### ISSUE TITLE
[syncfusion_flutter_datagrid] Problem with SfDataPager when change _rowsPerPage

### ISSUE THREAD

**Issue by NgoTruongThanh** [syncfusion/flutter-widgets#1558] opened 2023-12-05 04:50 UTC
When i change _rowsPerPage and showCheckBoxColumn is false. DataSource will change state by rowPerPage.
But when i change showCheckBoxColumn  to true. DataSource will be change state delay 1 step

**Comment by Tamilarasan-Paranthaman** [comment] 2024-02-09 13:49
Hi @NgoTruongThanh,

We have investigated this case on our end and encountered the same issue you have described. Considering this, we have logged a bug report in our feedback portal. We will fix the reported issue and include the changes in our weekly patch release, which is expected to be rolled out on February 27, 2024. We will let you know once it is published. 

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment] 2024-02-27 09:05
@NgoTruongThanh,

We are glad to inform you that the reported issue regarding the “The DataGrid did not update properly when changing rowsPerPage along with the DataPager and Checkbox column” has been resolved. This fix has been incorporated into our latest weekly patch release. To benefit from this fix, we recommend updating your DataGrid package to version **24.2.8**.
 
https://pub.dev/packages/syncfusion_flutter_datagrid   

**Root Cause of the issue:** The DataGrid is not properly refreshed when changing the rowsPerPage along with the checkbox column at runtime. As a result, the DataGrid does not update as intended.

We thank you for your support and appreciate your patience in waiting for this update.

Regards,
Tamilarasan

**Closed** 2024-03-01 01:14 UTC
Labels: bug, data_grid, solved
