### ISSUE TITLE
[syncfusion_flutter_xlsio] update image pakage to ^4.0.4 

### ISSUE THREAD

**Issue by Joseph-Nathan** [syncfusion/flutter-widgets#1023] opened 2023-01-04 00:40 UTC
Flutter : 3.3.0
when i try to build my ios app 
it failed due to image package ,
and when i update it i get error 

on flutter 3.3.x build ios failed with package image under 4.0.4
 `
Error: The getter 'data' isn't defined for the class 'ExifData'.
 'ExifData' is from 'package:image/src/exif/exif_data.dart'
 `

**Comment by KonduruKeerthi** [comment] 2023-01-16 12:23
We are checking your query and will get back to you with details on Jan 19th, 2023.

**Comment by KonduruKeerthi** [comment] 2023-01-20 12:02
We have checked the reported issue but are unable to reproduce it. Screenshots are given below for your reference.

![image](https://user-images.githubusercontent.com/93245531/213690422-f19718c5-96b3-4968-8059-629cbd14213a.png)

![image](https://user-images.githubusercontent.com/93245531/213690467-a2dd6e72-d769-4d29-ac55-6976e0c1314b.png)

Please send us a sample of reproducing the issue and confirm your iOS configuration so that we can investigate it further.

**Comment by danilocatalanoapsystem** [comment] 2023-01-20 16:23
Also I have the same problem I have a version of syncfusion_flutter_xlsio and I absolutely have to use the packages of image: 4.0.10 but after the flutter pub get it conflicts with the version of syncfusion_flutter_xlsio

**Comment by KonduruKeerthi** [comment] 2023-01-27 06:25
We have confirmed the issue as **Pub get failed while using the image package version above ^4.0.0** and logged a defect report. We will include the fix for this issue in our weekly NuGet release scheduled for the **second week of February 2023**. You will be informed regarding this once the fix is included.

 

You can track the status of this defect report through the feedback link below.

https://www.syncfusion.com/feedback/40609/pub-get-failed-while-using-the-image-package-version-above-4-0-0 

 

**Disclaimer:** Inclusion of this solution in the weekly release may change due to other factors including but not limited to QA checks and works reprioritization.

**Comment by RahulBalasundaramSF3494** [comment] 2023-02-10 13:49
We have included the fix for **Pub get failed while using the image package version above ^4.0.0** in our weekly NuGet release **version 20.4.49**. Please upgrade your package to this latest version to resolve the issue.

Latest NuGet Package: https://pub.dev/packages/syncfusion_flutter_xlsio/versions/20.4.49-beta

**Closed** 2024-03-19 11:00 UTC
Labels: xlsIO
