### ISSUE TITLE
[syncfusion_flutter_datagrid] Performance is terrible when use setState with SfDataPaper 

### ISSUE THREAD

**Issue by Trung15010802** [syncfusion/flutter-widgets#1721] opened 2024-03-08 09:03 UTC
I am using `syncfusion_flutter_datagrid: ^24.2.9,` if i use checkbox the performance is very bad:

**Without checkbox:**
The scroll and animation is very smooth

https://github.com/syncfusion/flutter-widgets/assets/90593296/b879242b-0fd3-4e39-b62b-6a653f2dd777

**With checkbox:**
The scroll is delayed and animation isn't smooth

https://github.com/syncfusion/flutter-widgets/assets/90593296/e2eb05fb-005a-49b7-a8fd-33965d3fb023

**Comment by Tamilarasan-Paranthaman** [comment] 2024-03-12 12:51
Hi @Trung15010802,

Based on the provided details, we have created a basic DataGrid sample and thoroughly tested it on our end. Regrettably, we were unable to replicate the reported scrolling performance issue, even when enabling checkboxes in the DataGrid.

We have attached the sample that we used for testing to this ticket for your reference. We kindly request that you review the attached sample and execute it on your end. Should any configurations or adjustments be necessary to accurately reproduce the issue, please modify the sample accordingly. Additionally, we would appreciate detailed steps for reproducing the issue along with the sample, as well as any other pertinent details.

<details>
<summary>Sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_datagrid/datagrid.dart';

void main() {
  runApp(const MaterialApp(home: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
          useMaterial3: false),
      home: const SfDataGridDemo(),
    );
  }
}

class SfDataGridDemo extends StatefulWidget {
  const SfDataGridDemo({super.key});

  @override
  SfDataGridDemoState createState() => SfDataGridDemoState();
}

class SfDataGridDemoState extends State<SfDataGridDemo> {
  List<Employee> _employees = <Employee>[];
  late EmployeeDataSource _employeeDataSource;

  @override
  void initState() {
    super.initState();
    _employees = getEmployeeData();
    _employeeDataSource = EmployeeDataSource(_employees);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text('Syncfusion Flutter DataGrid')),
        body: SfDataGrid(
          source: _employeeDataSource,
          columns: getColumns,
          selectionMode: SelectionMode.multiple,
          showCheckboxColumn: true,
        ));
  }

  List<GridColumn> get getColumns {
    return <GridColumn>[
      GridColumn(
          columnName: 'ID',
          label: Container(
              padding: const EdgeInsets.all(8.0),
              alignment: Alignment.center,
              child: const Text('ID'))),
      GridColumn(
          columnName: 'Name',
          label: Container(
              padding: const EdgeInsets.all(8.0),
              alignment: Alignment.center,
              child: const Text('Name'))),
      GridColumn(
          columnName: 'Designation',
          label: Container(
              padding: const EdgeInsets.all(8.0),
              alignment: Alignment.center,
              child:
                  const Text('Designation', overflow: TextOverflow.ellipsis))),
      GridColumn(
          columnName: 'Salary',
          label: Container(
              padding: const EdgeInsets.all(8.0),
              alignment: Alignment.center,
              child: const Text('Salary'))),
    ];
  }

  List<Employee> getEmployeeData() {
    return [
      Employee(10001, 'Jack', 'Manager', 150000),
      Employee(10002, 'Perry', 'Project Lead', 80000),
      Employee(10003, 'James', 'Developer', 55000),
      Employee(10004, 'Michael', 'Designer', 39000),
      Employee(10005, 'Roland Mendel', 'Developer', 45000),
      Employee(10006, 'Sven Ottlieb', 'UI Designer', 36000),
      Employee(10007, 'Williams', 'Developer', 44000),
      Employee(10008, 'Adams', 'Developer', 43000),
      Employee(10009, 'Edwards', 'QA Testing', 43000),
      Employee(10010, 'Grimes', 'Developer', 43000),
      Employee(10011, 'Maria Andres', 'Developer', 41000),
      Employee(10012, 'Thomas Hardy', 'Developer', 40000),
      Employee(10013, 'Hanna Moos', 'Sales Associate', 350000),
      Employee(10014, 'Elizabeth', 'Developer', 41000),
      Employee(10015, 'Patricio Simpson', 'Administrator', 33000),
      Employee(10016, 'Francisco Chang', 'Developer', 32000),
      Employee(10017, 'Yang Wang', 'Developer', 30000),
      Employee(10018, 'Peter Franken', 'Developer', 30000),
      Employee(10019, 'Carlos Schmitt', 'Developer', 30000),
      Employee(10020, 'Yoshi Latimer', 'Developer', 28000),
    ];
  }
}

class EmployeeDataSource extends DataGridSource {
  EmployeeDataSource(List<Employee> employees) {
    buildDataGridRows(employees);
  }

  List<DataGridRow> datagridRows = [];

  @override
  List<DataGridRow> get rows => datagridRows;

  void buildDataGridRows(List<Employee> employeesData) {
    datagridRows = employeesData
        .map<DataGridRow>((e) => DataGridRow(cells: [
              DataGridCell<int>(columnName: 'ID', value: e.id),
              DataGridCell<String>(columnName: 'Name', value: e.name),
              DataGridCell<String>(
                  columnName: 'Designation', value: e.designation),
              DataGridCell<int>(columnName: 'Salary', value: e.salary),
            ]))
        .toList();
  }

  @override
  DataGridRowAdapter buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((dataGridCell) {
      return Container(
        alignment: Alignment.center,
        padding: const EdgeInsets.symmetric(horizontal: 8.0),
        child: Text(dataGridCell.value.toString()),
      );
    }).toList());
  }
}

class Employee {
  Employee(this.id, this.name, this.designation, this.salary);
  final int id;
  final String name;
  final String designation;
  final int salary;
}

```
</details>

<details>
<summary>Output</summary>


https://github.com/syncfusion/flutter-widgets/assets/93904422/b07f5f75-3212-4950-948b-25e2f9fa1203


</details>

Regards,
Tamilarasan

**Comment by Trung15010802** [comment] 2024-03-19 04:02
When i enable check box my gridtable is being rebuilt continuously.
![image](https://github.com/syncfusion/flutter-widgets/assets/90593296/d4268456-4af5-4a89-a1e1-4234feffa871)

This link containt full source code. I try to write your package like a library for my app:
https://drive.google.com/file/d/1V16aTh0NqETkRXP7Rj10zLEkcpavI-KT/view?usp=sharing

**Comment by Trung15010802** [comment] 2024-03-19 04:10
```
// ignore_for_file: public_member_api_docs, sort_constructors_first
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:syncfusion_flutter_core/theme.dart';
import 'package:syncfusion_flutter_datagrid/datagrid.dart';

import 'package:stvg_package/src/controller/providers.dart';
import 'package:stvg_package/src/functions/excel_functions.dart';

import 'table_data_source.dart';

final DataPagerController dataPaperController = DataPagerController();

class GridTable<T> extends ConsumerStatefulWidget {
  final TableDataSource dataGridSource;
  final List<GridColumn> collums;
  final bool showCheckBox;
  final double rowHeight;
  final bool allowFiltering;
  final bool isLazyPaging;
  final bool allowSorting;
  final double headerRowHeight;
  final bool allowEditing;
  final int frozenColumnsCount;
  final List<String> totalColumns;
  final ColumnWidthMode columnWidthMode;
  final CallBack onFilterChanged;
  final SelectionMode selectionMode;
  final bool isScrollbarAlwaysShown;
  final SfDataGridThemeData dataGridThemeData;
  final ValueChanged<List<T>>? onSelected;
  final SfDataPagerThemeData? sfDataPagerThemeData;
  final List<int> availableRowsPerPage;
  final int visibleItemsCount;
  final int totalData;
  final int? rowsPerPage;
  final bool isLoading;
  final Widget? loadingWidget;
  const GridTable(
      {super.key,
      required this.dataGridSource,
      required this.collums,
      this.showCheckBox = false,
      required this.rowHeight,
      this.allowFiltering = false,
      this.allowSorting = false,
      required this.headerRowHeight,
      this.allowEditing = false,
      this.frozenColumnsCount = 0,
      required this.totalColumns,
      this.rowsPerPage,
      required this.isLoading,
      this.columnWidthMode = ColumnWidthMode.none,
      required this.onFilterChanged,
      required this.selectionMode,
      required this.isScrollbarAlwaysShown,
      required this.dataGridThemeData,
      this.onSelected,
      required this.visibleItemsCount,
      this.sfDataPagerThemeData,
      required this.totalData,
      required this.availableRowsPerPage,
      this.loadingWidget,
      required this.isLazyPaging});

  @override
  ConsumerState<GridTable> createState() => _TableState<T>();
}

class _TableState<T> extends ConsumerState<GridTable<T>> {
  late double pageCount;
  int lastIndex = 0;
  final DataGridController dataGridController = DataGridController();
  bool showLoadingIndicator = false;

  void _updatePageCount() {
    final rowsCount = widget.dataGridSource.filterConditions.isNotEmpty
        ? widget.dataGridSource.effectiveRows.length
        : widget.dataGridSource.list.length;
    pageCount = (rowsCount / rowsPerPage).ceilToDouble();
    if ((rowsCount % rowsPerPage) != 0) {
      lastIndex = rowsPerPage + 1;
    } else {
      lastIndex = rowsPerPage + 1;
    }
  }

  @override
  void initState() {
    rowsPerPage = widget.rowsPerPage ?? 10;
    _updatePageCount();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    debugPrint('Rebuild');
    double pageCount = ((widget.totalData / rowsPerPage).ceil()).toDouble();
    return LayoutBuilder(builder: (context, constraints) {
      return Column(
        children: [
          Expanded(
            child: SfDataGridTheme(
              data: widget.dataGridThemeData,
              child: _buildStack(constraints),
            ),
          ),
          SfDataPagerTheme(
            data: widget.sfDataPagerThemeData ?? const SfDataPagerThemeData(),
            child: SfDataPager(
                controller: dataPaperController,
                delegate: widget.dataGridSource,
                availableRowsPerPage: widget.availableRowsPerPage,
                onRowsPerPageChanged: (int? rows) {
                  setState(() {
                    rowsPerPage = rows!;
                    widget.dataGridSource.reloadCurrentPage();
                  });
                },
                visibleItemsCount: widget.visibleItemsCount,
                pageCount: pageCount != 0 ? pageCount : 1,
                onPageNavigationStart: (int pageIndex) {
                  if (!isInit) {
                    setState(() {
                      showLoadingIndicator = true;
                    });
                  }
                },
                onPageNavigationEnd: (int pageIndex) {
                  debugPrint('onPageNavigationEnd');
                  setState(() {
                    showLoadingIndicator = false;
                  });
                }),
          ),
        ],
      );
    });
  }

  Widget _buildStack(BoxConstraints constraints) {
    if (!widget.isLoading) {
      return _buildDataGrid();
    } else {
      List<Widget> getChildren() {
        final List<Widget> stackChildren = [];
        stackChildren.add(_buildDataGrid());
        if (showLoadingIndicator) {
          stackChildren.add(
            Container(
              color: Colors.black12,
              width: constraints.maxWidth,
              height: constraints.maxHeight,
              child: widget.loadingWidget ??
                  const Align(
                    alignment: Alignment.center,
                    child: CircularProgressIndicator(
                      strokeWidth: 3,
                    ),
                  ),
            ),
          );
        }
        return stackChildren;
      }

      return Stack(
        children: getChildren(),
      );
    }
  }

  Widget _buildDataGrid() {
    return ScrollConfiguration(
      behavior: const ScrollBehavior().copyWith(dragDevices: {
        PointerDeviceKind.touch,
        PointerDeviceKind.mouse,
      }),
      child: SfDataGrid(
        key: ref.read(dataGridKeyProvider),

        controller: dataGridController,
        allowFiltering: widget.allowFiltering,
        allowSorting: widget.allowSorting,
        allowEditing: widget.allowEditing,
        isScrollbarAlwaysShown: widget.isScrollbarAlwaysShown,
        frozenColumnsCount: widget.frozenColumnsCount,
        gridLinesVisibility: GridLinesVisibility.both,
        headerGridLinesVisibility: GridLinesVisibility.both,
        editingGestureType: EditingGestureType.tap,
        showCheckboxColumn: widget.showCheckBox,
        headerRowHeight: widget.headerRowHeight,
        columnWidthMode: widget.columnWidthMode,
        selectionMode: widget.selectionMode,
        source: widget.dataGridSource,
        navigationMode: GridNavigationMode.cell,
        columns: widget.collums,
        rowsPerPage: rowsPerPage,
        onSelectionChanged: (addedRows, removedRows) {
          final rows = dataGridController.selectedRows;
          final List<T> list = [];
          for (var row in rows) {
            list.add(row.getCells().last.value);
          }
          if (widget.onSelected != null) {
            widget.onSelected!(list);
          }
        },
        onQueryRowHeight: (details) {
          if (details.rowIndex == 0) return widget.headerRowHeight;
          // final int rowsPerPage = details.pageSize;
          // return  (details.rowIndex == lastIndex)? 90: widget.rowHeight;
          return widget.rowHeight;
        },
        // tableSummaryRows: [
        // if(widget.totalColumns.isNotEmpty)
        // GridTableSummaryRow(
        //     showSummaryInRow: true,
        //     columns: widget.totalColumns.map((e) => GridSummaryColumn(
        //         name: e,
        //         columnName: e,
        //         summaryType: GridSummaryType.sum,
        //     )).toList(),
        //     position: GridTableSummaryRowPosition.bottom)
        // GridTableSummaryRow(
        //     showSummaryInRow: true,
        //     columns: [GridSummaryColumn(
        //       name: 'a',
        //       columnName: 'SALARY',
        //       summaryType: GridSummaryType.sum,
        //     )],
        //     position: GridTableSummaryRowPosition.bottom)
        // ],
        onFilterChanged: (details) {
          _updatePageCount();
          lastIndex = widget.dataGridSource.effectiveRows.length + 1;
          widget.onFilterChanged(lastIndex);
        },
      ),
    );
  }
}

```

I find the issue that onPageNavigationEnd is called multple time when i enable checkbox

**Comment by abineshPalanisamy** [comment] 2024-03-21 13:26
Hi @Trung15010802 ,
 
Thank you for providing the sample. Following our testing, we have confirmed that this is indeed a bug. A bug report has been logged in our feedback portal to address this issue. We are committed to resolving the reported issue and will incorporate the necessary changes in the upcoming weekly patch release, scheduled for rollout on April 02, 2024. We will let you know once released. We appreciate your patience and understanding until then.
 
Regards,
Abinesh P

**Comment by abineshPalanisamy** [comment] 2024-04-03 10:02
Hi @Trung15010802 ,
 
We are glad to inform you that the reported problem has been resolved on our end. Therefore, kindly update SfDataGrid to the latest version. If you have any further queries, please don't hesitate to reach out. We are more than happy to assist you.
 
Regards,
Abinesh P

**Comment by Trung15010802** [comment] 2024-04-12 04:04
Hi @abineshPalanisamy, 
I realized that the issue hasn't been resolved. Tested on latest version
![image](https://github.com/syncfusion/flutter-widgets/assets/90593296/a212c9f0-0291-40d8-8a96-5d34e33b0416)

**Comment by Trung15010802** [comment] 2024-04-12 04:06
And next page button not trigger `onPageNavigationStart `function, previous page not trigger `onPageNavigationEnd`
![image](https://github.com/syncfusion/flutter-widgets/assets/90593296/515b6791-7ad8-4602-8ac5-0546c88db99f)

**Comment by abineshPalanisamy** [comment] 2024-04-12 10:42
Hi @Trung15010802,
 
Based on the information provided, the issue mentioned is that performance is terrible when using setState with SfDataPager. This unintended call to the paging callbacks results in multiple setState triggers, causing the SfDataPager to rebuild each time setState is invoked. Therefore, we have restricted unwanted calls without requiring page navigation. During the initial loading phase, we allow callbacks to be made, this is the expected behavior of pagination callbacks. Kindly check whether the performance stabilizes after restricting the SfDataPager from rebuilding each time setState is invoked.
 
We are investigating the issue where the next and previous page buttons do not trigger page callbacks. In the meantime, we will provide further details. 

If you are still encountering the performance problem, we kindly ask you to provide any additional clear details regarding the performance issue when using SfDataPager. This additional information will greatly aid us in further investigating the matter and delivering an appropriate solution as promptly as possible.

Regards,
Abinesh P

**Closed** 2024-04-12 13:43 UTC
Labels: bug, data_grid, follow-up scheduled
