### ISSUE TITLE
The method 'markNeedsBuild' isn't defined for the class 'RenderConstrainedLayoutBuilder<Constraints, RenderObject>'

### ISSUE THREAD

**Issue by harsh-171095** [syncfusion/flutter-widgets#1907] opened 2024-06-06 08:06 UTC
### Bug description

while I reinstall latest version and try to build a app getting issue 

```
 - 'RenderConstrainedLayoutBuilder' is from 'package:flutter/src/widgets/layout_builder.dart' ('../../../Flutter_SDK/flutter/packages/flutter/lib/src/widgets/layout_builder.dart').
 - 'Constraints' is from 'package:flutter/src/rendering/object.dart' ('../../../Flutter_SDK/flutter/packages/flutter/lib/src/rendering/object.dart').
 - 'RenderObject' is from 'package:flutter/src/rendering/object.dart' ('../../../Flutter_SDK/flutter/packages/flutter/lib/src/rendering/object.dart').
Try correcting the name to the name of an existing method, or defining a method named 'markNeedsBuild'.
        renderObject.markNeedsBuild();
                     ^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-25.2.7/lib/src/charts/common/element_widget.dart:113:5: Error: The method 'markNeedsBuild' isn't defined for the class 'RenderChartElementLayoutBuilder<T, D>'.
 - 'RenderChartElementLayoutBuilder' is from 'package:syncfusion_flutter_charts/src/charts/common/element_widget.dart' ('../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-25.2.7/lib/src/charts/common/element_widget.dart').
Try correcting the name to the name of an existing method, or defining a method named 'markNeedsBuild'.
    markNeedsBuild();
    ^^^^^^^^^^^^^^
Failed to compile application.
```

### Steps to reproduce

1. install 'syncfusion_flutter_charts: ^25.2.6'
2. build App

### Code sample

build issue

### Screenshots or Video

No

### Stack Traces

No

### On which target platforms have you observed this bug?

Web

### Flutter Doctor output

```
../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-25.2.7/lib/src/charts/cartesian_chart.dart:1367:22: Error: The method 'markNeedsBuild' isn't defined for the class 'RenderConstrainedLayoutBuilder<Constraints, RenderObject>'.
 - 'RenderConstrainedLayoutBuilder' is from 'package:flutter/src/widgets/layout_builder.dart' ('../../../Flutter_SDK/flutter/packages/flutter/lib/src/widgets/layout_builder.dart').
 - 'Constraints' is from 'package:flutter/src/rendering/object.dart' ('../../../Flutter_SDK/flutter/packages/flutter/lib/src/rendering/object.dart').
 - 'RenderObject' is from 'package:flutter/src/rendering/object.dart' ('../../../Flutter_SDK/flutter/packages/flutter/lib/src/rendering/object.dart').
Try correcting the name to the name of an existing method, or defining a method named 'markNeedsBuild'.
        renderObject.markNeedsBuild();
                     ^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-25.2.7/lib/src/charts/base.dart:3225:7: Error: The method 'markNeedsBuild' isn't defined for the class 'RenderLoadingIndicator'.
 - 'RenderLoadingIndicator' is from 'package:syncfusion_flutter_charts/src/charts/base.dart' ('../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-25.2.7/lib/src/charts/base.dart').
Try correcting the name to the name of an existing method, or defining a method named 'markNeedsBuild'.
      markNeedsBuild();
      ^^^^^^^^^^^^^^

```

**Comment by mdeport** [comment] 2024-06-07 10:17
I have the same error

../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-25.2.7/lib/src/charts/cartesian_chart.dart:1367:22: Error: The method 'markNeedsBuild' isn't defined for the class 'RenderConstrainedLayoutBuilder<Constraints, RenderObject>'.
 - 'RenderConstrainedLayoutBuilder' is from 'package:flutter/src/widgets/layout_builder.dart' ('../../../flutterdev/flutter/flutter/packages/flutter/lib/src/widgets/layout_builder.dart').
 - 'Constraints' is from 'package:flutter/src/rendering/object.dart' ('../../../flutterdev/flutter/flutter/packages/flutter/lib/src/rendering/object.dart').
 - 'RenderObject' is from 'package:flutter/src/rendering/object.dart' ('../../../flutterdev/flutter/flutter/packages/flutter/lib/src/rendering/object.dart').
Try correcting the name to the name of an existing method, or defining a method named 'markNeedsBuild'.
        renderObject.markNeedsBuild();
                     ^^^^^^^^^^^^^^

**Comment by LokeshPalani** [comment] 2024-06-11 14:18
Hi @harsh-171095 | @mdeport,

We have checked the reported issue and tried to replicate it in the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/SfCartesianChart.html) with version [26.1.35](https://pub.dev/packages/syncfusion_flutter_charts/versions/26.1.35) by setting [builder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior/builder.html) property of [TrackballBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior-class.html). And, we have tested with the following scenarios.


- Tested with all layout widget by adding Row, Column, SizedBox, Container and Card inside the [builder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior/builder.html) property of [TrackballBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior-class.html).
- Tested with setting chart as Stateless widget and added TextButton inside the [builder](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior/builder.html) property of [TrackballBehavior](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/TrackballBehavior-class.html).

However, we were unable to reproduce the reported issue at our end. We kindly request you to replicate the reported issue in the sample attached below and provide us with more details regarding the specific scenario in which you encounter the issue with a screenshot or screen recording. This will help us to assist you more effectively.

Regards,
Lokesh P.

**Comment by TruongGlacio** [comment] 2024-06-12 04:29
Hi @LokeshPalani , 
Please reproduce with flutter sdk min version 3.22.2. This issuse happen with flutter sdk greater than 3.22.2.
I am using flutter sdk 3.23.0-13.pre.145 from flutter Master channel, and this issue has happen

**Comment by harsh-171095** [comment] 2024-06-12 18:51
Hello @TruongGlacio 
       Yes, I was try with the same Flutter SDK Version 3.22.2 and now it working fine. 

Might be new flutter SDK Support are not done yet on library.

**Comment by mdeport** [comment] 2024-06-13 19:46
hello @TruongGlacio
thanks for the information now everything works fine

**Comment by LokeshPalani** [comment] 2024-06-14 01:06
Hi @mdeport | @harsh-171095  | @TruongGlacio,

We would like to inform you that our latest Syncfusion Flutter packages are now only compatible with the latest Stable Flutter SDK version. We do not have plans to migrate the packages to the master channel as it is not a stable version and is still in the development phase. Therefore, we suggest using the latest Stable Flutter SDK to utilize our Syncfusion packages.

Furthermore, we have provided a link to the User Guide documentation below, which specifies the compatible Syncfusion package version for each Flutter SDK version.

UG Link: https://help.syncfusion.com/flutter/system-requirements#sdk-version-compatibility  

Regards,
Lokesh P.

**Comment by babihutan** [comment] 2024-08-08 13:41
Well, flutter stable just got upgraded, so now my syncfusion pkgs don't work.

**Comment by kyleorin** [comment] 2024-08-10 18:45
> Well, flutter stable just got upgraded, so now my syncfusion pkgs don't work.

same here

**Comment by newselfDevops** [comment] 2024-08-12 08:05
![image](https://github.com/user-attachments/assets/49409f46-5516-4d8e-9007-a6fd629c082c)

same error on Flutter 3.24.0, what can I do?

**Comment by namhoangdev31** [comment] 2024-08-13 09:49
same error on Flutter 3.24.0, what can I do?
Please help me

**Comment by namhoangdev31** [comment] 2024-08-13 09:54
same error on Flutter 3.24.0, what can I do?
<img width="1138" alt="Ảnh màn hình 2024-08-13 lúc 16 53 38" src="https://github.com/user-attachments/assets/7abaaa04-1018-4670-af95-d6dd04f0e66c">

**Comment by yknevenky** [comment] 2024-08-13 11:18
I too face the same

**Comment by achilov1206** [comment] 2024-08-13 11:32
Same issue with latest stable version of Flutter 3.24.0

**Comment by babihutan** [comment] 2024-08-13 11:35
My workaround to get it to build is to use the 3.23 version of flutter:

```
Flutter 3.23.0-0.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 2feea7a407 (10 weeks ago) • 2024-06-06 10:19:10 +0700
Engine • revision bb10c54666
Tools • Dart 3.5.0 (build 3.5.0-180.3.beta) • DevTools 2.36.0
```

**Comment by mukul218** [comment] 2024-08-13 12:29
I am also facing same issue with latest flutter version Flutter 3.24.0

**Comment by AmmarTN** [comment] 2024-08-13 13:18
Same here any updates or workaround it yet?

**Comment by rakeshdas369** [comment] 2024-08-13 19:19
me also facing the same issues.

**Comment by flocbit** [comment] 2024-08-14 07:55
Yup, same problem.

**Comment by adityadua24** [comment] 2024-08-14 12:27
same problem ! Please tag me when someone fixes this 😅

**Comment by aryata777** [comment] 2024-08-14 14:48
I am also facing same issue with latest flutter version Flutter 3.24.0

**Comment by pctin** [comment] 2024-08-15 08:50
Same problem with flutter 3.24.0

**Comment by shahinshopon** [comment] 2024-08-16 21:24
I am also facing the same issue with the latest Flutter version 3.24.0
To solve this problem I have followed this : 

../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-26.2.9/lib/src/charts/common/element_widge
t.dart:117 ( Here 117 means line number )
../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-26.2.9/lib/src/charts/base.dart:3317 ( Here 3317 means line number )
../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-26.2.9/lib/src/charts/cartesian_chart.dart:1367 ( Here 1367 means line number )
../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-26.2.9/lib/src/charts/common/core_tooltip.dart:168 ( Here 168 means line number )
../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_charts-26.2.9/lib/src/charts/common/core_legend.dart:452 ( Here 452 means line number )
Just need to change markNeedsBuild to markNeedsLayout In this dart file.
Hope the problem will be solved.

**Comment by temuujinnn** [comment] 2024-08-19 08:09
I am also facing the same issue with the latest Flutter version 3.24.0

**Comment by gaddlord** [comment] 2024-08-19 08:33
I have downgraded all Syncfusion libs to  22.2.9 to bypass the problem. That forced also intl to go down to "intl: ^0.18.0"

syncfusion_flutter_charts: ^22.2.9 # HACK Downgraded due to https://github.com/syncfusion/flutter-widgets/issues/1907

**Comment by ahmeedev** [comment] 2024-08-19 09:05
same issue

**Comment by Steven-Douglass** [comment] 2024-08-19 12:23
same issue

**Comment by MoonEunki** [comment] 2024-08-21 08:42
I'm using syncfusion_flutter_charts: ^26.2.10, 
and after switching to Flutter version 3.22.1 using FVM, it works

**Comment by prologikus** [comment] 2024-08-22 11:22
reopen this issue as it's faced in the lasted flutter sdk

**Comment by Steven-Douglass** [comment] 2024-08-22 15:53
Same issue

**Comment by aktarulahsan** [comment] 2024-08-25 10:21
I have solution. 

Solution : go to this path

 ('../../../../Development/flutter/packages/flutter/lib/src/rendering/object.dart').

and write a function like 

void markNeedsBuild() {}
now run your project.

**Comment by mahfuzur32785** [comment] 2024-08-25 12:08
1. On Windows: It might be in C:\flutter or another directory where you extracted it.

2. Navigate to the Target File
Once you've located the SDK:

Go to the packages/flutter/lib/src/widgets/ directory.
Open the layout_builder.dart file in a text editor.

3. Modify the layout_builder.dart File
Find the RenderConstrainedLayoutBuilder mixin and add the markNeedsBuild method:

dart
Copy code
mixin RenderConstrainedLayoutBuilder on RenderObject {
  // Other existing code...

  void markNeedsBuild() {
    markNeedsLayout();
  }
}

**Comment by Ander0106** [comment] 2024-08-27 06:00
solution is in this link,  to me the problem is al ready
https://stackoverflow.com/questions/78882125/how-to-solve-the-issue-of-renderobject-markneedsbuild-not-present-in-flutter

**Comment by JakDeveloper** [comment] 2024-08-27 06:05
> 1. On Windows: It might be in C:\flutter or another directory where you extracted it.
> 2. Navigate to the Target File
>    Once you've located the SDK:
> 
> Go to the packages/flutter/lib/src/widgets/ directory. Open the layout_builder.dart file in a text editor.
> 
> 3. Modify the layout_builder.dart File
>    Find the RenderConstrainedLayoutBuilder mixin and add the markNeedsBuild method:
> 
> dart Copy code mixin RenderConstrainedLayoutBuilder on RenderObject { // Other existing code...
> 
> void markNeedsBuild() { markNeedsLayout(); } }

This works.

**Comment by moin-maniar** [comment] 2024-08-28 11:14
I am using flutter 3.22.0 and facing the same issue. Is there any luck?

**Comment by aktarulahsan** [comment] 2024-08-28 14:58
I have solution.

Solution : go to this path

('../../../../Development/flutter/packages/flutter/lib/src/rendering/object.dart').

and write a function like

void markNeedsBuild() {
markNeedsLayout();
}
now run your project.
you can see more
https://stackoverflowjava.blogspot.com/2024/08/error-method-markneedsbuild-isnt.html

**Comment by ekuleshov** [comment] 2024-09-02 19:27
It is very disappointing to see it taking 3 months and over 30 reports to fix an issue related to using a deprecated Flutter API.

A proposed solution to downgrade Flutter is no go -  many packages bumped their minimal version of SDK.

**Comment by saurabhkumar-sk** [comment] 2024-09-03 11:06
#workaround was to edit packages/flutter/lib/src/widgets/layout_builder.dart, find mixin RenderConstrainedLayoutBuilder and add there this code:

  void markNeedsBuild() {
    markNeedsLayout();

}

**Comment by ekuleshov-idexx** [comment] 2024-09-03 11:17
If the fix is that simple, what is stopping Syncfusion from replacing that method call in 4 places in their package(s) and releasing an update today?

**Comment by ekuleshov** [comment] 2024-09-03 11:19
If the fix is that simple, what is stopping Syncfusion from replacing that method call in 4 places in their package(s) and releasing an update today?

**Comment by jeanlucthumm** [comment] 2024-09-03 15:23
@ekuleshov notice the solution involves changing internal Flutter code so it's not really a solution

**Comment by ekuleshov** [comment] 2024-09-03 15:27
> @ekuleshov notice the solution involves changing internal Flutter code so it's not really a solution

I am well aware. It can't be used with any CI or automated build systems. My comment was about changing the Syncfusion chart package to replace all calls to deprecated/removed method with a method that is being rerouted to. Shouldn't take more than 30 seconds to do so and definitely not 3 months.

**Comment by gakuru** [comment] 2024-09-03 17:50
Using Flutter 3.24.1
The issue mostly seems to be emanating from the **markNeedsBuild**, apparently changing it to **markNeedsLayout** seems to make the build run

**Comment by robinmonsere** [comment] 2024-09-05 19:54
Any updates on this?

**Comment by babahmed** [comment] 2024-09-05 19:58
> Any updates on this?

None, 3 releases within the last month, and non fixes the issue.

**Comment by ekuleshov** [comment] 2024-09-06 12:56
> None, 3 releases within the last month, and non fixes the issue.

Most of these releases are just a version bump.
E.g. where was no code changes between 26.2.13 and 26.2.12.
That is a misleading practice IMHO.

**Comment by babahmed** [comment] 2024-09-06 13:38
> > None, 3 releases within the last month, and non fixes the issue.
> 
> Most of these releases are just a version bump. E.g. where was no code changes between 26.2.13 and 26.2.12. That is a misleading practice IMHO.

There is a message on another thread where they mentioned it would be fixed in next week's release.

**Comment by ApplySci** [comment] 2024-09-07 04:53
> > None, 3 releases within the last month, and non fixes the issue.
> 
> Most of these releases are just a version bump. E.g. where was no code changes between 26.2.13 and 26.2.12. That is a misleading practice IMHO.

Why are they just doing version bumps, I wonder? Is there some gaming of popularity / recency algorithm somewhere?

**Comment by robinmonsere** [comment] 2024-09-07 09:47
> There is a message on another thread where they mentioned it would be fixed in next week's release.

Do you have a link to this?

**Comment by ekuleshov** [comment] 2024-09-07 15:24
> Do you have a link to this?

Scroll up - https://github.com/syncfusion/flutter-widgets/issues/1907#issuecomment-2306720375

> Why are they just doing version bumps, I wonder? Is there some gaming of popularity / recency algorithm somewhere?

My guess is either they want package to bump to the top of the recent ones on pub.dev or being lazy/negligent to update versions separately on individual packages (a really misleading practice and abuse of the public package repositories).

**Comment by babahmed** [comment] 2024-09-07 20:24
> > There is a message on another thread where they mentioned it would be fixed in next week's release.
> 
> Do you have a link to this?

Here: https://github.com/syncfusion/flutter-widgets/issues/2050

**Comment by AliEsmaeil** [comment] 2024-09-07 20:38
check that [answer](https://stackoverflow.com/questions/78896982/error-the-method-markneedsbuild-isnt-defined-for-the-class-renderloadingind/78961053#78961053)

**Comment by ThilipChandru** [comment] 2024-09-11 05:33
Hi all,


Thank you for your patience. We have upgraded our Flutter Charts package to be compatible with Flutter SDK 3.24.0. We kindly request you to upgrade [Flutter Charts](https://pub.dev/packages/syncfusion_flutter_charts/versions/26.2.14) to the latest version.

Regards,
Thilip Chandru.

**Comment by m4ndil** [comment] 2024-09-15 04:54
> void markNeedsBuild() {
> markNeedsLayout();
> }

Worked for me

**Comment by LavanyaGowtham2021** [comment] 2024-09-24 10:29
Please let us know if you need any further on this.

**Closed by LavanyaGowtham2021** 2024-09-24 10:29 UTC
Labels: charts, waiting for customer response

**Comment by chahrlens** [comment] 2024-10-11 22:16
It's not the best solution, but it works for a tight spot.
edit the file:
path-to-flutter-sdk/packages/flutter/lib/src/rendering/object.dart

and add at the end:

void markNeedsBuild() {
markNeedsLayout();
}

This has worked for me.

**Comment by LavanyaGowtham2021** [comment] 2024-10-14 07:25
https://github.com/syncfusion/flutter-widgets/issues/1907#issuecomment-2342659790 As per this update we have updated our package with latest SDK 3.24. We kindly request you to upgrade [Flutter Charts](https://pub.dev/packages/syncfusion_flutter_charts/versions/26.2.14) to the latest version.
