### ISSUE TITLE
[SfDatagrid] Accessibility: Screenreader reads every cell as "Clickable"

### ISSUE THREAD

**Issue by DaathGit** [syncfusion/flutter-widgets#1652] opened 2024-02-01 14:53 UTC
Hello everyone,
i'm implementing accessibility for a Flutter application that's using SfDatagrid.
I noticed that (using NVDA and running the project on web), every table cell is read as "Clickable", even if it only contains a simple text (in which case it reads: "Clickable, *text*".
Is there any way to just read the text, without the "Clickable" part?

**Comment by Tamilarasan-Paranthaman** [comment] 2024-02-05 14:03
Hi @DaathGit,

Does this issue only occur when tapping values in the DataGrid, or do you also encounter the same problem when tapping on other widgets, such as Text widgets?

We are not sure about how you load the values and which widgets are loaded in the DataGrid cells. Could you please test using the provided basic sample and let us know if the issue persists?

**Sample Link: [Flutter-DataGrid-Sample](https://github.com/syncfusion/flutter-widgets/files/14166570/Sample.zip)**


Regards,
Tamilarasan

**Comment by DaathGit** [comment] 2024-02-05 14:18
Hi Tamilarasan,

I downloaded the DataGrid Sample and started the app.
The problem persists in this case, too. Using NVDA, and the arrow keys (up/down) to "move between" / "read" the elements of the page, it reads "Clickable" on every table cell.

Reading simple Text widgets outside the table doesn't show this problem.

**Comment by Tamilarasan-Paranthaman** [comment] 2024-02-08 14:34
@DaathGit,

Thank you for the update. We have also replicated the behavior you described on our end while using NVDA. After further investigation, we confirmed that NVDA reports elements as clickable if they have associated event handlers for **click**, **mouseDown**, or **mouseUp** events.

In the current implementation of the DataGrid, we utilize the **GestureDetector** widget within DataGridCell to detect interaction actions such as **onCellTap** and **onCellDoubleTap**. This design ensures that every cell in the DataGrid has support for interaction actions. Consequently, NVDA announces elements as clickable due to this behavior. Unfortunately, at this time, we do not have a workaround available for this. 

As an additional observation, you can wrap the **Text** widget as a child of the **GestureDetector** widget, and NVDA will announce the text value with "Clickable" (Clickable text value). 

```dart
GestureDetector(
              onTap: () {}, child: Text('Text widget with gesture recognizer')),
```
You can find more details in the following NVDA [repository](https://github.com/nvaccess/nvda/issues/5830#issuecomment-199778283).

**Comment by DaathGit** [comment] 2024-02-09 06:46
Hi Tamilarasan,
I understand, thank you for your help.

**Comment by ashok-kuvaraja** [comment] 2024-02-12 04:46
Hi @DaathGit,

We suspect that the given explanation has helped you to understand the problem in NVDA. We are closing this issue. If you need any more help, please don't hesitate to reopen this. We are always happy to help you.

Regards,
Ashok K

**Closed by ashok-kuvaraja** 2024-02-12 04:46 UTC
Labels: data_grid
