### ISSUE TITLE
[syncfusion_flutter_calendar] CalendarView.months and CalendarView.weeks

### ISSUE THREAD

**Issue by AAverin** [syncfusion/flutter-widgets#1097] opened 2023-02-26 11:35 UTC
It would be great to have two extra modes for CalenarView – many months overview and month weeks overview. This would allow to build overviews of events that span around weeks and months.

**Many months overview/year overview**
Calendar should display months one after another over the period of a few years. Here is an example of one year view from Google Calendar. View should be configurable to hide and show days.
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/1481332/221407796-9d7250d2-cee2-4179-9ae7-ddb214c55133.png">

**Many weeks overview***
Calendar should display weeks one after another where every week is a single cell. Cell should be customisable to either display start of the week or Calendar Week Number, or some custom value.

**Comment by MuniappanSubramanian** [comment] 2023-02-27 12:28
**Regarding Many months’ overview/year overview**

As of now, the Flutter calendar does not have support for " **Month Dates view in the Year in the Flutter Calendar**" and we have logged a feature request for the same. We will implement this feature in any of our upcoming releases.   

At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. We will let you know when this feature is implemented. We appreciate your patience until then.  

Thank you for requesting this feature and helping us define it. We are always trying to make our products better and feature requests like yours are a key part of our product growth efforts.  

You can also communicate with us regarding the open features at any time using our Feature Report page.   

We will prioritize the features every release based on the demands and we do not have an immediate plan to implement this feature since we committed to already planned work. So, this feature will be available in any of our upcoming releases.   

Please upvote these features to make this our priority. While this feature itself is important we will prioritize the features every release, based on the user demands. So, this feature will be available in any of our upcoming releases  

Feedback link:  https://www.syncfusion.com/feedback/41553/provide-support-for-month-dates-view-in-the-year-view-of-the-flutter-calendar

If you have any more specifications/suggestions for the feature request, you can add them as a comment in the portal and cast your vote to make it count.  

**Regarding Many week's overviews**

In the Flutter Calendar, you can customize the number of weeks in the month view by using the numberOfWeeksInView property in MonthView. Refer to our UG documentation to achieve your requirement,

https://help.syncfusion.com/flutter/calendar/month-view#customize-number-of-month-rows

**Comment by AAverin** [comment] 2023-02-27 12:38
@MuniappanSubramanian Thanks, I will watch the Year overview feature request.

For the number of weeks displayed, I can't get >6.
What I want to achieve is overview of many weeks on the same screen where appointments happen weekly. "Many" is 20+ weeks displayed at the same time. Every week can be represented as once cell or as one row.

**Comment by Indumathi1195R** [comment] 2023-04-24 04:42
AAverin,


You can’t set the numberOfWeeksInview above 6. As per the current implementation of the calendar, the default value is 6, so you can’t set it above the default value, and it is an expected behavior of the calendar. So you can’t show many weeks in a single view.

**Closed** 2023-05-30 10:10 UTC
