### ISSUE TITLE
[SfCartesianChart] [Flutter] How to get real pointIndex on tapped dataSource on FastLineSeries

### ISSUE THREAD

**Issue by LazyLazyCoder** [syncfusion/flutter-widgets#1925] opened 2024-06-13 12:32 UTC
### Use case

Hello

I can't find a way to get dataSource index when I click on dataSource chart. onPointTap give pointIndex, but is only valid to visible view range (defined by autoScrollingDelta). I need to get real pointIndex to move marker on the map

Thanks

### Proposal

Help response

**Comment by LokeshPalani** [comment] 2024-06-20 01:59
Hi @LazyLazyCoder,


We can be able to replicate the reported issue regarding **‘Did not get correct pointIndex when tap on the FastLineSeries with autoScrollingDelta’** on our end and the issue is scheduled to be fixed in our **weekly patch release,** which is expected to be rolled out on **July 2, 2024**. We will notify you here once the release has been rolled out, and we appreciate your patience in the meantime.

Regards,
Lokesh P.

**Comment by LokeshPalani** [comment] 2024-07-02 14:30
Hi @LazyLazyCoder,

The reported issue is fixed, and the fix published in the below version. Therefore, we kindly request that you upgrade the **syncfusion_flutter_charts** package to the latest version below to avoid this issue.

**Version**: https://pub.dev/packages/syncfusion_flutter_charts/versions/26.1.40    

**Root cause:** Index calculated from segment index instead of finding the nearest point, since the fast line series is a single-segment series.
  
Regards,
Lokesh P.

**Comment by LazyLazyCoder** [comment] 2024-07-04 08:19
Hello

Currently, our team has moved to another library. If it doesn't work, we'll go back to syncfusion and I'll be able to check the fix and give you an answer. Thank You.

**Closed** 2024-07-29 05:55 UTC
Labels: bug, charts, fixed
