### ISSUE TITLE
EmptyPointMode.gap with tooltip

### ISSUE THREAD

**Issue by FabioNieVec** [syncfusion/flutter-widgets#1793] opened 2024-04-10 10:10 UTC
Hello,

I'm trying to implement a graph that uses a tool tip and "deleting" all the null values. If I try this -> 

```
SfCartesianChart(
                  palette: [Theme.of(context).primaryColor],
                  series: [
                    LineSeries<ChartData, int>(
                      dataSource: [
                        ChartData(1, 100),
                        ChartData(2, null),
                        ChartData(3, 150),
                        ChartData(4, 200),
                        ChartData(5, 300),
                        ChartData(6, 400),
                      ],
                      markerSettings: const MarkerSettings(isVisible: true),
                      animationDuration: 0,
                      xValueMapper: (ChartData data, _) => data.x,
                      yValueMapper: (ChartData data, _) => data.y,
                      emptyPointSettings: const EmptyPointSettings(
                        mode: EmptyPointMode.gap,
                      ),
                    ),
                  ],
                    primaryXAxis: const NumericAxis(),
                    primaryYAxis: const NumericAxis(
                      edgeLabelPlacement: EdgeLabelPlacement.shift,
                      minimum: 0,
                    ),
                  tooltipBehavior: TooltipBehavior(
                    enable: true,
                  ),
                )
```

It will create the gap but when I hover over the second point it shows me the data from: ChartData(2, null) if I hover over the next one I get ChartData(4, 200). I somehow always skip the third entry, but not the second.

I'm using the newest version at the moment.

![image](https://github.com/syncfusion/flutter-widgets/assets/32736671/a1a9e43c-2f2e-49ac-80c7-587f45ac8598)

![image](https://github.com/syncfusion/flutter-widgets/assets/32736671/5f081a5b-68c5-48c6-a92c-7efa5ee33970)

**Comment by LokeshPalani** [comment] 2024-04-15 17:35
Hi @FabioNieVec, 

 

We have checked the reported issue that getting the wrong tooltip value when having empty points in the line series getting reproduced at our end. We will fix and include this issue in our upcoming weekly patch release, expected to be rolled out on April 30, 2024. We will update here once the fix has been rolled out and we appreciate your patience until then.

 

Regards,
Lokesh P.

**Comment by LokeshPalani** [comment] 2024-04-25 03:03
Hi @FabioNieVec,

 

We would like to let you know that the reported issue is fixed and rolled out in our patch release. We kindly request you to upgrade the syncfusion_flutter_charts package to the latest version below. 

 

 Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/25.1.41+1

 

Root cause: Missed to check the whether the segment y value is empty point while getting the tooltip value.

 

If you have any further queries, please feel free to reach out to us.

 

Regards,
Lokesh P.

**Closed** 2024-05-15 04:47 UTC
Labels: bug, charts, fixed
