### ISSUE TITLE
Flutter web syncfusion datagrid begin edit not start properly on tab key press

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#1129] opened 2023-03-14 16:32 UTC
when i press tab key speedly and input some value some time cell begin edit not start as you can see in video

https://user-images.githubusercontent.com/62530396/225073358-d4504053-826f-4cb3-aa72-6cd4aee9ea83.mp4

[grid_sample.zip](https://github.com/syncfusion/flutter-widgets/files/10971100/grid_sample.zip)

**Comment by Tamilarasan-Paranthaman** [comment] 2023-03-16 05:18
Hi @abdulrehmananwar,

We have tested the shared sample with the latest DataGrid version **20.4.54** and Flutter version 3.7.7. We were unable to reproduce the reported issue on our end. We noticed that you have set the read-only property for the "amount" column. However, we were able to confirm that the "beginEdit" function was called correctly and the cell entered the edit mode for all columns except the "amount" column. We have provided a reference video for your convenience.


https://user-images.githubusercontent.com/93904422/225521621-a2fc2f09-27af-47c7-8bfb-e3290afe30ec.mp4



Regards,
Tamilarasan

**Comment by abdulrehmananwar** [comment] 2023-03-16 05:30
**you can check screen shot get from your shared video. cell begin edit not started at that cell. it happed some time when i do work speedy please resolve this issue thanks.**
![image](https://user-images.githubusercontent.com/62530396/225523156-03b6fe2d-8e11-4666-9279-bc7e661457c3.png)

**Comment by abdulrehmananwar** [comment] 2023-03-24 07:02
still facing same issue also update to syncfusion_flutter_datagrid: ^21.1.35 butt facing same issue some time it struck and cell begin edit not start then i press tab key and again press shift tab key then begin edit started.
not shower butt it may be happend on low specs system.

**Comment by abdulrehmananwar** [comment] 2023-05-26 05:56
some time still its happening when i press tab key . beginedit not started so i have to click on cell to start begin edit. could it possible for you to make functionality like  c# windows form datagridview in which when we press any key on focused cell that keyvalue entered in focused cell

**Comment by abdulrehmananwar** [comment] 2023-05-30 10:14
please reply on it thanks

**Comment by Tamilarasan-Paranthaman** [comment] 2023-06-09 14:41
Based on the provided sample, it seems that you are using a workaround with the tab key inside the post-framework callback to move to the next cell and initiate editing. Additionally, you are adding a new row in the onCellSubmit method and refreshing the DataGrid by calling **notifyListeners**. However, please note that calling **notifyListeners** while a cell is in edit mode may cause unintended behavior. It can result in the DataGrid resetting various properties, including **committing the current cell's value** and other editing-related details.

**Regarding: could it possible for you to make functionality like C# windows form datagridview in which when we press any key on focused cell that key value entered in focused cell.**

Based on the current implementation and structure of the DataGrid, the standard behavior is to initiate the editing of a cell by tapping or double tapping the cell, depending on the value of the SfDataGrid.editingGestureType property. This design ensures consistency and adheres to the expected behavior of the DataGrid.

By default, you cannot directly type or enter a value into a focused cell without initiating the editing process. The purpose of the editing gesture is to provide a deliberate action from the user to indicate their intention to modify the cell's value.

**Comment by abdulrehmananwar** [comment] 2023-06-15 05:34
good point i    set on CustomSelectionManager as below butt now problem is that event on **canSubmitCell** it cell not to submit it also goes endEdit() how to resolve this issue on  **canSubmitCell**

if (keyEvent.logicalKey == LogicalKeyboardKey.tab) {
      if(dataGridController.isCurrentCellInEditing)
      {
        await dataGridController.endEdit();
      }

**Comment by Tamilarasan-Paranthaman** [comment] 2023-06-19 14:28
In the provided code snippet, the **DataGridController.endEdit()** method is called within the **handleKeyEvent** function. In the DataGrid implementation, **handleKeyEvent** is triggered before the **canSubmitCell** function at the sample level. Therefore, once **endEdit** method is called through the **DataGridController**, the current cell is programmatically ended, and it cannot be cancelled afterwards.

**Comment by abdulrehmananwar** [comment] 2023-06-19 14:35
ok i there any way to check that canSubmitCell is true or false?
 before  DataGridController.endEdit()  within the handleKeyEvent function.

**Comment by Tamilarasan-Paranthaman** [comment] 2024-02-14 12:57
The canSubmitCell method, an override within the DataGridSource class, it triggers each time a cell is submitted from edit mode. In the current DataGrid implementation, it is automatically invoked whenever endEdit is called. You can control whether the cell should commit by returning true or false from canSubmitCell.

In the provided code snippet, calling DataGridController.endEdit when pressing the tab key allows the tab key functionality to proceed (moving to the next cell) only if canSubmitCell returns true. Otherwise, the cell will not be submitted.

Attempting to manually call canSubmitCell before DataGridController.endEdit within the RowSelectionManager.handleKeyEvent method will not be feasible.

**Comment by ashok-kuvaraja** [comment] 2024-03-12 13:18
Hi @abdulrehmananwar,

We hope that the reported issue has been resolved at your end. Therefore, I am closing this ticket. If you need any further assistance, kindly reopen this issue or create a new issue with your requirements. We are always happy to help you.

Regards, 
Ashok K

**Closed by ashok-kuvaraja** 2024-03-12 13:18 UTC
Labels: data_grid, waiting for customer
