### ISSUE TITLE
[syncfusion_flutter_datepicker] Text scale issue

### ISSUE THREAD

**Issue by MagTuxGit** [syncfusion/flutter-widgets#1619] opened 2024-01-09 13:03 UTC
There is some issue with text scale. It happens on iOS only.
I believe it's here:
https://github.com/syncfusion/flutter-widgets/blob/73d2f82496b7541a7955f9d0ab7636de5aa867b9/packages/syncfusion_flutter_datepicker/lib/src/date_picker/date_picker.dart#L5630
In my case didChangeDependencies called few times and every time it scales the text down. In a result I have something like this:
![IMG_9082](https://github.com/syncfusion/flutter-widgets/assets/5296407/660218b9-dfdc-4149-9dd3-0c79bceb7707)

Here is the reproducible example
``` dart
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_datepicker/datepicker.dart';

void main() {
  runApp(const MyHomePage());
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Builder(builder: (context) {
        return Material(
          child: Column(
            children: [
              const TextField(autofocus: true),
              MaterialButton(
                  onPressed: () {
                    showModalBottomSheet(
                        context: context,
                        builder: (context) => SfDateRangePicker());
                  },
                  child: const Text('Show date picker')),
            ],
          ),
        );
      }),
    );
  }
}
```
It's caused by keyboard animation and bottom sheet animation.

Text size settings to reproduce
Settings - Display - Text size
option 4 (middle) - no bug
options 1-3 - text is smaller
options 5-7 - text is bigger

**Comment by MagTuxGit** [comment] 2024-01-09 16:34
23.2.4 works fine
23.2.6+ have the bug

**Comment by RoyGuanyu** [comment] 2024-01-09 18:42
I got the same issue on syncfusion_flutter_calendar

**Comment by true-glassy** [comment] 2024-01-09 19:57
I have the same issue when the keyboard is open the font of the date picker increases significantly.
I have attached a photo of every time I open and close the keyboard on IOS real device.

![IMG_7926](https://github.com/syncfusion/flutter-widgets/assets/116687366/1e37b06a-bdd8-4fe0-9877-b1b1daa2967e)
![IMG_7927](https://github.com/syncfusion/flutter-widgets/assets/116687366/cb08cee4-085e-4ac2-bad1-62fa0cff6d77)
![IMG_7928](https://github.com/syncfusion/flutter-widgets/assets/116687366/1a004b0b-defd-475c-bae5-c2a909cf49cc)
![IMG_7929](https://github.com/syncfusion/flutter-widgets/assets/116687366/7bff04f2-7d0c-4c4c-adf6-054669ab9982)

**Comment by Yuvaraj-Gajaraj** [comment] 2024-01-12 13:51
We have checked the reported issue with the help of a shared code snippet that in iOS devices the calendar text size is scaled small due to device keyboard animation, and is not reproduced at our end. We request you to share the following details which is helpful to know the issue better and provide a solution sooner.

- iOS version and the device type used to reproduce the issue.
- Flutter SDK version and Xcode version used.
- syncfusion_flutter_datepicker version used in your sample.

Screen record:
![ScreenRecording2024-01-12at7 18 06PM-ezgif com-video-to-gif-converter](https://github.com/syncfusion/flutter-widgets/assets/61863686/2d4ce266-071e-4352-a720-d6473c615366)

**Comment by MagTuxGit** [comment] 2024-01-12 18:42
iPhone XR, iOS 17.1.2
iPhone 8, iOS 17.x (don't remember)
iPhone 12, iOS 17.x

Flutter 3.16.5

syncfusion_flutter_datepicker 23.2.6+

But maybe those are not important, cause I discovered one important thing.
Settings - Display - Text size
option 4 (middle) - no bug
options 1-3 - text is smaller
options 5-7 - text is bigger

**Comment by jalchr** [comment] 2024-01-15 09:30
With version: 24.1.45
I'm experiencing same issue as @true-glassy

**Comment by dlwpdud12** [comment] 2024-01-22 03:11
same issue here. usually can work, but only one have this issue 2

**Comment by patthipati** [comment] 2024-02-04 05:07
I also have the same issue when the widget rebuild   font of the date picker increases significantly increasing

**Comment by MagTuxGit** [comment] 2024-02-06 12:31
It's obvious that there is a recursive scaling here if the initial scale is not 1.
https://github.com/syncfusion/flutter-widgets/blob/73d2f82496b7541a7955f9d0ab7636de5aa867b9/packages/syncfusion_flutter_datepicker/lib/src/date_picker/date_picker.dart#L5630

**Comment by Yuvaraj-Gajaraj** [comment] 2024-02-07 13:31
We are able to replicate the reported issue regarding the Text Scaling Issue in DateRangePicker on the iOS Simulator at our end and have logged a bug report for it in our feedback portal. We will fix and include the changes in our Volume 1 main release which is expected to be rolled out on March 3rd week. We will update you here once the release is rolled out and we appreciate your patience until then

**Comment by Yuvaraj-Gajaraj** [comment] 2024-03-15 12:29
The reported issue regarding the **Text Scaling Issue in DateRangePicker on the iOS Simulator** has been fixed and rolled out in our Volume 1 2024 main release. To avoid this please upgrade your package to the latest version mentioned below.

Latest package: https://pub.dev/packages/syncfusion_flutter_datepicker/versions/25.1.35

**Comment by RoyGuanyu** [comment] 2024-03-17 06:06
Thanks for the efforts.
Is this issue also solved in Syncfusion Calendar? Thanks

**Comment by Yuvaraj-Gajaraj** [comment] 2024-03-22 09:41
Hi @RoyGuanyu ,

Yes, the Text scaling issue is also resolved in the SfCalendar control and rolled out in our Volume 1 2024 main release. To avoid this please upgrade your package to the latest version mentioned below.

Latest package: https://pub.dev/packages/syncfusion_flutter_calendar/versions/25.1.35

Regards,
Yuvaraj.

**Closed** 2024-04-23 04:51 UTC
Labels: bug, date_picker, fixed
