### ISSUE TITLE
Flutter Syncfusion DataGrid some time Flicker when sroll bar start 

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#1224] opened 2023-05-30 10:32 UTC
it happed only some time not sure why this is happening

https://github.com/syncfusion/flutter-widgets/assets/62530396/3e797903-72f1-4d2f-9aeb-02014d527f2e

**Comment by Tamilarasan-Paranthaman** [comment] 2023-05-31 14:32
Hi @abdulrehmananwar,

Based on the information provided, we have been unable to reproduce the reported issue on our end. We suspect that this may be a sample-specific issue. In order to investigate the issue further, we kindly request that you provide us with a simple sample that replicates the problem. Alternatively, if you could modify the attached sample to make the issue reproducible, along with any other relevant details pertaining to this issue, it would greatly assist us in identifying the problem and offering an appropriate solution.

https://github.com/syncfusion/flutter-widgets/assets/93904422/575eb7da-1f56-4f96-a189-d2852e59276a

**Sample Link: [DataGrid-Simple-Sample](https://github.com/syncfusion/flutter-widgets/files/11614932/sample.zip)**


By providing a reproducible simple sample and additional information, we can thoroughly investigate the issue and provide you with a more accurate resolution.

Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment] 2024-02-08 04:44
Hi @abdulrehmananwar,

We suspect that the reported problem has been resolved at your end. We are closing this issue. Please let us know if you have any further queries on this. We are happy to help you.

Regards, 
Ashok K

**Closed by ashok-kuvaraja** 2024-02-08 04:44 UTC
Labels: data_grid
