### ISSUE TITLE
Multiple issues using the PDFViewer with scrolling, performance, slowness - not ready yet for production

### ISSUE THREAD

**Issue by alexda8999** [syncfusion/flutter-widgets#632] opened 2022-03-15 19:01 UTC
I have installed the latest version of the plugin syncfusion_flutter_pdfviewer: 19.4.56-beta. 

I am using Flutter 2.10.3. I am currently reviewing the possibility of using this plugin to render PDF's for iOS/Android. 

During my tests - I have found a number of issues that are potential showstoppers:- 

1) The Performance of the viewer is extremely bad, especially under iOS. Specifically scrolling a PDF with or without images is very slow. There is no fling gesture allowing you to quickly swipe up or down and jump multiple pages in quick succession. The best I can achieve is 1-2 pages. 

Additionally, when you hold down on a page and try and scroll - all PAGES immediately **GO BLANK** - after a few seconds, the pages are then painted with the contents. In my tests, the longest I had to wait before the PDF page showed contents was 4 seconds! Why does the page go blank and more importantly why does it take so long to restore the data when you use a **finger gesture** to scroll a pdf ?

2) When I use the page number widget that is positioned to the right of my report and if I use that to scroll - the pages appear to redraw much faster than if I use my finger on the pdf page (There is still a delay but its not as bad as just using your finger on the pdf page)

3) The page number widget when positioned to the right of the page sometimes misses a finger gesture and then I am scrolling the page rather than scrolling through pages in my report. This can easily be replicated by first holding the number widget and moving it to the bottom and then the top - then release your finger and then hold it again to move to the bottom. **You will notice that the page widget doesnt move but the underlying page does**

4) My app's memory increases in size dramatically when I scroll a report - up and down constantly. The report can be anywhere from 10 pages to 100 pages, with or without images. **The more I scroll up and down - the more memory resources are used and then scrolling becomes painfully slow and the app is unusable**

5) When the page number widget is docked to the bottom of the screen - on (say) an iOS device when one tries to scrolling horizontally the pages in the report , the device captures the gesture - even if you wrap in a SafeArea, the gesture is still too close to the bottom of the screen and the native iOS gesture kicks in.

6) When you have horizontal scrolling - when you **HOLD** your finger on the page number widget and scroll the report (BUT DONT LET GO) - when you **stop scrolling** The Page you are currently at is **BLANK**. If you let go of the Page Number widget - the page then gets created and you can see the content.

7) I have experienced CRASHING when scrolling very large reports (100-150 pages) - Is the pdfViewer limited to therefore displaying < 100 pages ? Is this a restriction? Looking at the changelog  the crashing was supposed to be fixed in 19.4.55 

Kindly therefore advise what the current roadmap is for the PDFViewer and whether there are any immediate plans to fix the severe performance issues and sluggish behaviour as mentioned above.

**Comment by ahmadzakariamediaplus** [comment] 2022-03-16 08:36
i am facing the same issues as described by @alexda8999.

**Comment by ssbaval** [comment] 2022-03-16 14:38
I have most of the issues also specified by @alexda8999 - we have a high profile app and the issues with the PdfViewer prevent us from releasing it. 

When will the issues be fixed and a the plugin moved out of Beta?

**Comment by dillibabu1802** [comment] 2022-03-16 17:23
Hi @ssbaval/ @ahmadzakariamediaplus / @alexda8999 

SfPdfViewer widget highly depends on InteractiveViewer for Scrolling, zooming and panning. Currently, flutter have few performance issues in InteractiveViewer as below.

[https://github.com/flutter/flutter/issues/86531](https://github.com/flutter/flutter/issues/86531)
[https://github.com/flutter/flutter/issues/78543](https://github.com/flutter/flutter/issues/78543)

The filing gesture behavior is similar to the InteractiveViewer. To achieve bi-directional scrolling in a flutter, we have only the InteractiveViewer widget. 

Instant loading of PDF page disturbs the scrolling. Since Flutter is single-threaded, image generated in native platform and loaded to image widget in flutter. We tried the isolate.spawn for this process, we couldn't achieve the desired output. To improve the loading speed, we have loaded one page at a time and to avoid pixelation in zoom, we have rendered the image with high resolution based on zoom value. We have already logged a Feature request for this - [https://www.syncfusion.com/feedback/31524/active-viewport-rendering](https://www.syncfusion.com/feedback/31524/active-viewport-rendering)

Regards,
Dilli babu.

**Comment by ssbaval** [comment] 2022-03-16 18:59
@dillibabu1802 - I'm sorry but it sounds like you are trying to deflect the issues with the Syncfusion PDFViewer onto Flutter's Interactive Viewer - Not all of the scrolling issues that are inherent within the PdfViewer are caused by the InteractiveViewer - Have you actually investigated the issues mentioned in this thread, especially the detailed information supplied by @alexda8999  ?

Yes I agree that there are issues with Interactive Viewer but the issues regarding scrolling (poor performance) etc was much better in version 19.3.48-beta compared to what we have now. Additionally, 19.4.50 was okay but there were painful iOS crashes caused by this plugin in that version and this was only fixed in 19.4.56-beta (There are still issues of crashing but it is not as bad in this version). Really bad scrolling performance issues is definitely noticeable in 19.4.55. It's strange since you are saying that the issues of poor scrolling is to do with Flutter's interactive viewer - so why don't we see the issues in Android? They are more apparent in iOS. 

Syncfusion ships some great components but unfortunately - Syncfusion has a history of always adding more regression bugs whenever a new release is made. Things that used to work in one version no longer work in the next or if they do work, they suffer from severe performance issues.

What about BLANK PAGES after one stops scrolling ? I experience this exact bug - sometimes it can take upto 5 seconds before a page is rendered - are you saying this is also down to Flutter's Interactive Viewer ???

**Comment by dillibabu1802** [comment] 2022-03-17 14:23
Hi @ssbaval 

_I'm sorry but it sounds like you are trying to deflect the issues with the Syncfusion PDFViewer onto Flutter's Interactive Viewer - Not all of the scrolling issues that are inherent within the PdfViewer are caused by the InteractiveViewer - Have you actually investigated the issues mentioned in this thread, especially the detailed information supplied by @alexda8999 ?

Yes I agree that there are issues with Interactive Viewer but the issues regarding scrolling (poor performance) etc was much better in version 19.3.48-beta compared to what we have now. Additionally, 19.4.50 was okay but there were painful iOS crashes caused by this plugin in that version and this was only fixed in 19.4.56-beta (There are still issues of crashing but it is not as bad in this version). Really bad scrolling performance issues is definitely noticeable in 19.4.55. It's strange since you are saying that the issues of poor scrolling is to do with Flutter's interactive viewer - so why don't we see the issues in Android? They are more apparent in iOS._ - We deeply regret for the inconveniences.  We can reproduce the reported issue with simple sample with InteractiveViewer with scrollable image which loads on demand(future). If all images are loaded while initializes SfPdfViewer instead of virtual loading then the reported scrolling issues doesn't happens but the loading time takes more than 10 seconds.  Moreover, we haven't done any specific implementation for iOS. We have major rendering logics in flutter dart which works in Android, iOS, web and macOS. So, there is no platform specific scrolling implementation.  Source available here - [https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_pdfviewer](https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_pdfviewer).

_Syncfusion ships some great components but unfortunately - Syncfusion has a history of always adding more regression bugs whenever a new release is made. Things that used to work in one version no longer work in the next or if they do work, they suffer from severe performance issues._ Sorry for the inconvenience and we are improving the regression testing in every release and we are working for the betterment and it will be reflected in futures releases.

_What about BLANK PAGES after one stops scrolling ? I experience this exact bug - sometimes it can take upto 5 seconds before a page is rendered - are you saying this is also down to Flutter's Interactive Viewer ???_ We have used the [UIGraphicsImageRenderer](https://developer.apple.com/documentation/uikit/uigraphicsimagerenderer) to render the image. The time taken for image rendering depends zooming percentage of document as we have worked on preserving quality of the document when it is zoomed. We are still checking the possibility to improve the image rendering and scrolling part in iOS devices and will be update you the further details on 23 March 2022.

Regards,
Dillli babu.

**Comment by ssbaval** [comment] 2022-03-19 12:21
> We have used the [UIGraphicsImageRenderer](https://developer.apple.com/documentation/uikit/uigraphicsimagerenderer) to render the image. The time taken for image rendering depends zooming percentage of document as we have worked on preserving quality of the document when it is zoomed.

We do not have any additional Zooming set on our reports and so the SfPdfViewer will take the default zoom - even with the default zoom, there is a noticeable and painful delay when scrolling a report - and again, the delay is more prevalent when one uses a finger gesture on a report as opposed to using the PAGE NUMBER widget.

**Comment by deepika134** [comment] 2022-03-21 11:36
Hi @ssbaval,

We are checking on the reported query and will update the further details on 23 March 2022.

Regards,
Deepika Ravi

**Comment by dillibabu1802** [comment] 2022-03-23 17:45
Hi @ssbaval 

On further analyzing, we found that scroll freezing issue due to image rendering in main thread of flutter can be resolved in iOS platform. We are analyzing on multi threading in iOS image rendering. We will update the further details on 25 March 2022.

Regards,
Dilli babu

**Comment by dillibabu1802** [comment] 2022-03-25 13:25
Hi @ssbaval 

We have planned to improve the image rendering in Flutter PdfViewer iOS. The implementation will be available in April 2nd weekly package release which is estimated to be available by April 12 2022 tentatively.

Regards,
Dilli babu.

**Comment by ssbaval** [comment] 2022-04-06 16:06
@dillibabu1802 Can you advise if the improved image rendering that you mention here :

 [dillibabu1802](https://github.com/dillibabu1802) commented [12 days ago](https://github.com/syncfusion/flutter-widgets/issues/632#issuecomment-1079025588)

Has been implemented in : 

`syncfusion_flutter_pdfviewer: ^20.1.47-beta`

If so, I have just installed this latest version and the performance is much much worse than 19.4.52.

If you recall, there are two major issues with performance with the PdfViewer : 

1- Trying to scroll a page (But placing your finger on a page and scrolling either up or down)
2- Using the page number widget (Either vertical/horizontal scrolling)

The issues with both of the techniques above are now : 

**1- Trying to scroll a page (But placing your finger on a page and scrolling either up or down)**
We still have very bad performance when compared with (2). Pages are BLANK for literally a few seconds when we scroll before we actually see any content. You can easily see this yourself by first dragging the **page number widget  all the way to the bottom and then to the top and then now just try and scroll the current page using your finger (downwards) ... The further you scroll down , the longer it takes to show content!!

**2- Using the page number widget (Either vertical/horizontal scrolling)**
Using this approach to scroll is marginally faster now with version 20.1.47-beta than with 19.4.56-beta. 

However, this version now has regressed in terms of loosing touch gesture on the page number widget. By this I mean that when you try and quickly hold onto the page number widget and scroll either up or down , the gesture is lost and is then transferred to the page!! We used to have this previously but now it is much much worse and more apparent.

I have also tried to run the Flutter UI Widgets app on iOS and in particular the PdfViewer and it takes like 5 seconds to show content when you scroll and scrolling is extremely poor. 

Its been a while now since the performance improvements to the PdfViewer were promised and unfortunately the current version has regressed so badly now - it renders it not really usable in production apps. Is there a roadmap for the PDFViewer so that users can see whether its worth waiting for it to improve or whether we should see alternative native viewers.

**Comment by dillibabu1802** [comment] 2022-04-07 14:38
Hi @ssbaval 

We regret the inconvenience.

As mentioned on 25 March 2022, the reported issues will be fixed and included in April 2nd weekly release which is estimated to be available by 12 April 2022.

**Regarding the issue in Flutter UI Widgets app in iOS app store:**
Due to a technical glitch, we are yet to upgrade the latest version of the app store application and the latest Syncfusion package in it. This is will be resolved in a couple of days and you can confirm it by checking the "Version history" tag in App Store.

**Regarding Scrolling improvements:**
Yes, we have planned to improve the scrolling performance improvements in the upcoming main release 2022 Volume 2 and we will continuously improvement in our every weekly release (every Tuesday). So, we appreciate your patience until then and we improve our regression to provide a stable implementation.

Regards,
Dilli babu.

**Comment by sallypeters** [comment] 2022-04-08 11:49
@dillibabu1802 

I am using the version listed below which states **improved scrolling & performance**


[](https://pub.dev/packages/syncfusion_flutter_pdfviewer/changelog#20147-beta---04042022)[20.1.47-beta] - 
```
04/04/2022 
The Windows platform support has been provided.
Improved scrolling and panning performance in the zoomed document.
```

I am finding **significant issues with the latest version of this plugin**

Does the current plugin already contain the improvements mentioned for release on 12th April ?

I am not finding the same major issues with scrolling a document in Android compared with iOS - if there is no Platform-specific code to handle this - can you explain why we are seeing terrible performance in iOS when using this plugin? Furthermore - in our app, we use **InteractiveViewer** to render and enrich very large PNG's and do not have any performance issues whatsoever.

Lastly - we have also used these plugins (Although not as feature rich as Syncfusion PdfViewer) and we can confirm that they do not suffer from the poor performance that **Syncfusion PdfViewer** has.

https://pub.dev/packages/pdf_viewer_plugin
https://pub.dev/packages/advance_pdf_viewer
https://pub.dev/packages/flutter_pdfview

Lastly - This plugin has been in Beta for almost 2 years -  when can we expect a more stable performant plugin ?

**Comment by dillibabu1802** [comment] 2022-04-12 14:43
Hi @sallypeters / @ssbaval 

We have improved the scrolling freeze issue in iOS and included the fix in [latest version](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/20.1.48-beta.1). We are still working on the scrolling improvements in upcoming releases and all the issues will be resolved by 2022 Volume 2. Kindly check the latest version of Flutter PdfViewer and let us know if you face any issues.

Regards,
Dilli babu.

**Comment by sallypeters** [comment] 2022-04-13 17:38
@dillibabu1802 

I have accessed again what I believe to be the latest version of this plugin : 

![image](https://user-images.githubusercontent.com/65397428/163237672-20b04058-7d94-4afe-8f94-eb63855866c9.png)

Its hard to ascertain whether I indeed have the latest version since if you refer to the screenshot above, it doesnt appear to have updated the **changelog.**

Nevertheless, I have updated to this new version and the performance with regards to the scrolling, blank pages and everything else that has been pointed out by myself and other users from this entire thread still remain. I cannot see any noticeable improvement in the latest release which is very very worrying.

You mention in your last post : 
`
We are still working on the scrolling improvements in upcoming releases and all the issues will be resolved by 2022 Volume 2`

That all issues regarding scrolling will be resolved in 2022 vol 2. Kindly advise when we are to expect this version so that we can at least decide if we should abandon the syncfusion pdf viewer for something more performant.

**Comment by therealjohnsummer** [comment] 2022-04-14 11:16
@dillibabu1802 I am using 20.1.48-beta.1 - I have a very small PDF report, no more than 8 pages. When I scroll there is blank/empty spaces and then after a few seconds - I see my data. You mention here : 

`As mentioned on 25 March 2022, the reported issues will be fixed and included in April 2nd weekly release which is estimated to be available by 12 April 2022.`

That this will be fixed but it is not - I'd appreciate if you can commit to advising when these issues will be **COMPLETELY fixed** as each time you keep on saying that it gets fixed in release xxx and then we find out that the release is either worse than the previous one or that there are further issues/regression bugs.

The release 20.1.48-beta.1 has now made scrolling so bad its not worth using thus plugin. Your **Virtual Scrolling** causes more issues then what it solves because there is such a delay when the actual page is rendered - it would have been better to not include virtual scrolling since the current experience outweighs the benefits.

Another huge disappointment with this new release is that when you use either vertical or horizontal scrolling and you drag the page number icon either vertical or horizontal a number of times - focus then loses from the control and then gets put on the page. This has been mentioned a number of times and yet this is still not fixed and no response has been made regarding this - we take the time to fill out these github issues, does syncfusion actually read what we put here ?

Lastly - if we upgrade our license to an enterprise license will this give us priority in getting this fixed?

**Comment by dillibabu1802** [comment] 2022-04-19 13:44
Hi @ssbaval,

We regret the inconvenience.

We are improving the scroll performance in iOS gradually. We are deeply worried that the issue still persists at your end. It would be greatly helpful if you could share the video illustration of issues you are facing at your end along with input documents if any. We will ensure the fix for your documents and scenarios before every release of the package. We will update the changelog properly from the next release onwards. Obviously, we have a roadmap to improve scrolling in our upcoming release 2022 Volume 2022.

Regards,
Dilli babu.

**Comment by dillibabu1802** [comment] 2022-04-19 13:58
Hi @therealjohnsummer 

We deeply regret the inconvenience. 

Kindly share us the following details.
1. Issue reproducing document.
2. Video illustration of your scenarios.
3. Platforms in which issues are reproduced.

These information will be helpful for us the add your cases in our regression and provide you a stable package.

**Regarding Virtual Scrolling:**
Virtual scrolling was the most requested feature in PdfViewer since the PDF pages will be loaded on demand which reduces the app runtime memory and it will be highly helpful when customer loads a more than 100+ page document. Kindly share us the video illustration of your issue in virtual scrolling along with expected time to load the pages. We will resolve the issue as per your requirement.

**Regarding ScrollHead issue:**
We are sorry to hear that the scroll head issues are yet to resolve. We are unable to reproduce the reported issue at our end. We have checked all the possible scenarios. Kindly share us the video illustration with your hand movements which will be helpful for us to provide a prompt solution. 

Regards,
Dilli babu.

**Comment by rodrigorafaeldamaceno** [comment] 2022-05-03 20:13
App keeps crashing on iOS when scrolling, any solution for this?

**Comment by deepika134** [comment] 2023-04-24 04:24
Hi @rodrigorafaeldamaceno ,

We tried to reproduce the reported issue with provided details, but the scrolling is works properly on our end. For your reference, we have prepared the sample and it can be downloaded from the attachment. If you still reproduce the reported issue in your use case, then kindly share the modified issue reproducing in sample and also, please share the following details, to reproduce the reported issue on our end.

•	Platforms in which the issue is reproduced (Android, iOS, Web, macOS).
•	Device Specification.
•	Flutter Doctor log.
•	syncfusion_flutter_pdfviewer package version.
•	Flutter SDK version.
•	Issue reproducing steps/video.

This information will be helpful for us to provide you a prompt solution at the earliest.
[sample_632.zip](https://github.com/syncfusion/flutter-widgets/files/11306521/sample_632.zip)

**Comment by ramkumarsync** [comment] 2024-02-07 10:57
We are closing this issue since we don't have enough information to reproduce it. You can reopen this anytime and share the requested details to proceed further.

**Closed by ramkumarsync** 2024-02-07 10:57 UTC
Labels: pdf_viewer
