### ISSUE TITLE
Search engine not working on Arabic pdf

### ISSUE THREAD

**Issue by Islam-galal** [syncfusion/flutter-widgets#1687] opened 2024-02-23 04:17 UTC
Dears search option is working on English pdf only , is there any way to make it works on other language like Arabic ?

**Comment by immankumarsync** [comment] 2024-02-27 11:26
@Islam-galal, we checked the search functionality in the PDF attached below, and the text search is working as expected in that document. Can you confirm whether you are facing issues with the same document as the one we checked? If you are facing the same issue in the same document as ours, can you share the search query in which you have faced the issue?
[rtl_document.pdf](https://github.com/syncfusion/flutter-widgets/files/14418669/rtl_document.pdf)

If you are facing the issue in a different document, kindly share the PDF document for analysis of the issue and help with a prompt solution.

If you feel the document should not be shared publicly here, you can create a ticket in our [support portal](https://support.syncfusion.com/) and share the details there. We will check and revert soon.

**Comment by ramkumarsync** [comment] 2024-03-14 06:46
Could you please share the requested details to make further progress on this and help you with a prompt solution at the earliest?

**Comment by Hammadbinnaeem** [comment] 2024-04-02 11:39
I am facing the same issue when try to search a pdf which is in german language
the link of the document
https://www.eaquals.org/wp-content/uploads/German-samples-Goethe-Institute.pdf

**Comment by immankumarsync** [comment] 2024-04-03 05:46
Hi @Hammadbinnaeem,
We tried to replicate the issue that the text search is not working on German language PDF documents. But it is working fine as expected. Please find the sample that we used to replicate the issue and the screen recording from the link below.
https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample-26514553

If you are using an older version of the syncfusion_flutter_pdfviewer package, please update and check if the issue is resolved. If the issue still occurs, please let us know the _search query / string_ in which the issue occurs.

**Comment by Deepak1799** [comment] 2024-07-29 19:14
We are closing this issue since we do not have enough information to proceed further. You can reopen this anytime and share the requested details to proceed further.

**Closed by Deepak1799** 2024-07-29 19:14 UTC
Labels: pdf viewer, waiting for customer response
