### ISSUE TITLE
[syncfusion_flutter_pdfviewer] First found Text Search Instance is not visible on screen when searchText method is used in onDocumentLoaded callback

### ISSUE THREAD

**Issue by sagarkardani** [syncfusion/flutter-widgets#467] opened 2021-12-02 05:41 UTC
When previousInstance() or nextInstance() methods are called, respected search instance is highlighted but the highlighted instance is sometimes not coming on the visible part of screen.

**Comment by dillibabu1802** [comment] 2021-12-03 08:37
Hi @sagarkardani 

Thank you for contacting Syncfusion support.

We tried to reproduce the reported issue but the text search navigation was working properly. You can also check the functionalities in [mobile](https://play.google.com/store/apps/details?id=com.syncfusion.flutter.examples) and [web](https://flutter.syncfusion.com/#/pdf-viewer/custom-toolbar) demos. We also suspect that issue might be document-specific since text bounds are retrieved from PDF document and navigation is performed based on it. Kindly share us the following details to provide a prompt solution at the earliest.

1. Issue reproducing document.
2. Sample code snippets.
3. Working platforms.
4. flutter doctor log.

Regards,
Dilli babu.

**Comment by sagarkardani** [comment] 2021-12-03 14:13
Hi @dillibabu1802

Thanks for reply.

I just dig into the issue and found that if `pdfViewerController.searchText('Heading 2')` used in `onDocumentLoaded` callback then the controller is not jumping properly to the first found instance. This is more reproducible when first found instance is not visible on very first loaded screen or when document is loaded with higher `initialZoomLevel`. This should be reproducible on any document.

Document - [dummy.pdf](https://github.com/syncfusion/flutter-widgets/files/7650131/dummy.pdf)
<details><summary>Code</summary>
<p>

```dart
void main() {
  runApp(MyDemoApp());
} 

class MyDemoApp extends StatefulWidget {
  const MyDemoApp({ Key? key }) : super(key: key);

  @override
  _MyDemoAppState createState() => _MyDemoAppState();
}

class _MyDemoAppState extends State<MyDemoApp> {
  late PdfViewerController _pdfViewerController;
  late PdfTextSearchResult _searchResult;

  @override
  void initState() {
    _pdfViewerController = PdfViewerController();
    _searchResult = PdfTextSearchResult();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'My Demo App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('My Demo App'),
          actions: <Widget>[
            IconButton(
              icon: Icon(
                Icons.search,
                color: Colors.white,
              ),
              onPressed: () async {
                _searchResult = await _pdfViewerController.searchText('the', searchOption: TextSearchOption.caseSensitive);
                print('${_searchResult.totalInstanceCount} instances found');
                setState(() {});
              },
            ),          
            Visibility(
              visible: _searchResult.hasResult,
              child: IconButton(
                icon: Icon(
                  Icons.keyboard_arrow_up,
                  color: Colors.white,
                ),
                onPressed: () {
                    _searchResult.previousInstance();
                },
              ),
            ),
            Visibility(
              visible: _searchResult.hasResult,
              child: IconButton(
                icon: Icon(
                  Icons.keyboard_arrow_down,
                  color: Colors.white,
                ),
                onPressed: () {
                  _searchResult.nextInstance();
                },
              ),
            ),
          ],
        ),
        body: SfPdfViewer.file/network(
          //filePath or network Path here,
          controller:_pdfViewerController,
          //initialZoomLevel: 2.0,
          onDocumentLoaded: (details) async {
            _searchResult = await _pdfViewerController.searchText('Point 2/Point 3/Point 4', searchOption: TextSearchOption.caseSensitive);
            print('${_searchResult.totalInstanceCount} instances found');
            setState(() {});
          },
        ),
      ),
    );
  }
}
```
</details>

Platform : Android API 27

syncfusion_flutter_pdfviewer: latest

Regards,
Sagar

**Comment by deepika134** [comment] 2021-12-07 02:31
Hi @sagarkardani,

We are analyzing the reported issue and we will update the further details on December 9, 2021.

Regards,
Deepika Ravi.

**Comment by deepika134** [comment] 2021-12-17 04:24
Hi Sagarkardani, 

We have confirmed that the reported issue “First found Text Search Instance is not visible on the screen when searchText method is used in onDocumentLoaded callback” is a defect. The issue fix will be included in our upcoming weekly release, which is estimated to be available on December 28, 2021. 
 
Regards,  
Deepika Ravi

**Comment by deepika134** [comment] 2021-12-28 15:36
Hi Sagarkardani,  
 
We have included the fix for this issue "PDF document is not loading from the page of the first occurrence when searchText is performed in the onDocumentLoaded callback" in our latest weekly NuGet release, so kindly upgrade to the latest version v19.4.40 to get the issue resolved. 
   
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.4.40-beta  

Regards,  
Deepika Ravi

**Closed** 2022-01-10 06:35 UTC
