### ISSUE TITLE
error G7AD6136F: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null

### ISSUE THREAD

**Issue by nios2** [syncfusion/flutter-widgets#856] opened 2022-08-18 19:31 UTC
I just imported a desktop application to vscode just to get such a error. I'm using flutter 2.10.0 on my project. 
![wuh!!](https://user-images.githubusercontent.com/76213966/185478714-00fdff97-7c3c-4e67-9ffd-b7cbaf421cf0.jpg)

**Comment by Indumathi1195R** [comment] 2022-08-19 06:15
Hi,

Based on the information provided we have checked the mentioned issue "**Errors related to operand of null aware operation**". When migrating to Flutter 3, See the warning like Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null. These warnings are caused by the instance property on bindings is now non-nullable. So, no need to specify the null-aware operators such as (! and ?). Kindly, migrate SfCalendar(above 20.1.56) and Flutter (3.0.0) to latest version resolving this error.

Kindly find the release notes for the same by referring to the following link,

https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#if-you-see-warnings-about-bindings 

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Comment by nios2** [comment] 2022-08-23 21:14
no more errors, problem fixed!

**Closed** 2022-08-23 21:14 UTC
