### ISSUE TITLE
[syncfusion_flutter_datagrid] Error RangeError (index): Index out of range: no indices are valid: 0

### ISSUE THREAD

**Issue by NgoTruongThanh** [syncfusion/flutter-widgets#1856] opened 2024-05-10 07:31 UTC
### Bug description

When my search list is empty 

GridTable will error by  columnWidthMode.fitByCellValue

I can fix it by change columnWidthMode or set width. But i think the lib should fix it 

### Steps to reproduce

...

### Code sample

columnWidthMode: ColumnWidthMode.fill,

### Screenshots or Video

![image](https://github.com/syncfusion/flutter-widgets/assets/128819206/df3974c4-72c3-4028-8aaa-8b3a0a76785d)>

### Stack Traces

[Add the Stack Traces here]

### On which target platforms have you observed this bug?

Web

### Flutter Doctor output

```
C:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.22631.3527], locale en-US)
    • Flutter version 3.19.5 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 300451adae (6 weeks ago), 2024-03-27 21:54:07 -0500
    • Engine revision e76c956498
    • Dart version 3.3.3
    • DevTools version 2.31.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.6)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34221.43
    ! Unable to locate a Windows 10 SDK. If building fails, install the Windows 10 SDK in Visual Studio.

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.89.1)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.88.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3527]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 124.0.6367.119
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 124.0.2478.80

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
Process finished with exit code 0
```

**Comment by abineshPalanisamy** [comment] 2024-05-13 06:07
Hi @NgoTruongThanh ,
 
Based on the details provided, we are unable to address the reported issue clearly. To further assist you and gain a better understanding of the problem, we kindly request that you provide any additional details, samples, or steps that may help us reproduce the issue. This additional information will enable us to thoroughly address your issue and provide an appropriate solution.
 
Regards,
Abinesh P

**Comment by Trung15010802** [comment] 2024-05-14 07:21
I have the same error when using `ColumnWidthMode.auto` or `ColumnWidthMode.fitByCellValue`. The error apears when list is empty and We resize the grid table

https://github.com/syncfusion/flutter-widgets/assets/90593296/6687fbbe-f5fb-4b4e-a223-ed49f5075a3c

```dart
import 'package:flutter/material.dart';

import 'package:syncfusion_flutter_datagrid/datagrid.dart';

void main() {
  runApp(const MyApp());
}

/// The application that contains datagrid on it.
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Syncfusion DataGrid Demo',
      theme: ThemeData(useMaterial3: false),
      home: const MyHomePage(),
    );
  }
}

/// The home page of the application which hosts the datagrid.
class MyHomePage extends StatefulWidget {
  /// Creates the home page.
  const MyHomePage({super.key});

  @override
  MyHomePageState createState() => MyHomePageState();
}

class MyHomePageState extends State<MyHomePage> {
  List<Employee> employees = <Employee>[];
  late EmployeeDataSource employeeDataSource;

  late Map<String, double> columnWidths = {
    'id': double.nan,
    'name': double.nan,
    'designation': double.nan,
    'salary': double.nan
  };

  @override
  void initState() {
    super.initState();
    employees = getEmployeeData();
    employeeDataSource = EmployeeDataSource(employeeData: employees);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Syncfusion Flutter DataGrid'),
      ),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SearchBar(
            hintText: 'Search ...',
            onChanged: (value) {
              Future.delayed(Duration.zero,(){

                employeeDataSource.clearFilters();
              });
              Future.delayed(Duration.zero, () {
                employeeDataSource.addFilter(
                  'name',
                  FilterCondition(
                    type: FilterType.contains,
                    value: value,
                    filterBehavior: FilterBehavior.stringDataType,
                    filterOperator: FilterOperator.or,
                  ),
                );
              });
            },
          ),
          const SizedBox(
            height: 10,
          ),
          Expanded(
            child: Column(
              children: [
                Expanded(
                  child: SfDataGrid(
                    source: employeeDataSource,
                    headerGridLinesVisibility: GridLinesVisibility.both,
                    gridLinesVisibility: GridLinesVisibility.both,
                    allowColumnsResizing: true,
                    onColumnResizeUpdate: (ColumnResizeUpdateDetails details) {
                      setState(() {
                        columnWidths[details.column.columnName] = details.width;
                      });
                      return true;
                    },
                    columns: <GridColumn>[
                      GridColumn(
                          width: columnWidths['id']!,
                          columnName: 'id',
                          columnWidthMode: ColumnWidthMode.auto,
                          label: Container(
                              padding: const EdgeInsets.all(16.0),
                              alignment: Alignment.center,
                              child: const Text(
                                'ID',
                              ))),
                      GridColumn(
                          columnWidthMode: ColumnWidthMode.auto,

                          width: columnWidths['name']!,
                          columnName: 'name',
                          label: Container(
                              padding: const EdgeInsets.all(8.0),
                              alignment: Alignment.center,
                              child: const Text('Name'))),
                      GridColumn(
                          columnWidthMode: ColumnWidthMode.auto,

                          width: columnWidths['designation']!,
                          columnName: 'designation',
                          label: Container(
                              padding: const EdgeInsets.all(8.0),
                              alignment: Alignment.center,
                              child: const Text(
                                'Designation',
                                overflow: TextOverflow.ellipsis,
                              ))),
                      GridColumn(
                          columnWidthMode: ColumnWidthMode.auto,

                          width: columnWidths['salary']!,
                          columnName: 'salary',
                          label: Container(
                              padding: const EdgeInsets.all(8.0),
                              alignment: Alignment.center,
                              child: const Text('Salary'))),
                    ],
                  ),
                ),
                SfDataPager(pageCount: 2, delegate: employeeDataSource),
              ],
            ),
          ),
        ],
      ),
    );
  }

  List<Employee> getEmployeeData() {
    return [
      Employee(10001, 'James', 'Project Lead', 20000),
      Employee(10002, 'Kathryn', 'Manager', 30000),
      Employee(10003, 'Lara', 'Developer', 15000),
      Employee(10004, 'Michael', 'Designer', 15000),
      Employee(10005, 'Martin', 'Developer', 15000),
      Employee(10006, 'Newberry', 'Developer', 15000),
      Employee(10007, 'Balnc', 'Developer', 15000),
      Employee(10008, 'Perry', 'Developer', 15000),
      Employee(10009, 'Gable', 'Developer', 15000),
      Employee(10010, 'Grimes', 'Developer', 15000),
      // create random data
      Employee(10011, 'James', 'Project Lead', 20000),
      Employee(10012, 'Kathryn', 'Manager', 30000),
      Employee(10013, 'Lara', 'Developer', 15000),
      Employee(10014, 'Michael', 'Designer', 15000),
      Employee(10015, 'Martin', 'Developer', 15000),
      Employee(10016, 'Newberry', 'Developer', 15000),
      Employee(10017, 'Balnc', 'Developer', 15000),
      Employee(10018, 'Perry', 'Developer', 15000),
      Employee(10019, 'Gable', 'Developer', 15000),
      Employee(10020, 'Grimes', 'Developer', 15000),
    ];
  }
}

/// Custom business object class which contains properties to hold the detailed
/// information about the employee which will be rendered in datagrid.
class Employee {
  /// Creates the employee class with required details.
  Employee(this.id, this.name, this.designation, this.salary);

  /// Id of an employee.
  final int id;

  /// Name of an employee.
  final String name;

  /// Designation of an employee.
  final String designation;

  /// Salary of an employee.
  final int salary;
}

/// An object to set the employee collection data source to the datagrid. This
/// is used to map the employee data to the datagrid widget.
class EmployeeDataSource extends DataGridSource {
  /// Creates the employee data source class with required details.
  EmployeeDataSource({required List<Employee> employeeData}) {
    _employeeData = employeeData
        .map<DataGridRow>((e) => DataGridRow(cells: [
              DataGridCell<int>(columnName: 'id', value: e.id),
              DataGridCell<String>(columnName: 'name', value: e.name),
              DataGridCell<String>(
                  columnName: 'designation', value: e.designation),
              DataGridCell<int>(columnName: 'salary', value: e.salary),
            ]))
        .toList();
  }

  List<DataGridRow> _employeeData = [];

  @override
  List<DataGridRow> get rows => _employeeData;

  @override
  DataGridRowAdapter buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((e) {
      return Container(
        alignment: Alignment.center,
        padding: const EdgeInsets.all(8.0),
        child: Text(e.value.toString()),
      );
    }).toList());
  }
}

```

**Comment by abineshPalanisamy** [comment] 2024-05-15 06:34
Hi @Trung15010802 ,
 
We have checked your query at our end, and we are able to replicate that issue at our end. We have considered this as a  bug and logged a bug report regarding this in our feedback portal. We will fix the reported issue and include the changes in our upcoming weekly patch release, which is expected to be rolled out on May 28, 2024. We will let you know once released, and we appreciate your patience until then.
 
Regards,
Abinesh P

**Comment by abineshPalanisamy** [comment] 2024-05-28 11:53
Hi @Trung15010802 ,
 
We are glad to inform you that the reported problem has been resolved on our end. Therefore, kindly update SfDataGrid to the latest version([25.2.6](https://pub.dev/packages/syncfusion_flutter_datagrid)). If you have any further queries, please don't hesitate to reach out. We are more than happy to assist you.
 
Regards,
Abinesh P

**Comment by Trung15010802** [comment] 2024-05-31 04:15
> Hi @Trung15010802 ,
> 
> We are glad to inform you that the reported problem has been resolved on our end. Therefore, kindly update SfDataGrid to the latest version([25.2.6](https://pub.dev/packages/syncfusion_flutter_datagrid)). If you have any further queries, please don't hesitate to reach out. We are more than happy to assist you.
> 
> Regards, Abinesh P

I confirm the issues is gone

**Comment by ashok-kuvaraja** [comment] 2024-05-31 04:43
Hi @Trung15010802,

Thanks for the update. We're closing this issue since the reported issue has been resolved. If you need any further assistance, kindly reopen this issue. We are always happy to help you.

Regards,
Ashok K

**Closed by ashok-kuvaraja** 2024-05-31 04:43 UTC
Labels: bug, data grid, solved
