### ISSUE TITLE
Crash in `ScrollHeadOverlayState._updateScrollHeadPosition`

### ISSUE THREAD

**Issue by tp** [syncfusion/flutter-widgets#2018] opened 2024-08-08 12:20 UTC
### Bug description

In our crash reporting we see a huge number of errors resulting from a `clamp` in `ScrollHeadOverlayState._updateScrollHeadPosition`.

The code in the current `master` is:
https://github.com/syncfusion/flutter-widgets/blob/ee87b7b6a735a9a303d7e7973fa4540d0337b64e/packages/syncfusion_flutter_pdfviewer/lib/src/control/scroll_head_overlay.dart#L802-L803

(In our stack traces it shows a slightly different line number, but the code and its inputs still match the lines above.)

The full exception we get is

```
ArgumentError: Invalid argument(s): 1.0
  File "double.dart", line 235, in double.clamp
  File "scroll_head_overlay.dart", line 710, in ScrollHeadOverlayState._updateScrollHeadPosition
  File "scroll_head_overlay.dart", line 294, in ScrollHeadOverlayState.build.<fn>
  File "binding.dart", line 1392, in SchedulerBinding._invokeFrameCallback
  File "binding.dart", line 1326, in SchedulerBinding.handleDrawFrame
  File "binding.dart", line 1171, in SchedulerBinding._handleDrawFrame
  File "hooks.dart", line 312, in _invoke
  File "platform_dispatcher.dart", line 419, in PlatformDispatcher._drawFrame
  File "hooks.dart", line 283, in _drawFrame
```

Which means that in the line above `scrollHeadMaxExtentX` is less than 1.

While we see this across thousands of installations, I was not able to reproduce this in isolation. Also the code to calculate the inputs seems sensible, and the value should always be > 1, as  `widget.viewportDimension.width` will be much bigger than `_kPdfScrollHeadHeight`.

So my assumption is that sometimes the input `viewportDimension` is wrong / "empty", but again I couldn't see any issue with the value being created in https://github.com/syncfusion/flutter-widgets/blob/ee87b7b6a735a9a303d7e7973fa4540d0337b64e/packages/syncfusion_flutter_pdfviewer/lib/src/pdfviewer.dart#L2985.

### Steps to reproduce

No clear reproduction is available, but thousand of error reports show that this is a real issue in the field.

### Code sample

-

### Screenshots or Video

-

### Stack Traces

ArgumentError: Invalid argument(s): 1.0
  File "double.dart", line 235, in double.clamp
  File "scroll_head_overlay.dart", line 710, in ScrollHeadOverlayState._updateScrollHeadPosition
  File "scroll_head_overlay.dart", line 294, in ScrollHeadOverlayState.build.<fn>
  File "binding.dart", line 1392, in SchedulerBinding._invokeFrameCallback
  File "binding.dart", line 1326, in SchedulerBinding.handleDrawFrame
  File "binding.dart", line 1171, in SchedulerBinding._handleDrawFrame
  File "hooks.dart", line 312, in _invoke
  File "platform_dispatcher.dart", line 419, in PlatformDispatcher._drawFrame
  File "hooks.dart", line 283, in _drawFrame

### On which target platforms have you observed this bug?

Android, iOS

### Flutter Doctor output

```
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-DE)
    • Flutter version 3.22.2 on channel stable at /Users/timm/fvm/versions/3.22.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (9 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/timm/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.92.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (5 available)
    • macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                               • web-javascript • Google Chrome 127.0.6533.90

[✓] Network resources
    • All expected network resources are available.
```

**Comment by immankumarsync** [comment] 2024-08-09 17:38
Hi @tp,
Thank you for sharing the possible cause of the issue. However, we are unable to replicate the issue with the provided stack trace.
Could you please share the replication steps, this would be helpful in resolving the issue effectively?

**Comment by immankumarsync** [comment] 2024-08-25 03:25
@tp, we have resolved the issue based on the stack trace and fix is available in our latest weekly release.
Package link: [syncfusion_flutter_pdfviewer v26.2.10](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/26.2.10)

Kindly let us know whether the issue is resolved on your end.

**Closed as completed** 2024-08-26 12:48 UTC
Labels: pdf viewer, solved
