### ISSUE TITLE
Setting isScrollbarAlwaysShown to true and interacting with horizontal scrollbar in web erases data and makes flutter app inoperable. 

### ISSUE THREAD

**Issue by jturakrbi** [syncfusion/flutter-widgets#439] opened 2021-10-28 15:24 UTC
Steps to reproduce:
1. Run syncfusion datagrid example on web.
2. Extend columns and row cell count to x where x is a sufficient number for the grid width to exceed the size of the screen ( I went a little overkill and used 16). 
3. Set getEmployeeData list size to 6 (enough to where to list doesn't fill the entire screen size vertically).
3. Click and drag the horizontal scroll bar located at the bottom of the grid to the end of the grid. (Scroll with a trackpad to get the horizontal scrollbar to appear, or shrink the browser window size).
4. Data in grid disappears, and the app is no longer interact-able.

I attached a screen recording below 

https://user-images.githubusercontent.com/87328949/139285862-b089658d-7c81-4ca1-a2e4-ea2100fb6bdf.mov

Resulting error in terminal is extremely long but the start of it is this: 
Error: Assertion failed: flutter/packages/flutter/lib/src/widgets/single_child_scroll_view.dart:666:18
transformed == position + -_paintOffset
is not true.

**Comment by Sangeetha-Raju** [comment] 2021-11-01 13:27
Hi Jturakrbi, 
 
Sorry for the inconvenience. 
 
We are facing some difficulties in finding the root cause for this issue. So, we need some more time to analyze this issue at our end. We will check and update you the further details on or before November 3, 2021. 
 
We appreciate your patience until then. 
 
Regards, 
Sangeetha Raju.

**Comment by Sangeetha-Raju** [comment] 2021-11-03 13:39
Hi @jturakrbi, 
 
We have checked your reported issue and considered this as bug. We will include the changes in our upcoming weekly pub release which is scheduled to be rolled out on 16th November 2021.  
  
Please refer to the feedback link below for further follow up, 
  
**Feedback link:**  https://www.syncfusion.com/feedback/30098/the-exception-is-thrown-when-scroll-through-horizontal-thumb-track-in-web-and  
  
We will let you know once it gets rolled out. We appreciate your patience until then. Please let us know if you require any further assistance. 
 
Regards, 
Sangeetha Raju.

**Comment by Sangeetha-Raju** [comment] 2021-11-16 13:36
Hi @jturakrbi, 
 
Sorry for the inconvenience caused. 
 
Due to some technical difficulties in providing the fix for this issue, we did not include the fix for the reported issue within the promised date(16th November 2021). We are currently working with high priority. We will fix the reported issue in upcoming weekly pub release which is scheduled to be rolled out on 23rd November 2021. You can track the status through the shared feedback portal link. 
 
We appreciate your patience until then. 
 
Regards, 
Sangeetha Raju.

**Comment by Sangeetha-Raju** [comment] 2021-11-23 10:42
Hi @jturakrbi,

We have resolved the “The exception is thrown when scroll through horizontal thumb track in web and desktop platforms” issue and included the fix in our weekly pub release. Please update DataGrid package to **19.3.55** version. You can also refer to the following pub link.

**Pub link:** https://pub.dev/packages/syncfusion_flutter_datagrid/versions/19.3.55 

Please let us know if you require any further assistance.

Regards,
Sangeetha Raju.

**Comment by Sangeetha-Raju** [comment] 2021-12-15 09:54
Hi @glaceon2000,

The reported issue has been resolved already. Please update the **datagrid package to 19.3.59** version. You can also refer the following pub link.

**Pub link:** https://pub.dev/packages/syncfusion_flutter_datagrid/versions/19.3.59 

We have prepared a sample for you reference. Please find the sample from the following link.

**Sample link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/datagrid_demo-1508272281 

Please check the above sample and revert us if you still facing the same issue? If yes, please confirm the following details,

1.	Which Flutter channel (Stable, beta or Master) are you using? 
2.	Issue replicating platform.
3.	Emulator or the physical device details.

If we misunderstood anything, please modify the sample based on your requirement. It will be helpful for us to check on it and provide you the solution at the earliest.    

Regards,
Sangeetha Raju.

**Closed** 2022-01-10 06:34 UTC
