### ISSUE TITLE
[syncfusion_flutter_xlsio]  add cellValue as formula.

### ISSUE THREAD

**Issue by Joseph-Nathan** [syncfusion/flutter-widgets#708] opened 2022-05-05 18:26 UTC
i add cell content value : '=Row()'
but it does not work when export it .

**Comment by SivakumarRamya** [comment] 2022-05-06 13:01
Hi Joseph,

Greetings from Syncfusion.

We can reproduce the reported Row formula issue at our end and validate it currently. We will share the validation details in 2 business days, on May 10, 2022.

Regards,
Ramya.

**Comment by SivakumarRamya** [comment] 2022-05-10 12:40
Hi Joseph,

We appreciate your patience.

We have confirmed the issue as **Support for creating Excel document with ROW formula function** and logged a defect report. We will include the fix for this issue in our upcoming weekly NuGet release scheduled for May 24, 2022.

You can track the status of the defect report through the following feedback link.

**Track Status:** [https://www.syncfusion.com/feedback/34777/support-for-creating-excel-document-with-row-formula-function](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syncfusion.com%2Ffeedback%2F34777%2Fsupport-for-creating-excel-document-with-row-formula-function&data=05%7C01%7Cramya.s%40syncfusion.com%7C0792cb2cbe564c015a9208da32818748%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637877829137890832%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8ZUch6iywRx8QkBqV7PHPpF0U%2FdizWsSOvz2xSwaESA%3D&reserved=0)

We will let you know once the new package version is available on nuget.org.

**Disclaimer:** Inclusion of this solution in the weekly release may change due to other factors including but not limited to QA checks and works reprioritization.

Regards,
Ramya.

**Comment by SivakumarRamya** [comment] 2022-05-24 09:54
Hi Joseph,


We appreciate your patience.

We have included the fix to resolve the issue **Support for creating Excel document with ROW formula function** in our weekly NuGet release version **20.1.0.57.** Kindly upgrade your Syncfusion packages to this new **20.1.0.57** version and let us know if the issue is resolved.


Regards,
Ramya

**Closed** 2022-05-25 04:53 UTC
