### ISSUE TITLE
Last sunday of march in month view of calendar repeats the saturday date

### ISSUE THREAD

**Issue by fourman-alex** [syncfusion/flutter-widgets#93] opened 2020-12-17 16:17 UTC
See attached screenshot from the web demo. You can see March 27th repeats twice.
This happens for every march of every year in this view.
_Opened this issue in the example repo as well: https://github.com/syncfusion/flutter-examples/issues/244_
![image](https://user-images.githubusercontent.com/5362998/102510369-3692f100-4090-11eb-9985-dbd362db2ae8.png)

**Comment by Indumathi1195R** [comment] 2020-12-18 10:22
Hi Team,

Based on the provided information, we have checked the mentioned issue “**Calendar repeats the date in March month of SfCalendar**” in Sample browser sample. We are unable to reproduce the issue from our end and it is working fine as expected. We have attached the tested image for the same. Please find the image from the following link.

**Link:**
[Image.zip](https://github.com/syncfusion/flutter-widgets/files/5715082/Image.zip)

If possible, can you please share the below details to reproduce the issue from our end? It would be helpful for us to analyze and provide you a solution at the earliest.

•	Time zone details
•	Issue reproducing scenario or video

Regards,
Indumathi R

**Comment by fourman-alex** [comment] 2020-12-18 11:15
So this appears to be a timezone issue. When I'm on Beirut, Lebanon UTC+2 timezone this issue appears, yet on what seems to be the same Kiev, Ukraine UTC+2 timezone this issue does not appear.

**Comment by Indumathi1195R** [comment] 2020-12-21 12:54
Hi,

We have already found and fixed the mentioned issue “**Calendar repeats the date in March month of SfCalendar with Beirut timezone**”. We will include the issue fix in our upcoming Weekly Nuget release package which is expected to be rolled out by December 29, 2020, and let you know once the release rolled out. We appreciate your patience until then.

Regards,
Indumathi R

**Comment by Indumathi1195R** [comment] 2020-12-30 05:38
Hi,

We have included the mentioned issue fix for “**Calendar repeats the date in March month of SfCalendar with Beirut timezone**” in our latest Weekly NuGet package **version 18.4.32**. Kindly update the Flutter calendar package to this version for resolving this mentioned issue. Please find the latest version from the following link.

**Link:** https://pub.dev/packages/syncfusion_flutter_calendar/versions

We hope that this helps you. Please let us know if you need further assistance.

Regards,
Indumathi R

**Closed** 2021-01-18 04:08 UTC
