### ISSUE TITLE
Problem on rendering pdf

### ISSUE THREAD

**Issue by albertobetta** [syncfusion/flutter-widgets#490] opened 2021-12-16 00:26 UTC
Hi!

I'm trying to view the pdf file available at the url https://piazzole-api.inforge.cloud/api/audit/1/pdf
(you can find it attached)

But when I load the plugin for a moment, the red screen of the error you find below appears.

I don't know how to solve the problem, can you help me?

thank you

Release
syncfusion_flutter_pdfviewer: ^19.3.59-beta

The file downloaded locally
[document (2).pdf](https://github.com/syncfusion/flutter-widgets/files/7723646/document.2.pdf)

Exception
 ======== Exception caught by widgets library =======================================================
The following _CastError was thrown building FutureBuilder<Map<int, List<dynamic>>?>(dirty, dependencies: [MediaQuery], state: _FutureBuilderState<Map<int, List<dynamic>>?>#b6f89):
type '_PdfStream' is not a subtype of type '_PdfArray?' in type cast

The relevant error-causing widget was: 
  SfPdfViewer SfPdfViewer:file:///Users/albertobetta/Lavori/Flutter/piazzole_app/lib/app/pages/login/login_page.dart:145:30
When the exception was thrown, this was the stack: 
#0      PdfPage._getResources (package:syncfusion_flutter_pdf/src/pdf/implementation/pages/pdf_page.dart:546:27)
#1      _PageResourceLoader.getPageResources (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/page_resource_loader.dart:12:38)
#2      PdfTextExtractor._getText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:245:25)
#3      PdfTextExtractor._extractText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:151:14)
#4      PdfTextExtractor.extractText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:67:12)
#5      SfPdfViewerState.build.<anonymous closure>.<anonymous closure> (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:1306:34)
#6      new _GrowableList.generate (dart:core-patch/growable_array.dart:133:28)
#7      SfPdfViewerState.build.<anonymous closure> (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:1270:53)
#8      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:782:55)
#9      StatefulElement.build (package:flutter/src/widgets/framework.dart:4782:27)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4665:15)
#11     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#13     StatefulElement.update (package:flutter/src/widgets/framework.dart:4872:5)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#19     StatelessElement.update (package:flutter/src/widgets/framework.dart:4746:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6202:14)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3412:15)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690:16)
#24     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
#25     Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
#26     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:33)
#27     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#28     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#29     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#30     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#31     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#35     _invoke (dart:ui/hooks.dart:166:10)
#36     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#37     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 3 frames from dart:async)

 
The code 
@override
  Widget build(BuildContext context) {
    return GetBuilder<LoginController>(
      init: initPage(),
      builder: (controller) => Scaffold(
        body: SafeArea(
          child: SfPdfViewer.network( 'https://piazzole-api.inforge.cloud/api/audit/1/pdf',),
        ),
      ),
    );
  }
}

**Comment by deepika134** [comment] 2021-12-16 12:14
Hi Alberto Betta,

Thank you for contacting Syncfusion support.

We have checked the reported issue and found that the issue is from our dependency package. The issue fix will be included in our upcoming weekly release which will be available on 28 December 2021.
You can track the status of the issue in the following link,
https://www.syncfusion.com/feedback/31228/typecasting-issue-while-extracting-text-from-particular-pdf-document.

Regards,
Deepika Ravi

**Comment by deepika134** [comment] 2021-12-28 15:35
Hi Alberto Betta,  
 
We have included the fix for this issue " Typecasting issue while extracting text from particular PDF document" in our latest weekly NuGet release, so kindly upgrade to the latest version v19.4.40 to get the issue resolved. 
   
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.4.40-beta  

Regards,  
Deepika Ravi

**Closed** 2022-02-15 06:47 UTC
