### ISSUE TITLE
[syncfusion_flutter_pdfviewer] seeing extreme slowness to view a PDF, "Skipped 172 frames!  The application may be doing too much work on its main thread."

### ISSUE THREAD

**Issue by insinfo** [syncfusion/flutter-widgets#602] opened 2022-02-23 15:30 UTC
I'm seeing extreme slowness to view a PDF, as well as a crash in the application when I perform a text search in any PDF, I think the search has to be done outside the main thread, using the "isolate groups" of dart 2.15 in addition to some optimization.

https://www.riodasostras.rj.gov.br/wp-content/uploads/2021/01/1277en1.pdf

https://youtu.be/vKhrtwtIGlw

**Comment by deepika134** [comment] 2022-02-25 04:36
Hi Isaque Neves,

We are analyzing on the reported query and will update the further details on March 1, 2022.

Regards,
Deepika Ravi

**Comment by deepika134** [comment] 2022-03-01 15:36
Hi Isaque Neves,

The crash issue is caused by zooming in a document, not by the text search. We have already logged a bug regarding the app closing unexpectedly while zooming and scrolling a PDF. The issue fix will be included in our upcoming weekly release, which is estimated to be available on February 8, 2022. The status of the issue can be tracked using the following link,
https://www.syncfusion.com/feedback/32260/unexpected-closure-of-the-app-when-zooming-and-scrolling-the-pdf-continuously 

Regards,
Deepika Ravi

**Comment by insinfo** [comment] 2022-03-03 20:59
@deepika134
from what I could see, the crash does not occur when zooming, but when I do a text search
Take a test by searching for the word "newspaper" with this PDF on Android for you to see
https://www.riodasostras.rj.gov.br/wp-content/uploads/2021/01/1277en1.pdf

**Comment by deepika134** [comment] 2022-03-06 05:35
Hi Isaque Neves,

We tried to reproduce the reported issue with provided details, but the issue couldn't be reproduced on our end. For your reference, we have prepared a sample (along with the output screen record of the same) and it can be downloaded from the following link,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/Output118593674.zip

If you still reproduce the reported issue in your use case, then kindly share the modified issue reproducing in sample which will be helpful for us to provide a prompt solution at the earliest.

Regards,
Deepika Ravi

**Comment by insinfo** [comment] 2022-03-14 21:28
@deepika134
I created an example project that demonstrates the app crashing when performing a search

https://github.com/insinfo/demonstrate_bug_pdfviewer

https://youtu.be/7VoESIJbxiU
https://youtu.be/V6tpuJC2BdI
https://youtu.be/u2d0th-mrxE

**Comment by deepika134** [comment] 2022-03-15 06:49
Hi Isaque Neves,

When performing a text search, the UI freeze is a known issue of SfPdfViewer. At present we do not have support for "Asynchronous text search". We have used text search methods from the Syncfusion PDF package. Since the requested support is yet to be given in that package, we are unable to do in our widget. As an alternative, we tried to use the [Isolate. spawn](https://api.flutter.dev/flutter/dart-isolate/Isolate/spawn.html) but, the spawn method allows static members and top-level functions to make synchronous methods as asynchronous. We will let you know when this feature is implemented. The status of the feature can be tracked by the following link, 
https://www.syncfusion.com/feedback/21985/asynchronous-text-search 

Regards,
Deepika Ravi

**Comment by insinfo** [comment] 2022-03-22 17:05
@deepika134
I updated the project to compare [syncfusion_flutter_pdfviewer](https://pub.dev/packages/syncfusion_flutter_pdfviewer) with [PdfTron](https://github.com/PDFTron/pdftron-flutter) and [PsPdfkit](https://pub.dev/packages/pspdfkit_flutter/versions/2.0.0) and it seems at the moment that [syncfusion_flutter_pdfviewer] is extremely slower than the others, I hope this is only in the beta version and that the final version will be faster.

https://github.com/insinfo/demonstrate_bug_pdfviewer

**Comment by GMChristo** [comment] 2022-03-22 17:34
I'm having the same problem, when I open a pdf the display stay frozen for a while, and because of this I can't put something like a loading icon to the user known the app still working

**Comment by deepika134** [comment] 2022-03-24 01:30
Hi @insinfo / @GMChristo ,

We regret the inconvenience.

As we mentioned earlier, we will include the support for "Asynchronous text search" in SfPdfViewer in our future releases. We will let you know once the feature is implemented. The status of the feature can be tracked by the following link,
https://www.syncfusion.com/feedback/21985/asynchronous-text-search 

Regards,
Deepika Ravi

**Closed** 2022-04-25 05:20 UTC
