### ISSUE TITLE
[syncfusion_flutter_pdf_viewer] Pdf freezes app and needs to restart the app 

### ISSUE THREAD

**Issue by abhinavsinghring** [syncfusion/flutter-widgets#1639] opened 2024-01-18 18:17 UTC
Hey there,
I have faced some issues using this pdf viewer in my app.
Currently, this is happening with this PDF which I'm attaching here below
[jhva105.pdf](https://github.com/syncfusion/flutter-widgets/files/13980290/jhva105.pdf)

I tested it on multiple devices and it resulted in the same freezing issue while loading the pdf.

I think it crashes at the text extract point as this pdf is in Sanskrit language. But the other PDFs in the same language are opening fine.
Like this 
[jhva104.pdf](https://github.com/syncfusion/flutter-widgets/files/13980310/jhva104.pdf)

I'm attaching here the screenshot of the frozen screen.
![Screenshot_1705601723](https://github.com/syncfusion/flutter-widgets/assets/83336285/3e7ebf66-ca43-48a4-be9a-9f65c9eadf5b)

This is also shown when freezes.
![image](https://github.com/syncfusion/flutter-widgets/assets/83336285/52def62a-129f-4bc0-9998-98a526db9ef5)

I have tried opening this PDF with another PDF viewer and it does open there is something related to this plugin.
My app is likely to go into production in two weeks, many things in this plugin are not ready for production. There are many plugins that render all PDF pages in one go or in an instant but this viewer can't (if they can what's stopping you from this), you say that to prevent excessive ram usage and still uses more ram than those plugins which render fast. Only reason for still using this plugin in my app is because of search and navigation options including scrollhead. I have to show an excuse popup to users.

**Comment by immankumarsync** [comment] 2024-01-19 11:01
Hi @abhinavsinghring, we are able to replicate the reported issue, "Application freezes when extracting text in particular document". Currently, we are validating the issue, and we will provide further update on January 23, 2024.

**Comment by abhinavsinghring** [comment] 2024-01-24 09:41
@immankumarsync  Any update?

**Comment by immankumarsync** [comment] 2024-01-25 12:30
We confirmed the issue ”Extract text is not working properly in specific PDF document” as a defect in our product and fix will be included in our upcoming weekly NuGet release, which will be available on February 6, 2024.

Use the below feedback link to track the status of the reported bug.
[Extract text is not working properly in specific PDF document in Flutter | Feedback Portal (syncfusion.com)](https://www.syncfusion.com/feedback/50277/extract-text-is-not-working-properly-in-specific-pdf-document)

Disclaimer: “Inclusion of this solution in the weekly release may change due to other factors including but not limited to QA checks and works reprioritization.”

**Comment by immankumarsync** [comment] 2024-02-06 04:34
Hi @abhinavsinghring,
The issue “Extract text is not working properly in specific PDF document” has been resolved and the fix is available in our latest weekly release. Please find the package link below.

Package link:  [https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/24.2.4](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/24.2.4)

**Closed** 2024-02-08 08:40 UTC
Labels: pdf_viewer
