### ISSUE TITLE
iOS app crashes when scrolling through pdf

### ISSUE THREAD

**Issue by flutternoob** [syncfusion/flutter-widgets#525] opened 2022-01-08 17:21 UTC
Hi, I am using the ```syncfusion_flutter_pdf_viewer``` library for a Flutter app. The library works fine on an Android device. However, on an iOS device, the app crashes (the app closes unexpectedly) when scrolling through the PDF. This holds good for all PDFs. I have attached a minimum reproducible project as a zip file. Thanks.

[ios_pdf_bug.zip](https://github.com/syncfusion/flutter-widgets/files/7833661/ios_pdf_bug.zip)

**Comment by dillibabu1802** [comment] 2022-01-11 12:27
Hi @flutternoob ,

Thank you for contacting Syncfusion support.

We are analyzing on the reported issue from our end and will update the further details on 13 January 2022.

Regards,
Dilli babu.

**Comment by flutternoob** [comment] 2022-01-24 15:09
There seems to be a memory issue. To reproduce the bug, scroll back and forth through the PDF rapidly on an iOS device. I could not get a video screen capture. The error log shown here is from the production app that I built, not the minimum reproducible project. Here is the exception:

```
The app “Runner”  quit unexpectedly.

Domain: IDEDebugSessionErrorDomain

Code: 10

Failure Reason: Message from debugger: Terminated due to memory issue

User Info: {

    DVTErrorCreationDateKey = "2022-01-24 07:43:30 +0000";

    IDERunOperationFailingWorker = DBGLLDBLauncher;

}

--



Analytics Event: com.apple.dt.IDERunOperationWorkerFinished : {

    "device_model" = "iPhone10,3";

    "device_osBuild" = "15.1 (19B74)";

    "device_platform" = "com.apple.platform.iphoneos";

    "launchSession_schemeCommand" = Run;

    "launchSession_state" = 2;

    "launchSession_targetArch" = arm64;

    "operation_duration_ms" = 524306;

    "operation_errorCode" = 10;

    "operation_errorDomain" = IDEDebugSessionErrorDomain;

    "operation_errorWorker" = DBGLLDBLauncher;

    "operation_name" = IDEiPhoneRunOperationWorkerGroup;

    "param_consoleMode" = 0;

    "param_debugger_attachToExtensions" = 0;

    "param_debugger_attachToXPC" = 1;

    "param_debugger_type" = 5;

    "param_destination_isProxy" = 0;

    "param_destination_platform" = "com.apple.platform.iphoneos";

    "param_diag_MainThreadChecker_stopOnIssue" = 0;

    "param_diag_MallocStackLogging_enableDuringAttach" = 0;

    "param_diag_MallocStackLogging_enableForXPC" = 1;

    "param_diag_allowLocationSimulation" = 1;

    "param_diag_gpu_frameCapture_enable" = 0;

    "param_diag_gpu_shaderValidation_enable" = 0;

    "param_diag_gpu_validation_enable" = 0;

    "param_diag_memoryGraphOnResourceException" = 0;

    "param_diag_queueDebugging_enable" = 1;

    "param_diag_runtimeProfile_generate" = 0;

    "param_diag_sanitizer_asan_enable" = 0;

    "param_diag_sanitizer_tsan_enable" = 0;

    "param_diag_sanitizer_tsan_stopOnIssue" = 0;

    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;

    "param_diag_showNonLocalizedStrings" = 0;

    "param_diag_viewDebugging_enabled" = 1;

    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;

    "param_install_style" = 0;

    "param_launcher_UID" = 2;

    "param_launcher_allowDeviceSensorReplayData" = 0;

    "param_launcher_kind" = 0;

    "param_launcher_style" = 0;

    "param_launcher_substyle" = 0;

    "param_runnable_appExtensionHostRunMode" = 0;

    "param_runnable_productType" = "com.apple.product-type.application";

    "param_runnable_swiftVersion" = "5.5.2";

    "param_runnable_type" = 2;

    "param_testing_launchedForTesting" = 0;

    "param_testing_suppressSimulatorApp" = 0;

    "param_testing_usingCLI" = 0;

    "sdk_canonicalName" = "iphoneos15.2";

    "sdk_osVersion" = "15.2";

    "sdk_variant" = iphoneos;

}

--





System Information



macOS Version 12.0.1 (Build 21A559)

Xcode 13.2.1 (19586) (Build 13C100)

Timestamp: 2022-01-24T13:13:30+05:30
```

**Comment by deepika134** [comment] 2022-01-25 11:48
Hi flutternoob ,

We can reproduce the reported issue in android device with similar reproduction steps. We are analyzing on this and will update the further details on January 27, 2022.
  
Regards, 
Deepika R

**Comment by flutternoob** [comment] 2022-01-25 14:19
@deepika134 its happening on an iOS device not android

**Comment by dillibabu1802** [comment] 2022-01-27 05:47
https://github.com/syncfusion/flutter-widgets/issues/525

**Comment by dillibabu1802** [comment] 2022-01-27 15:30
Hi @flutternoob ,

On analyzing, we found that issue caused due to image extraction with high quality with respective to zoom value. So this issue is reproduced in lesser RAM devices. We are further analyzing on this and will update the further details on 31 January 2022.

Regards,
Dilli babu.

**Comment by deepika134** [comment] 2022-01-31 04:27
Hi flutternoob,

We have confirmed that the reported issue “Unexpected closure of the app when zooming and scrolling the pdf continuously” is a defect. The issue fix will be included in our upcoming weekly release, which is estimated to be available on February 8, 2022. The status of this issue can be tracked using the following link,
https://www.syncfusion.com/feedback/32260/unexpected-closure-of-the-app-when-zooming-and-scrolling-the-pdf-continuously

Regards,
Deepika Ravi.

**Comment by deepika134** [comment] 2022-02-08 12:59
Hi flutternoob,
  
We have included the fix for the issue " Unexpected closure of the app when zooming and scrolling the pdf continuously " in our latest weekly NuGet release, so kindly upgrade to the latest version v19.4.50 to get the issue resolved.  
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.4.50-beta 

Regards, 
Deepika Ravi

**Comment by Danish-Git** [comment] 2022-02-09 14:37
Hi, I am also facing same issue, I am using iPhone XR for testing, I have also upgraded dependency version to 19.4.50-beta. still facing same crash

LOG - 

syncfusion_flutter_pdfviewer/SwiftSyncfusionFlutterPdfViewerPlugin.swift:146: Fatal error: Unexpectedly found nil while unwrapping an Optional value
syncfusion_flutter_pdfviewer/SwiftSyncfusionFlutterPdfViewerPlugin.swift:146: Fatal error: Unexpectedly found nil while unwrapping an Optional value
* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
    frame #0: 0x0000000185ee9cf4 libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`_swift_runtime_on_report:
->  0x185ee9cf4 <+0>: ret    
libswiftCore.dylib`_swift_reportToDebugger:
    0x185ee9cf8 <+0>: b      0x185ee9cf4               ; _swift_runtime_on_report
libswiftCore.dylib`_swift_shouldReportFatalErrorsToDebugger:
    0x185ee9cfc <+0>: adrp   x8, 335352
    0x185ee9d00 <+4>: ldrb   w0, [x8, #0x874]
Target 0: (Runner) stopped.

**Comment by deepika134** [comment] 2022-02-09 16:03
Hi Danish-Git,

We regret the inconvenience.

We are analyzing the reported issue, can you please share the issue reproducing document. Which will be helpful for us to provide you with a prompt solution at the earliest.

Regards,
Deepika Ravi

**Comment by Danish-Git** [comment] 2022-02-10 05:26
Hi @deepika134,
    
    There is a method which converts image to pngData() format, but whenever the image goes for conversion then it returns nil, So it crashes there because we are doing force unwrap the pngData value.

Class Name : SwiftSyncfusionFlutterPdfViewerPlugin

Method Name : 

```
private func getImageForPlugin(index: Int,scale: CGFloat,documentID: String) -> FlutterStandardTypedData
    {
        let document = self.documentRepo[documentID]!!
        let page = document.page(at: Int(index))
        var pageRect = page!.getBoxRect(.mediaBox)
        let imageRect = CGRect(x: 0,y: 0,width: pageRect.size.width*CGFloat(scale),height: pageRect.size.height*CGFloat(scale))
        if #available(iOS 10.0, *) {
            let format = UIGraphicsImageRendererFormat()
            if #available(iOS 12.0, *) {
                format.preferredRange = .standard
            } else {
                format.prefersExtendedRange = false
            }
            let renderer = UIGraphicsImageRenderer(size: imageRect.size,format: format)
            let img = renderer.image { ctx in
                let mediaBox = page!.getBoxRect(.mediaBox)
                ctx.cgContext.beginPage(mediaBox: &pageRect)
                let transform = page!.getDrawingTransform(.mediaBox, rect: mediaBox, rotate: 0, preserveAspectRatio: true)
                ctx.cgContext.translateBy(x: 0.0, y: imageRect.size.height)
                ctx.cgContext.scaleBy(x: CGFloat(scale), y: -CGFloat(scale))
                ctx.cgContext.concatenate(transform)
                ctx.cgContext.drawPDFPage(page!)
                ctx.cgContext.endPage()
            }
            return FlutterStandardTypedData(bytes: img.pngData()!)              // —————> Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value
        }
        return FlutterStandardTypedData()
    }
```

LOG :

```
syncfusion_flutter_pdfviewer/SwiftSyncfusionFlutterPdfViewerPlugin.swift:146: Fatal error: Unexpectedly found nil while unwrapping an Optional value

2022-02-10 10:33:26.216353+0530 Runner[3939:454440] syncfusion_flutter_pdfviewer/SwiftSyncfusionFlutterPdfViewerPlugin.swift:146: Fatal error: Unexpectedly found nil while unwrapping an Optional value

(lldb) po print(img.pngData())
nil
0 elements

(lldb) po print(img)
<UIImage:0x283a4efd0 anonymous {0, 0} renderingMode=automatic>
0 elements

(lldb) 
```

**Comment by dillibabu1802** [comment] 2022-02-10 06:05
Hi @Danish-Git 

We are looking into this issue and will let you know more details shortly. Could you please confirm whether the issue is reproduced with [https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf](https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf) document as well ? If the issue is not reproduced, then kindly share us the issue reproducing document.

Regards,
Dilli babu.

**Comment by dillibabu1802** [comment] 2022-02-11 11:13
Hi @Danish-Git 

We have simplified the sample by removing Hive module, to find the exact cause of memoy leak. But, the issue wasn't reproduced from our side. Please try the below sample and let us know.
[https://www.syncfusion.com/downloads/support/directtrac/general/ze/ios_crash998022695.zip](https://www.syncfusion.com/downloads/support/directtrac/general/ze/ios_crash998022695.zip)

Initially on Jan 24, memory leak issue was reported with error log but in your last update, you have mentioned the nil unwrapping issue. Kindly confirm us whether the memory leak issue is reproduced now after upgrading to latest version of syncfusion_flutter_pdfviewer.

Regards,
Dilli babu

**Comment by Danish-Git** [comment] 2022-02-15 06:08
Hi @dillibabu1802 

I was waiting for getting authorization form end user to share PDF document with you. So it took too long 

[https://app.mystaffapp.org/system/diliboard_contents/downloadable_files/000/003/525/original/basildon_map.pdf?1644411617](https://app.mystaffapp.org/system/diliboard_contents/downloadable_files/000/003/525/original/basildon_map.pdf?1644411617)

**Comment by dillibabu1802** [comment] 2022-02-15 06:12
Hi @Danish-Git 

Thanks for sharing the document. We will check the issue with this document and let you know about it shortly.

Kindly confirm us the issue is reproduced in [https://www.syncfusion.com/downloads/support/directtrac/general/ze/ios_crash998022695.zip](https://www.syncfusion.com/downloads/support/directtrac/general/ze/ios_crash998022695.zip) sample aswell.

**Comment by Danish-Git** [comment] 2022-02-15 07:22
@dillibabu1802 

I have tried the code file you have provided. It is working fine with the existing PDF file in code, but when I changed it with mine PDF file it crashed
Log -

```

Syncing files to device iPhone XR...
Reloaded 1 of 1163 libraries in 4,331ms.
[ServicesDaemonManager] interruptionHandler is called. -[FontServicesDaemonManager connection]_block_invoke

======== Exception caught by image resource service ================================================
The following _Exception was thrown resolving an image frame:
Exception: Codec failed to produce an image, possibly due to invalid image data.

When the exception was thrown, this was the stack: 
====================================================================================================
* thread #11, name = 'io.flutter.1.raster', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=1850 MB, unused=0x0)
    frame #0: 0x0000000192d22d34 libsystem_malloc.dylib`<redacted> + 2156
libsystem_malloc.dylib`<redacted>:
->  0x192d22d34 <+2156>: sturh  w24, [x11, #-0x2]
    0x192d22d38 <+2160>: mov    x11, x24
    0x192d22d3c <+2164>: ldr    w27, [sp, #0x1c]
    0x192d22d40 <+2168>: b      0x192d22d54               ; <+2188>
Target 0: (Runner) stopped.
```

**Comment by flutternoob** [comment] 2022-02-15 11:44
Now a new error, "Unexpectedly found nil when unwrapping an Optional value", is thrown when scrolling rapidly through the PDF. This error does not occur on an iOS simulator. It occurs only on an iOS device. I have attached the screenshot of the error.

![Error](https://user-images.githubusercontent.com/62204476/154055461-9fa35b43-24f6-4ed4-886a-8b4cdb482d8e.jpeg)

**Comment by deepika134** [comment] 2022-02-16 13:28
Hi @Danish-Git / @flutternoob ,

We are analyzing on the reported issue and will update the further details on February 18, 2022.

Regards,
Deepika Ravi

**Comment by deepika134** [comment] 2022-02-18 14:55
Hi @flutternoob / @Danish-Git,

We can reproduce the reported issue on our end and will update the further details on February 22, 2022.

Regards,
Deepika Ravi

**Comment by abnerh69** [comment] 2022-02-19 14:25
Hi.  Thank you very much for taking your time to solve and share solutions so quickly.
I have similar issue on Android 11 (Samsung  Galaxy Tab S6 Lite SM-P610 64Gb).
Any hope to have solution on February 22, 2022?  Thanks.

**Comment by deepika134** [comment] 2022-02-21 16:15
Hi Abner Hernandez,

The crash issue reproduced only in iOS physical devices. To reproduce the crash issue in the Android tab, kindly share the following details,

1. Issue reproducing steps.
2. Issue reproducing document.
3. syncfusion_flutter_pdfviewer package version.
4. Flutter SDK version.

This information will be helpful for us to provide you with a prompt solution at the earliest.

Regards,
Deepika Ravi

**Comment by deepika134** [comment] 2022-02-22 16:09
Hi @Danish-Git , 
 
We have confirmed that the reported issue “Unexpected closure of the app when zooming and scrolling the pdf continuously” is a defect. The issue fix will be included in our upcoming weekly release, which is estimated to be available on 08 March 2021. The status of this issue can be tracked using the following link, https://www.syncfusion.com/feedback/32260/unexpected-closure-of-the-app-when-zooming-and-scrolling-the-pdf-continuously 

@flutternoob / @abnerh69,
Kindly share the document in which you are facing the reported issue it will be helpful for us to ensure the fix. 

Regards, 
Deepika Ravi

**Comment by Danish-Git** [comment] 2022-02-23 11:26
> Hi @dillibabu1802
> 
> I was waiting for getting authorization form end user to share PDF document with you. So it took too long
> 
> https://app.mystaffapp.org/system/diliboard_contents/downloadable_files/000/003/525/original/basildon_map.pdf?1644411617

@deepika134, Thanks for the update. Please refer to this PDF document . Hope it will be helpful to you

**Comment by flutternoob** [comment] 2022-02-23 16:02
@deepika134 The issue occurs with files that have more than 100 - 150 pages in them and rapid scrolling is attempted. I have attached a couple of them.
[lucifer_v3.pdf](https://github.com/syncfusion/flutter-widgets/files/8125822/lucifer_v3.pdf)

[lucifer_v2.pdf](https://github.com/syncfusion/flutter-widgets/files/8125816/lucifer_v2.pdf)

**Comment by deepika134** [comment] 2022-02-24 06:34
Hi @flutternoob / @Danish-Git,

Thank you for the update.

As we mentioned earlier, we will include the fix for ‘Unexpected closure of the app when zooming and scrolling the pdf continuously’ on the March 2nd weekly release.

Regards,
Deepika Ravi

**Comment by flutternoob** [comment] 2022-03-04 14:19
@deepika134 are there any updates on this issue?

**Comment by deepika134** [comment] 2022-03-08 16:02
Hi @flutternoob ,

Currently, we have improved the scrolling and image rendering in the iOS platform, which also resolves the crashing issue. kindly upgrade to the latest version v19.4.55 and let us know whether the issue persists or not.
https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.4.55-beta 

We are still working on improvement in the scrolling and image rendering module of Flutter PdfViewer. This implementation will be included in our next weekly package release which will be available on March 15, 2022.

Regards,
Deepika Ravi

**Comment by deepika134** [comment] 2022-03-08 16:03
Hi @Danish-Git,

We have improved the scrolling and image rendering in the iOS platform, which also resolves the crashing issue but in the provided document the higher resolution PDF Pages( the actual size of the page is 3772*5340), on zooming the pages the resolution of the document is increased which results in the crash. Currently, we are working on this with high priority and the fix will be included in our upcoming weekly release which will be available on March 15, 2022.

Regards,
Deepika Ravi

**Comment by deepika134** [comment] 2022-03-15 12:35
Hi @flutternoob / @Danish-Git ,

We have included the enhancement of the scrolling and image rendering module in our latest weekly NuGet release, so kindly upgrade to the latest version v19.4.56.

Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.4.56-beta

Regards,
Deepika Ravi

**Comment by Danish-Git** [comment] 2022-03-21 05:45
Hi @deepika134 

Thank you for the update. I have updated to v19.4.56-beta and its working awesome. this will help me lot.
wish you and your team with best wishes. 

Thanks

**Comment by deepika134** [comment] 2022-03-23 03:48
Hi Danish-Git,

Thank you for the update. We are glad to know that the reported issue has been resolved at your end.

Regards,
Deepika Ravi

**Closed** 2022-04-25 05:20 UTC

**Comment by rodrigorafaeldamaceno** [comment] 2022-05-04 13:51
@deepika134  This error continue ocorrer in 20.1.52-beta, any update?
`
The app “Runner” on @andrepaulii quit unexpectedly.
Domain: IDEDebugSessionErrorDomain
Code: 10
Failure Reason: Message from debugger: Terminated due to memory issue
User Info: {
  DVTErrorCreationDateKey = “2022-05-04 13:45:45 +0000";
  IDERunOperationFailingWorker = DBGLLDBLauncher;
}
--
Analytics Event: com.apple.dt.IDERunOperationWorkerFinished : {
  “device_model” = “iPhone14,5";
  “device_osBuild” = “15.4.1 (19E258)“;
  “device_platform” = “com.apple.platform.iphoneos”;
  “launchSession_schemeCommand” = Run;
  “launchSession_state” = 2;
  “launchSession_targetArch” = arm64;
  “operation_duration_ms” = 66692;
  “operation_errorCode” = 10;
  “operation_errorDomain” = IDEDebugSessionErrorDomain;
  “operation_errorWorker” = DBGLLDBLauncher;
  “operation_name” = IDEiPhoneRunOperationWorkerGroup;
  “param_consoleMode” = 0;
  “param_debugger_attachToExtensions” = 0;
  “param_debugger_attachToXPC” = 1;
  “param_debugger_type” = 5;
  “param_destination_isProxy” = 0;
  “param_destination_platform” = “com.apple.platform.iphoneos”;
  “param_diag_MainThreadChecker_stopOnIssue” = 0;
  “param_diag_MallocStackLogging_enableDuringAttach” = 0;
  “param_diag_MallocStackLogging_enableForXPC” = 1;
  “param_diag_allowLocationSimulation” = 1;
  “param_diag_gpu_frameCapture_enable” = 0;
  “param_diag_gpu_shaderValidation_enable” = 0;
  “param_diag_gpu_validation_enable” = 0;
  “param_diag_memoryGraphOnResourceException” = 0;
  “param_diag_queueDebugging_enable” = 1;
  “param_diag_runtimeProfile_generate” = 0;
  “param_diag_sanitizer_asan_enable” = 0;
  “param_diag_sanitizer_tsan_enable” = 0;
  “param_diag_sanitizer_tsan_stopOnIssue” = 0;
  “param_diag_sanitizer_ubsan_stopOnIssue” = 0;
  “param_diag_showNonLocalizedStrings” = 0;
  “param_diag_viewDebugging_enabled” = 1;
  “param_diag_viewDebugging_insertDylibOnLaunch” = 1;
  “param_install_style” = 0;
  “param_launcher_UID” = 2;
  “param_launcher_allowDeviceSensorReplayData” = 0;
  “param_launcher_kind” = 0;
  “param_launcher_style” = 0;
  “param_launcher_substyle” = 0;
  “param_runnable_appExtensionHostRunMode” = 0;
  “param_runnable_productType” = “com.apple.product-type.application”;
  “param_runnable_swiftVersion” = “5.6”;
  “param_runnable_type” = 2;
  “param_testing_launchedForTesting” = 0;
  “param_testing_suppressSimulatorApp” = 0;
  “param_testing_usingCLI” = 0;
  “sdk_canonicalName” = “iphoneos15.4”;
  “sdk_osVersion” = “15.4”;
  “sdk_variant” = iphoneos;
}
--
System Information
macOS Version 12.3.1 (Build 21E258)
Xcode 13.3.1 (20103) (Build 13E500a)
Timestamp: 2022-05-04T10:45:45-03:00
`
