### ISSUE TITLE
[Syncfusion_Datagrid] Grid page selector and text filter window background is transparency.

### ISSUE THREAD

**Issue by kanazzang** [syncfusion/flutter-widgets#1204] opened 2023-05-18 17:18 UTC
**The background color becomes transparent, making it inconvenient to use.** 

![image](https://github.com/syncfusion/flutter-widgets/assets/36879851/a2813b16-57ce-4bbd-ad8c-25ee543b5189)

![image](https://github.com/syncfusion/flutter-widgets/assets/36879851/6a1f06d3-5e64-4869-9852-abd846a99a8e)

**How can I make it not appear transparent like below?**

![image](https://github.com/syncfusion/flutter-widgets/assets/36879851/129f68e0-60ac-496e-85d0-817f61a78243)

![image](https://github.com/syncfusion/flutter-widgets/assets/36879851/b5a019da-bd3c-4d52-ad44-4f7367112945)

**Comment by Tamilarasan-Paranthaman** [comment] 2023-05-19 07:30
Hi @kanazzang,

Based on the information you provided, we have conducted tests using the attached sample in DataGrid version **21.2.5** and Flutter SDK version **3.10.0**. However, we were unable to reproduce the reported issue and found that the background color is not transparent.

We understand that you are still facing difficulties, and we are committed to helping you resolve the issue as quickly as possible. To further investigate, we have attached a sample that we tested, along with the corresponding output reference.

If possible, could you please provide the specific sample that is causing the issue? Alternatively, you can modify the attached sample to make it reproducible, which will allow us to investigate the problem more effectively and provide you with a timely solution.

**Sample Link: [DataGrid-Sample](https://github.com/syncfusion/flutter-widgets/files/11514555/sample.zip)**



https://github.com/syncfusion/flutter-widgets/assets/93904422/38032315-4998-4257-9a0a-feea32b8cd6f



Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment] 2024-02-08 04:40
Hi @kanazzang,

We suspect that the reported problem has been resolved at your end. We are closing this issue. Please let us know if you have any further queries on this. We are happy to help you.

Regards, 
Ashok K

**Comment by ashok-kuvaraja** [comment] 2024-02-08 04:40
Hi @kanazzang,

We suspect that the reported problem has been resolved at your end. We are closing this issue. Please let us know if you have any further queries on this. We are happy to help you.

Regards, 
Ashok K

**Closed by ashok-kuvaraja** 2024-02-08 04:40 UTC
Labels: data_grid
