### ISSUE TITLE
Invalid argument(s): Missing library: package:syncfusion_flutter_pdf/src/pdf/implementation/primitives//pdf_name.dart

### ISSUE THREAD

**Issue by Avadhesh-Pandey** [syncfusion/flutter-widgets#503] opened 2021-12-22 07:00 UTC
Unable to create release APK post updating the library and Dart to latest version.

ERROR : Invalid argument(s): Missing library: package:syncfusion_flutter_pdf/src/pdf/implementation/primitives//pdf_name.dart

Version : 
Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (6 days ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

**Comment by Surya-3013** [comment] 2021-12-23 09:37
Hi Avadhesh-Pandey / aleslanik2,

We have tried to reproduce the reported issue with the latest Flutter and Dart SDK versions, but we are not facing any issues in the release mode and we have shared the sample which we tried on our end for your reference. We request you to the following details to reproduce the issue on our end.

1.	Flutter doctor details.
2.	Sample code to reproduce the reported issue/Modify the provided sample to replicate the issue.
3.	Android device details.

Sample link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample_pdf635490551

Regards, 
Surya V

**Comment by bassichetti** [comment] 2021-12-26 22:45
Hello, on a machine that didn't have the memory cleared, it's ok, but if you clear the memory it doesn't work anymore after the **"flutter pub cache repair"** command.

**Comment by chinnumuniyappan** [comment] 2021-12-28 13:54
Hi @bassichetti,

We have tried to reproduce the reported issue by cleaning the flutter pub cache using repair (**flutter pub cache repair**) and clean (**flutter pub cache clean**) comments, But it was working as expected on our
end.

 
![image](https://user-images.githubusercontent.com/65020530/147573143-783258f5-f775-4fbd-9185-5ea1b58c2ebc.png)


Based on the stack trace, we suspect the reported issue due to adding more than one forward slash to importing dart files. And confirmed this to be a defect on our end. The fix for this issue will be available on our upcoming weekly release on January 4, 2022.

Kindly use the below feedback link to track the status of the reported bug, 
https://www.syncfusion.com/feedback/31519/invalid-arguments-exception-while-creating-release-apk 

Regards, 
Chinnu M

**Comment by bassichetti** [comment] 2021-12-29 19:16
all work now, tsk

**Closed** 2022-01-10 06:21 UTC

**Comment by CartmanGD** [comment] 2022-09-08 08:10
Running `flutter clean` -> `flutter pub cache repair` -> and then `flutter pub get` solved my issue.
