### ISSUE TITLE
Negative images

### ISSUE THREAD

**Issue by pmagnuson** [syncfusion/flutter-widgets#280] opened 2021-06-15 00:06 UTC
On some Apple devices, we are seeing images in the PDF document, displayed as inverted/negatives of the intended image.  
I will attach a .PDF sample page and a screenshot of the displayed image on the device.  

Note - using `syncfusion_flutter_pdfviewer: ^18.4.49-beta`.  I cannot upgrade to newer version due to conflicts with `googleapis_auth ^0.2.12+1`

Apple device:  `iPad (6th generation) MR7C2LL/A.  IOS 14.2`

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.3.1 20E241 darwin-x64, locale en-US)
    • Flutter version 2.0.4 at /Users/phil/bin/flutter
    • Framework revision b1395592de (2 months ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/phil/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • PTM iPad (mobile) • 87132db6298fc2f271dd2785c026bb1d94dd1442 • ios            • iOS 14.2
    • Chrome (web)      • chrome                                   • web-javascript • Google Chrome 91.0.4472.101

• No issues found!
```
source PDF document.  Images are greyscale PNG files.
[pg 90.pdf](https://github.com/syncfusion/flutter-widgets/files/6651856/pg.90.pdf)

screenshot from iPad
![IMG_0244](https://user-images.githubusercontent.com/1516372/121973656-a1b53b80-cd32-11eb-932b-c660ead26218.jpg)

**Comment by dillibabun** [comment] 2021-06-15 15:53
Hi @pmagnuson ,

Greetings from Syncfusion.

We are analyzing on the reported issues at our end. We will update the further details on 17 June 2021.

Regards,
Dilli babu

**Comment by dillibabun** [comment] 2021-06-17 17:26
Hi @pmagnuson,

We tried to reproduce the reported issue and the images are preserved properly across different Apple devices We are still checking on different iPad devices and will update the analysis details on 18 June 2021.

Regards,
Dilli babu.

**Comment by dillibabun** [comment] 2021-06-18 17:01
Hi @pmagnuson,

We tried to reproduce the reported issues in different Apple devices and the images were preserved properly. We request you to check the PDF document with our [example ](https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_pdfviewer/example) project and make sure there are no changes done in our source files(Runner, native files in iOS folder).

Regards,
Dilli babu.

**Comment by pmagnuson** [comment] 2021-06-22 17:49
I downloaded the SyncFusion libraries from this repository.  
Using the VSCode environment, I successfully ran the example flutter app in `flutter-widgets/packages/syncfusion_flutter_pdfviewer/example`.

My application loads the PDFs from assets, so I created a `assets/` directory containing the file `se_en.pdf` (and ran `flutter clean`)

<img width="336" alt="Screen Shot 2021-06-22 at 10 39 46 AM" src="https://user-images.githubusercontent.com/1516372/122973591-41cc1f80-d346-11eb-962d-0fea820370c8.png">

I changed the lines from

```dart
body: SfPdfViewer.network(
          'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf',
        key: _pdfViewerKey,
      ),
```
to user the asset loader

```dart
body: SfPdfViewer.asset(
        'assets/se_en.pdf',
        // SfPdfViewer.network(
        //   'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf',
        key: _pdfViewerKey,
      ),
```
this generates an exception in `pdf_provider.dart`
<img width="665" alt="Screen Shot 2021-06-22 at 10 43 32 AM" src="https://user-images.githubusercontent.com/1516372/122974162-dc2c6300-d346-11eb-90fc-de1689b155a9.png">

This error occurs on an IOS Simulator, IOS iPad, Android Pixel 3 XL.  

getting the `SfPdfViewer.asset` to work would be greatly appreciated so I can investigate this further.

Thank you.

**Comment by pmagnuson** [comment] 2021-06-23 00:50
I have been able to duplicate the defect in the SyncFusion example app for pdf_viewer.  

using this code:
```dart
body: SfPdfViewer.network(
        'http://localhost:8000/static/pg90.pdf',
        //   'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf',
        key: _pdfViewerKey,
      ),
```

here is pg90.pdf which shows correct images in most pdf viewers.
[pg90.pdf](https://github.com/syncfusion/flutter-widgets/files/6698145/pg90.pdf)

a screenshot from the IOS Simulator - the 6 lower images are negatives of the intended display.
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-06-22 at 17 44 39](https://user-images.githubusercontent.com/1516372/123017713-fdf70b80-d381-11eb-8f70-96169a067561.png)

Simulator is `Version 12.5 (961.1)`.
Device is `iPad Pro (9.7-inch) IOS 14.5`

Thank you,

**Comment by dillibabun** [comment] 2021-06-23 14:30
Hi @pmagnuson 

Thank you for the details.

We can reproduce the reported issue from our side. We suspect the issue is with Core graphics of iOS 14.4 and will update the further details on 25 June 2021.

Regards,
Dilli babu.

**Comment by dillibabun** [comment] 2021-06-27 15:59
Hi @pmagnuson 

We have confirmed that the "Grayscale image appears inverted in iOS 14.1 devices" is a defect and the fix for the issue will be included in July 1st weekly package release which is estimated to be available on July 6 2021 tentatively.

The status of this bug can be tracked using the following link.
[https://www.syncfusion.com/feedback/26504/grayscale-image-appears-inverted-in-ios-14-1-devices
](https://www.syncfusion.com/feedback/26504/grayscale-image-appears-inverted-in-ios-14-1-devices
)

Regards,
Dilli babu.

**Comment by sarathkumar50** [comment] 2021-07-06 11:25
Hi @pmagnuson,

Weekly package([19.2.46-beta](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.2.46-beta)) has been released. We have tested this package and the reported issue with "Grayscale image appears inverted in iOS 14.1 devices" has been resolved. Kindly use the latest package and let us know if you are facing any other issues.

Regards,
Sarath Kumar.

**Comment by pmagnuson** [comment] 2021-07-12 16:19
Thank you so much for looking into this.  I have updated to the latest version and the issue is resolved.  
Great work!!

**Closed** 2021-07-14 04:25 UTC
