### ISSUE TITLE
Syncfusion DataGridview Multi Focus on Cell when remove all rows add new rows

### ISSUE THREAD

**Issue by abdulrehmananwar** [syncfusion/flutter-widgets#1226] opened 2023-05-30 18:43 UTC
Step 1:- i have input in qty column press enter key. againt input in 2nd row press enter key 
now i have three rows and focus show up in 3rd row quantity column.
Step 2 :- i press reset (which clear existing rows  and add blank row) 
step 3 :- againt i do same as Step 1 now focus showing where before clear rows.

![image](https://github.com/syncfusion/flutter-widgets/assets/62530396/3f21ee25-74b6-471c-b923-4b942ad9646e)

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:syncfusion_flutter_datagrid/datagrid.dart';
import 'package:collection/collection.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Syncfusion DataGrid Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MainGridPage(),
    );
  }
}

class MainGridPage extends StatefulWidget {
  const MainGridPage({Key? key}) : super(key: key);
  @override
  State createState() => _MainPageState();
}

late EmployeeDataSource _employeeDataSource1;

class _MainPageState extends State {
  List<GridFields> firstgridflieds = [];
  Map<String, dynamic> datalists = <String, dynamic>{};
  List listsnames = ['fruit', 'vegetables', 'animals'];
  List<Map<String, dynamic>> gridlist = [];

  @override
  void initState() {
    firstgridflieds = [
      GridFields(FieldName: 'Name', InputType: 'search', ReadOnly: false),
      GridFields(FieldName: 'Quantity', InputType: 'number', ReadOnly: false),
      GridFields(FieldName: 'Price', InputType: 'decimal', ReadOnly: false),
      GridFields(FieldName: 'Amount', InputType: 'number', ReadOnly: true),
    ];
    super.initState();
    for (int index = 0; index < listsnames.length; index++) {
      String listkey = listsnames[index].toString();

      if (!datalists.containsKey(listsnames[index].toString())) {
        datalists[listkey] = [];
      }
      gridlist = List<Map<String, dynamic>>.from(datalists[listkey]);

      //Create the data source for the grids only once
      if (index == 0) {
        _employeeDataSource1 =
            EmployeeDataSource(gridlist, firstgridflieds, context);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text('Syncfusion DataGrid Demo')),
        body: SingleChildScrollView(
            child: Column(
              children: [
                Row(
                  children: [
                    MaterialButton(
                        color: Colors.amber,
                        child: const Text('Reset'),
                        onPressed: () {
                          //Clear the values of the first grid
                          _employeeDataSource1.dataGridRows.clear();
                          _employeeDataSource1.EmpList.clear();
                          _employeeDataSource1.updateDataSource();
                          _employeeDataSource1.addrow();

                          setState(() {});
                        }),
                    MaterialButton(
                        color: Colors.green,
                        child: const Text('Submit'),
                        onPressed: () {
                          //Get the values of the first grid
                          for (var details in _employeeDataSource1.dataGridRows) {
                            print(details.getCells()[0].value);
                          }
                        }),
                  ],
                ),
                DataGridView(

                    gridfields: firstgridflieds,
                    datalist: gridlist,
                    source:  _employeeDataSource1)
              ],
            )));
  }
}

class DataGridView extends StatefulWidget {
  final List<GridFields> gridfields;
  final List<Map<String, dynamic>> datalist;
  final EmployeeDataSource source;
  const DataGridView(
      {Key? key,
        required this.gridfields,
        required this.datalist,
        required this.source})
      : super(key: key);

  @override
  State<DataGridView> createState() => _DataGridViewState();
}

class _DataGridViewState extends State<DataGridView> {
  @override
  void dispose() {
    dataGridController.dispose();
    super.dispose();
  }

  DataGridController dataGridController = DataGridController();

  late CustomSelectionManager _customSelectionManager;

  @override
  void initState() {
    super.initState();

    _customSelectionManager = CustomSelectionManager(dataGridController);

    widget.source.addrow();
  }

  @override
  Widget build(BuildContext context) {
    return SfDataGrid(
      selectionMode: SelectionMode.single,
      navigationMode: GridNavigationMode.cell,
      editingGestureType: EditingGestureType.tap,
      selectionManager: _customSelectionManager,
      allowEditing: true,
      isScrollbarAlwaysShown: true,
      source: widget.source,
      controller: dataGridController,
      headerGridLinesVisibility: GridLinesVisibility.both,
      gridLinesVisibility: GridLinesVisibility.both,
      columns: List.generate(
          widget.gridfields.length,
              (i) => GridColumn(
              columnName: widget.gridfields[i].FieldName,
              label: Container(
                  alignment: Alignment.centerLeft,
                  child: Text(widget.gridfields[i].FieldName)))),
    );
  }
}

class EmployeeDataSource extends DataGridSource {
  EmployeeDataSource(this.EmpList, this.GridColumnList, this._context) {
    updateDataGridRows();
  }

  updateDataGridRows() async {
    dataGridRows = EmpList.map((e) => DataGridRow(
        cells: List.generate(
            GridColumnList.length,
                (i) => DataGridCell(
                columnName: GridColumnList[i].FieldName,
                value: e[GridColumnList[i].FieldName])))).toList();
  }

  final BuildContext _context;
  List<Map<String, dynamic>> EmpList = [];
  List GridColumnList = [];
  List<DataGridRow> dataGridRows = [];

  /// Helps to hold the new value of all editable widget.
  /// Based on the new value we will commit the new value into the corresponding
  /// [DataGridCell] on [onSubmitCell] method.
  dynamic newCellValue;

  /// Help to control the editable text in [TextField] widget.
  TextEditingController editingController = TextEditingController();

  @override
  List<DataGridRow> get rows => dataGridRows;

  void addrow() {
    Map<String, dynamic> value = {};
    EmpList.insert(EmpList.length, value);

    updateDataGridRows();
    notifyListeners();
  }

  @override
  Future<void> onCellSubmit(DataGridRow dataGridRow,
      RowColumnIndex rowColumnIndex, GridColumn column) async {
    final dynamic oldValue = dataGridRow
        .getCells()
        .firstWhereOrNull((DataGridCell dataGridCell) =>
    dataGridCell.columnName == column.columnName)
        ?.value ??
        '';

    final int dataRowIndex = dataGridRows.indexOf(dataGridRow);

    if (newCellValue == null || oldValue == newCellValue) {
      return;
    } else {
      // if new value found

      // set new value to Map List Row
      EmpList[dataRowIndex][column.columnName] = newCellValue;

      // get current row value
      Map<String, dynamic> currentrowvalues = EmpList[dataRowIndex];

      // do calculation for other columns
      int quantity = 0;
      int price = 0;
      int amount = 0;
      quantity = int.tryParse(currentrowvalues.containsKey('Quantity')
          ? currentrowvalues['Quantity'].toString()
          : "0") ??
          0;
      price = int.tryParse(currentrowvalues.containsKey('Price')
          ? currentrowvalues['Price'].toString()
          : "0") ??
          0;
      amount = quantity * price;

      // set value to Amount Cell
      EmpList[dataRowIndex]["Amount"] = amount;
      // reset current row values after adding new cells
      currentrowvalues = EmpList[dataRowIndex];

      // now assign new row values to GridRow through loop over each field
      GridColumnList.asMap().forEach((index, value) {
        // set new value to grid row
        dataGridRows[dataRowIndex].getCells()[index] = DataGridCell<dynamic>(
            columnName: value.FieldName,
            value: currentrowvalues.containsKey(value.FieldName)
                ? currentrowvalues[value.FieldName]
                : null);

        //notify listner to refresh cells
        notifyDataSourceListeners(
            rowColumnIndex: RowColumnIndex(rowColumnIndex.rowIndex, index));
      });

      // if current row is last row then add new row
      if (rowColumnIndex.rowIndex + 1 == rows.length) {
        addrow();
      }
    }
  }

  /// A boolean variable that indicates whether a dialog is currently open or not.
  bool isDialogOpen = false;

  /// A list of strings containing the names of different fruits.
  List<String> fruitlist = ["Apple", "Orange", "blueberry", "banana"];

  // List of search fruits that can be used to store and manipulate a collection of strings related to fruits.
  // This list can be modified at runtime as required.
  List<String> fruits = [];

  @override
  Future<bool> canSubmitCell(DataGridRow dataGridRow,
      RowColumnIndex rowColumnIndex, GridColumn column) async {
    GridFields fieldmodel = GridColumnList.where(
            (element) => element.FieldName == column.columnName).single;
    if (fieldmodel.InputType == "search" &&
        newCellValue != null &&
        newCellValue != '') {
      fruits = fruitlist
          .where((food) => food.toLowerCase().contains(newCellValue))
          .toList();

      // Check if a dialog is not already open and fruits list is not empty
      if (!isDialogOpen && fruits.isNotEmpty) {
        // Set isDialogOpen to true to indicate a dialog is being opened
        isDialogOpen = true;
        // Open the dialog box and wait for it to be dismissed
        await dialogbox(rowColumnIndex);
        // Set isDialogOpen to false to indicate the dialog has been closed
        isDialogOpen = false;

        // Check if the new value is available in the list.
        // If not available means the value is not selected from the dialog box, then return false to avoid the cell submission.
        if (fruits.contains(newCellValue)) {
          return true;
        } else {
          return false;
        }
      } else if (isDialogOpen) {
        // To allow the focus to the Dialog box.
        return true;
      } else {
        // To avoid the cell submission when the typed value is not available in the list.
        return false;
      }
    }
    // return true to allow the cell submission for other column.
    return true;
  }

  Future<void> dialogbox(RowColumnIndex rowColumnIndex) async {
    if (newCellValue.length > 0) {
      if (fruits.length == 1) {
        newCellValue = fruits[0];
        return;
      }
    }

    // ignore: prefer_is_empty
    if (fruits.length > 0) {
      await showDialog(
          context: _context,
          builder: (context) {
            return AlertDialog(
                scrollable: true,
                shape: const RoundedRectangleBorder(
                    borderRadius: BorderRadius.all(Radius.zero)),
                title: SizedBox(
                    width: 300,
                    height: 300,
                    child: ListView.builder(
                      itemCount: fruits.length,
                      itemBuilder: (context, i) {
                        return ListTile(
                          title: Text(fruits[i].toString()),
                          onTap: () async {
                            String value = fruits[i];
                            newCellValue = value;
                            Navigator.pop(context);
                          },
                        );
                      },
                    )));
          });
    }
  }

  @override
  Widget? buildEditWidget(DataGridRow dataGridRow,
      RowColumnIndex rowColumnIndex, GridColumn column, CellSubmit submitCell) {
// The new cell value must be reset.
// To avoid committing the [DataGridCell] value that was previously edited
// into the current non-modified [DataGridCell].
    newCellValue = null;

// get current row values
    Map<String, dynamic> rowvalue = EmpList[rowColumnIndex.rowIndex];
// get current field model
    GridFields fieldmodel = GridColumnList.where(
            (element) => element.FieldName == column.columnName).single;

// extract cell value from current row and set to text field
    editingController.text = rowvalue.containsKey(column.columnName)
        ? rowvalue[column.columnName].toString()
        : "";
    return TextField(
        autofocus: true,
        maxLines: 1,
        readOnly: fieldmodel.ReadOnly,
        controller: editingController,
        onChanged: (dynamic value) {
          //if (value.isNotEmpty) {
          newCellValue = value;
          // }
        },
        decoration: InputDecoration(
            border: InputBorder.none,
            isDense: true,
            suffix: fieldmodel.InputType == "search"
                ? ExcludeFocus(
                child: InkWell(
                    child: const Icon(Icons.search),
                    onTap: () => dialogbox(rowColumnIndex)))
                : null));
  }

  @override
  DataGridRowAdapter buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map((e) {
          return Text(
            e.value != null ? e.value.toString() : "",
//            style:Theme.of(_context).textTheme.bodyText1,
          );
        }).toList());
  }

  void updateDataSource() {
    notifyListeners();
  }
}

// create grid fields dynamically
class GridFields {
  final String FieldName;
  final String InputType;
  final bool ReadOnly;
  GridFields(
      {required this.FieldName,
        required this.InputType,
        required this.ReadOnly});

  factory GridFields.fromJson(Map<String, dynamic> json) {
    return GridFields(
        FieldName: json['FieldName'],
        InputType: json['InputType'],
        ReadOnly: json['InputType']);
  }
}

class CustomSelectionManager extends RowSelectionManager {
  CustomSelectionManager(this.dataGridController);
  DataGridController dataGridController;
  bool istabPressed = false;
  @override
  Future<void> handleKeyEvent(RawKeyEvent keyEvent) async {
    istabPressed = true;
    if (keyEvent.logicalKey == LogicalKeyboardKey.tab||keyEvent.logicalKey == LogicalKeyboardKey.enter) {
      super.handleKeyEvent(keyEvent).then((value) =>
          WidgetsBinding.instance.addPostFrameCallback((timeStamp) async {
            await dataGridController.beginEdit(dataGridController.currentCell);
          }));

      return;
    }
    super.handleKeyEvent(keyEvent);
  }
}

**Comment by Tamilarasan-Paranthaman** [comment] 2023-05-31 14:03
Hi @abdulrehmananwar,

Based on the information and steps provided, we have thoroughly tested the provided sample on our end. However, we were unable to reproduce the reported issue. Following the given steps, we observed that when the current cell is on the third row and the "Reset" button is clicked to clear the rows, the focus is properly shown on the cell after performing step 1. We did not encounter any instances of multiple focus on the DataGrid.


https://github.com/syncfusion/flutter-widgets/assets/93904422/0b2e8d6e-37de-4b0c-a2b2-315b0daca5b8



To assist you further and understand the issue better, we kindly request you to provide any additional details or steps that may help us in reproducing the problem. Additionally, if possible, please provide a video recording demonstrating the issue for better clarity.

Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment] 2024-02-08 04:45
Hi @abdulrehmananwar,

We suspect that the reported problem has been resolved at your end. We are closing this issue. Please let us know if you have any further queries on this. We are happy to help you.

Regards, 
Ashok K

**Closed by ashok-kuvaraja** 2024-02-08 04:45 UTC
Labels: data_grid
