### ISSUE TITLE
[syncfusion_flutter_pdfviewer] MissingPluginException in Flutter web release mode

### ISSUE THREAD

**Issue by sulthanalihsan** [syncfusion/flutter-widgets#1235] opened 2023-06-03 14:28 UTC
**[Issue Title]**

Error when using `syncfusion_flutter_pdfviewer` package in Flutter web release mode

**[Issue Description]**

I encountered an issue while using the `syncfusion_flutter_pdfviewer` package in release mode for Flutter web. The package works fine in debug mode but throws a `MissingPluginException` error in release mode. I am using Flutter version 3.10.1 and `syncfusion_flutter_pdfviewer` package version 21.2.8.

**[Additional Context]**

I have followed the necessary steps to integrate the `syncfusion_flutter_pdfviewer` package into my Flutter web project. It works flawlessly in debug mode, but when I switch to release mode, I encounter the `MissingPluginException` error.

**[Steps to Reproduce]**

1. Create a Flutter web project.
2. Add the `syncfusion_flutter_pdfviewer` package to the `pubspec.yaml` file.
3. Add the following script to the HTML file (`web/index.html`):

   ```html
   <script src="//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.min.js"></script>
   <script type="text/javascript">
     pdfjsLib.GlobalWorkerOptions.workerSrc = "//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.worker.min.js";
   </script>
   ```

4. Utilize the package to display a PDF file in the application.

   ```dart
   class PdfViewerPage extends StatelessWidget {
     @override
     Widget build(BuildContext context) {
       return Scaffold(
         body: SfPdfViewer.network('http://pdf.pdf'),
       );
     }
   }
   ```

5. Build and run the application in release mode.

**[Expected Behavior]**

The `syncfusion_flutter_pdfviewer` package should work without any issues in both debug and release modes for Flutter web.

**[Actual Behavior]**

In release mode, the application throws a `MissingPluginException` when trying to use the `syncfusion_flutter_pdfviewer` package. The error does not occur in debug mode.

**[Environment]**

- Flutter version: 3.10.1
- `syncfusion_flutter_pdfviewer` package version: 21.2.8

**[Additional Notes]**

I have verified that all the necessary steps for integrating the `syncfusion_flutter_pdfviewer` package into my Flutter web project have been followed. The issue occurs specifically in release mode, and the package works fine in debug mode.

Any help or suggestions to resolve this issue would be greatly appreciated. Thank you.

![{9FE5C4B7-89BB-489D-9998-05B84365E2BA}](https://github.com/syncfusion/flutter-widgets/assets/30169687/2c893f1b-907d-4c32-af28-66a45fcf294c)

**Comment by deepika134** [comment] 2023-07-27 05:54
Hi @sulthanalihsan ,
We tried to reproduce the reported issue with the provided details, but the PDF document loaded correctly in release mode on our end. For your reference, we have attached the tested sample, as well as a screen recording of the output, which can be downloaded from the attachment. Please review the sample and inform us if you are still encountering the issue on your end. If so, kindly provide a modified issue reproducing sample.
[github_1235.zip](https://github.com/syncfusion/flutter-widgets/files/12179735/github_1235.zip)

**Comment by ramkumarsync** [comment] 2024-02-08 07:27
We are closing this issue since we don't have enough information to reproduce it. You can reopen this anytime and share the requested details to proceed further.

**Closed by ramkumarsync** 2024-02-08 07:27 UTC
Labels: pdf_viewer
