### ISSUE TITLE
Another exception was thrown: Invalid argument (fontName): invalid font name: "Helvetica#2DBold"

### ISSUE THREAD

**Issue by umairwarriach26** [syncfusion/flutter-widgets#1665] opened 2024-02-13 13:48 UTC
<img width="1440" alt="Screenshot 2024-02-13 at 5 49 27 PM" src="https://github.com/syncfusion/flutter-widgets/assets/75238940/f1967111-dfdb-4fcf-976c-6c4e512eef24">
 FontStructure._getFontFamily (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/font_structure.dart:1036:9)
#1      FontStructure.createStandardFont (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/font_structure.dart:976:40)
#2      PdfTextExtractor._renderFont (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:1667:19)
#3      PdfTextExtractor._renderText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:1293:15)
#4      PdfTextExtractor._getText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:296:23)
#5      PdfTextExtractor._extractText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_ex<…>

**Comment by irfanajaffer** [comment] 2024-02-14 10:08
We were unable to reproduce the reported issue. We suspect that the issue may be document specific. Kindly provide us with a issue PDF document to analyze further in this..

**Comment by umairwarriach26** [comment] 2024-02-14 10:13
Hi thabks for reaching out to me. Kindly find the attached file below.

**Comment by irfanajaffer** [comment] 2024-02-16 11:15
We couldn't be able to find the attachment. Can you please resend it or if you find it confidential, please share it our official support email id (support@syncfusion.com)? so that we can assist you further in this.

**Comment by umairwarriach26** [comment] 2024-02-16 11:17
Sorry about that .I will resend it at the earliest.

**Comment by jeyalakshmit** [comment] 2024-02-19 13:38
We have confirmed the issue ”Invalid font name error occurs when extracting text from specific PDF document” as a defect in our product and fix will be included in our upcoming weekly release, which will be available on February 27, 2024.


Use the below feedback link to track the status of the reported bug.


https://www.syncfusion.com/feedback/51067/invalid-font-name-error-occurs-when-extracting-text-from-specific-pdf-document


Disclaimer: “Inclusion of this solution in the weekly release may change due to other factors including but not limited to QA checks and works reprioritization.”

**Comment by jeyalakshmit** [comment] 2024-02-27 13:40
The fix for the reported issue is included in our weekly release v24.2.8.
 
Root cause: The standard font name encoding was not properly identified in our font structure, causing the "Invalid font name" exception.
 
Kindly use the following link to refer to our latest release version,
https://pub.dev/packages/syncfusion_flutter_pdf/versions

**Closed** 2024-03-22 08:55 UTC
Labels: bug, pdf, waiting for customer
