### ISSUE TITLE
SfPdfViewer take long time to load pdf page when using the single page layout mode

### ISSUE THREAD

**Issue by ahmadzakariamediaplus** [syncfusion/flutter-widgets#593] opened 2022-02-21 09:05 UTC
Hello,

Thanks for providing us with the SfPdfViewer package.

I am currently facing an issue with my flutter project, when I use the single page layout mode the viewer takes a long time to load the page.

**but when I use the continuous mode all the pages load fast.**

I have loaded the pdf with all ways (assets, network, memory) and the result is the same.

Also, I have tested the PDF Viewer in the Syncfusion Flutter UI Widgets App, the same problem appears, 
the page takes more than 5 seconds to appear and sometimes doesn't appear at all.

Please watch the video to see the problem (at the end).
https://we.tl/t-B0VcIUu1kp

**Comment by deepika134** [comment] 2022-02-22 15:47
Hi ahmadzakariamediaplus,

We are analyzing on the reported query and will update the further details on February 24, 2022.

Regards,
Deepika Ravi

**Comment by deepika134** [comment] 2022-02-25 05:16
Hi ahmadzakariamediaplus,

On further analysis, we found that the page was getting properly from the plugin but sometimes the page is not updated in the SfPdfViewer widget. We are still analyzing on this and will update the further details on March 1, 2022.

Regards,
Deepika Ravi

**Comment by deepika134** [comment] 2022-03-01 15:41
Hi ahmadzakariamediaplus,

On further analyzing, we found that issue is reproduced randomly and suspect due to the flutter plugin. We are still analyzing on this and share further details by 3 March 2022

Regards,
Deepika Ravi

**Comment by deepika134** [comment] 2022-03-03 14:20
Hi ahmadzakariamediaplus,

We have confirmed that the reported issue "When scrolling a PDF in a single-page layout, the page is not updated properly in SfPdfViewer” is a defect. The issue fix will be included in our upcoming weekly release, which is estimated to be available on 08 March 2021. 
The status of this issue can be tracked using the following link, https://www.syncfusion.com/feedback/32260/unexpected-closure-of-the-app-when-zooming-and-scrolling-the-pdf-continuously 

Regards,
Deepika Ravi

**Comment by ahmadzakariamediaplus** [comment] 2022-03-03 14:22
> Hi ahmadzakariamediaplus,
> 
> We have confirmed that the reported issue "When scrolling a PDF in a single-page layout, the page is not updated properly in SfPdfViewer” is a defect. The issue fix will be included in our upcoming weekly release, which is estimated to be available on 08 March 2021. The status of this issue can be tracked using the following link, https://www.syncfusion.com/feedback/32260/unexpected-closure-of-the-app-when-zooming-and-scrolling-the-pdf-continuously
> 
> Regards, Deepika Ravi

Great

**Comment by deepika134** [comment] 2022-03-09 04:17
Hi @ahmadzakariamediaplus ,

We have included the fix for this issue "When scrolling a PDF in a single-page layout, the page is not updated properly in SfPdfViewer" in our latest weekly NuGet release, so kindly upgrade to the latest version v19.4.55 to get the issue resolved.
https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.4.55-beta

Regards,
Deepika Ravi

**Closed** 2022-03-30 05:18 UTC

**Comment by imatictz** [comment] 2022-03-30 12:24
Hi,
I am using the latest version (19.4.56-beta) and I am still facing this issue.
