### ISSUE TITLE
PDF Issue

### ISSUE THREAD

**Issue by vinaysiddhapura** [syncfusion/flutter-widgets#2003] opened 2024-08-03 19:14 UTC
### Bug description

PDF does not load in release mode Android or iOS application.

### Steps to reproduce

1. Just try to load the PDF from the network.
2. Run the application in release mode.
3. Scree will remain same. No PDF will be loaded.

### Code sample

<details open><summary>Code sample</summary>

```dart
Container(
      color: Colors.white,
      child: SfPdfViewer.network(
        widget.invoiceUrl,
        pageSpacing: 0,
        pageLayoutMode: PdfPageLayoutMode.single,
      ))
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
![WhatsApp Image 2024-08-03 at 09 58 31](https://github.com/user-attachments/assets/46580533-8c9a-4016-93ea-5e0df65153a2)

```

</details>

### On which target platforms have you observed this bug?

Android, iOS

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
flutter doctor -v
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.6 23G80 darwin-arm64, locale en-IN)
    • Flutter version 3.22.2 on channel stable at /Users/vinaysiddhapura/Desktop/VSWorkspace/SDK/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (8 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/vinaysiddhapura/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 14 (API 34) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.6 23G80 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.6 23G80 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 127.0.6533.89

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by immankumarsync** [comment] 2024-08-05 09:28
Hi @vinaysiddhapura,
We are unable to replicate the reported issue and the PDF document from the network is loaded in the SfPdfViewer widget in release mode. We have checked with this document URL, https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf

In Android, ensure that the network permission is enabled for release mode. You may need to add the following code in _android\app\src\main\AndroidManifest.xml_ file.

```xml
<uses-permission android:name="android.permission.INTERNET"/>
```

In iOS, no extra setup is needed to load PDF documents from the network.

If the issue still occurs even after enabling necessary permission, it may be due to the document from the URL might be inaccessible. Kindly check whether the document link opens without any issue by pasting the URL on the address bar of any browsers. If the document loads properly and if you believe that the issue happens only with SfPdfViewer widget, kindly share us the link so that we can analyze the cause of the issue.

**Comment by Deepak1799** [comment] 2024-08-27 12:41
@vinaysiddhapura  We are closing this issue since we do not have enough information to proceed further. You can reopen this anytime and share the requested details to proceed further.

**Closed by Deepak1799** 2024-08-27 12:41 UTC
Labels: pdf viewer, waiting for customer response
