### ISSUE TITLE
SplineAreaSeries在数据全为负数且相等的情况下，无法绘制

### ISSUE THREAD

**Issue by changleibox** [syncfusion/flutter-widgets#227] opened 2021-05-14 09:29 UTC
hi，我们公司购买了贵公司的syncfusion_flutter_charts组件库，但是我们在使用SplineAreaSeries的时候遇到了一个问题，在数据全为负数的情况下，纵轴的Intervals错误导致控件无法绘制

## Steps to Reproduce

1. 使用SplineAreaSeries统计图默认配置
2. 纵轴设置为相同值且全部为负数，如：-400
3. 绘制很多网格线，但是没绘制曲线图

**Expected results:** 
正常绘制曲线图

**Actual results:** 
绘制很多网格线，但是没绘制曲线图

![image](https://user-images.githubusercontent.com/26690041/118251240-e5b9e400-b4d9-11eb-8075-70d4c43beae1.png)

<details>
  <summary>Logs</summary>

```
[   +4 ms] executing: xcrun simctl launch 4426631E-8A73-4437-B294-726346BC4442 me.box.app.flutterCharts --enable-dart-profiling --enable-checked-mode --verify-entry-points
--observatory-port=0
[ +413 ms] me.box.app.flutterCharts: 18736
[  +21 ms] Waiting for observatory port to be available...
[ +533 ms] Observatory URL on device: http://127.0.0.1:57444/rp8NPFpCEtc=/
[   +8 ms] Caching compiled dill
[ +136 ms] Connecting to service protocol: http://127.0.0.1:57444/rp8NPFpCEtc=/
[ +242 ms] Launching a Dart Developer Service (DDS) instance at http://127.0.0.1:0, connecting to VM service at http://127.0.0.1:57444/rp8NPFpCEtc=/.
[  +95 ms] DDS is listening at http://127.0.0.1:57447/PoXk5ojeBY0=/.
[  +75 ms] Successfully connected to service protocol: http://127.0.0.1:57444/rp8NPFpCEtc=/
[  +20 ms] DevFS: Creating new filesystem on the device (null)
[  +16 ms] DevFS: Created new filesystem on the device
(file:///Users/box/Library/Developer/CoreSimulator/Devices/4426631E-8A73-4437-B294-726346BC4442/data/Containers/Data/Application/C92788A5-B353-4729-B6C4-133844E923EF/tmp/f
lutter_chartsPWkb8o/flutter_charts/)
[   +2 ms] Updating assets
[  +97 ms] Syncing files to device iPhone 12 Pro Max...
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +4 ms] <- recompile package:flutter_charts/main.dart eea0ee88-1403-4ee8-b2ca-51650349980b
[        ] <- eea0ee88-1403-4ee8-b2ca-51650349980b
[ +144 ms] Updating files.
[        ] DevFS: Sync finished
[   +2 ms] Syncing files to device iPhone 12 Pro Max... (completed in 153ms)
[   +1 ms] Synced 0.0MB.
[   +2 ms] <- accept
[   +9 ms] Connected to _flutterView/0x7fa3cc81a620.
[   +3 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
[   +2 ms] An Observatory debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:57447/PoXk5ojeBY0=/
[ +731 ms] The Flutter DevTools debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:9102?uri=http%3A%2F%2F127.0.0.1%3A57447%2FPoXk5ojeBY0%3D%2F
```

```
Analyzing flutter_charts...                                             
No issues found! (ran in 1.8s)
```

```
[✓] Flutter (Channel master, 2.2.0-11.0.pre.152, on macOS 11.3.1 20E241 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.2.0-11.0.pre.152 at /Users/box/Downloads/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f4c74a6ec3 (4 weeks ago), 2021-04-16 20:34:01 -0400
    • Engine revision e3832e14b4
    • Dart version 2.14.0 (build 2.14.0-8.0.dev)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

```yml
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flatterer:
    git: https://github.com/changleibox/flatterer.git
  syncfusion_flutter_charts: ^19.1.59
  intl: ^0.17.0
```

</details>

<details>
  <summary>Codes</summary>

```dart
class ChartsBugPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('ChartsBug'),
      ),
      body: SfCartesianChart(
        legend: Legend(isVisible: true),
        primaryXAxis: CategoryAxis(),
        primaryYAxis: NumericAxis(),
        series: [
          SplineAreaSeries<MapEntry<String, num>, String>(
            dataSource: List.generate(10, (index) {
              final dateTime = DateTime(2021, 1, 1).add(Duration(days: index));
              return MapEntry<String, num>(
                DateFormat('yyyy年MM月dd日').format(dateTime),
                -400,
              );
            }),
            xValueMapper: (datum, index) => datum.key,
            yValueMapper: (datum, index) => datum.value,
          ),
        ],
      ),
    );
  }
}
```

</details>

**Comment by Dharanipalani** [comment] 2021-05-17 07:27
Hii @changleibox,

Thank you for the interest in our Flutter charts. We have investigated your query and can tell you that the chart is rendering properly, and based on your screenshot, we found that the range is not in between the given data source. As a result, the chart is not visible to us. Your problem will be solved if you use the minimum and maximum values properly by considering the data source or remove the specified range. We also like to tell you that the chart calculates range and renders the chart automatically by default. For more gridlines issue, you can change the interval property on the corresponding axis as desired and refer to the help documents below for further information.

[https://help.syncfusion.com/flutter/cartesian-charts/axis-types#customizing-range](https://help.syncfusion.com/flutter/cartesian-charts/axis-types#customizing-range)
[https://help.syncfusion.com/flutter/cartesian-charts/axis-types#date-time-intervals](https://help.syncfusion.com/flutter/cartesian-charts/axis-types#date-time-intervals)
[https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#grid-lines-customization](https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#grid-lines-customization)

Thanks,
Dharanitharan. P

**Comment by changleibox** [comment] 2021-05-17 13:04
> Hi @changleibox,
> 
> Thank you for the interest in our Flutter charts. We have investigated your query and can tell you that the chart is rendering properly, and based on your screenshot, we found that the range is not in between the given data source. As a result, the chart is not visible to us. Your problem will be solved if you use the minimum and maximum values properly by considering the data source or remove the specified range. We also like to tell you that the chart calculates range and renders the chart automatically by default. For more gridlines issue, you can change the interval property on the corresponding axis as desired and refer to the help documents below for further information.
> 
> https://help.syncfusion.com/flutter/cartesian-charts/axis-types#customizing-range
> https://help.syncfusion.com/flutter/cartesian-charts/axis-types#date-time-intervals
> https://help.syncfusion.com/flutter/cartesian-charts/axis-customization#grid-lines-customization
> 
> Thanks,
> Dharanitharan. P

你好，感谢你的回答，但是在我的代码里，我没有设置它的range，麻烦再帮我看看

**Comment by SriramKiranSenthilkumar** [comment] 2021-05-18 14:29
Hi @changleibox,

We have analyzed your scenario with the provided sample and on running the sample, we found that the chart is render properly as per the provided data in your code snippet like in the below screenshot. 

![image](https://user-images.githubusercontent.com/63577117/118669400-55e6a380-b813-11eb-8f25-aca66944654f.png)

 
In the above screenshot, you can see that the chart is rendered straightly along y-axis because, you have provided -400 as y-value for all the data points. We have also attached the test sample below for your reference and since we are not sure on what scenario the reported bug can be reproduced, we kindly request you to replicate the reported issues in the below attached sample and revert us with it so that it will be helpful in providing the solutions sooner.

Sample: [ghfw227_splineareaseries.zip](https://github.com/syncfusion/flutter-widgets/files/6502065/ghfw227_splineareaseries.zip)


Regards.
Sriram Kiran

**Comment by changleibox** [comment] 2021-05-19 04:55
> Hi @changleibox,
> 
> We have analyzed your scenario with the provided sample and on running the sample, we found that the chart is render properly as per the provided data in your code snippet like in the below screenshot.
> 
> ![image](https://user-images.githubusercontent.com/63577117/118669400-55e6a380-b813-11eb-8f25-aca66944654f.png)
> 
> In the above screenshot, you can see that the chart is rendered straightly along y-axis because, you have provided -400 as y-value for all the data points. We have also attached the test sample below for your reference and since we are not sure on what scenario the reported bug can be reproduced, we kindly request you to replicate the reported issues in the below attached sample and revert us with it so that it will be helpful in providing the solutions sooner.
> 
> Sample: [ghfw227_splineareaseries.zip](https://github.com/syncfusion/flutter-widgets/files/6502065/ghfw227_splineareaseries.zip)
> 
> Regards.
> Sriram Kiran

你好，非常感谢你提供的解决方式，但是看你的截图，也是有问题，网格线绘制的非常密集，说明interval计算失败了
你可以把值设置为-4000，看看能不能绘制出来

**Comment by dharanidharandharmasivam** [comment] 2021-05-19 09:24
Hi @changleibox ,

We would like to let you know that the intervals will be calculated based on the size of the axis and data points. Since you have specified y value as -4000, based on the size of the axis, the intervals are calculated and due to this gridlines are seems to be densely rendered. To avoid this, you use the **[interval](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/interval.html)** property of the axis. 

`primaryYAxis: NumericAxis(
  interval: 10
  ),`

<img width="288" alt="Screenshot 2021-05-19 at 2 53 45 PM" src="https://user-images.githubusercontent.com/19346074/118789119-1327d880-b8b2-11eb-888b-09d4fbe7af81.png">

Thanks,
Dharani.

**Comment by changleibox** [comment] 2021-05-19 13:33
> Hi @changleibox ,
> 
> We would like to let you know that the intervals will be calculated based on the size of the axis and data points. Since you have specified y value as -4000, based on the size of the axis, the intervals are calculated and due to this gridlines are seems to be densely rendered. To avoid this, you use the **[interval](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/interval.html)** property of the axis.
> 
> `primaryYAxis: NumericAxis( interval: 10 ),`
> 
> <img alt="Screenshot 2021-05-19 at 2 53 45 PM" width="288" src="https://user-images.githubusercontent.com/19346074/118789119-1327d880-b8b2-11eb-888b-09d4fbe7af81.png">
> 
> Thanks,
> Dharani.

谢谢你的回复，手动设置interval属性是没有问题的，但是不设置自动计算的时候，是有问题的，目前这个问题可以通过手动设置interval或者手动设置最大值和最小值解决的

**Comment by Dharanipalani** [comment] 2021-05-26 06:58
Hi @changleibox,

We are happy to inform you that the reported issue is fixed in the latest version of our charts and now the auto interval calculation with the same negative values is calculated properly, to resolve this kindly upgrade to the latest version from the below link.

**Latest version**: [https://pub.dev/packages/syncfusion_flutter_charts/versions/19.1.65](https://pub.dev/packages/syncfusion_flutter_charts/versions/19.1.65)

Thanks,
Dharanitharan. P

**Closed** 2021-05-27 05:27 UTC
