### ISSUE TITLE
[syncfusion_flutter_datagrid] Checkboxes glitching while scrolling

### ISSUE THREAD

**Issue by squaregen** [syncfusion/flutter-widgets#599] opened 2022-02-22 21:57 UTC
Hi,
when i use `showCheckboxColumn: true` i get the problem described in https://github.com/syncfusion/flutter-widgets/issues/149 but the proposed solution is no longer feasible

and rowCacheExtent seems not resolve the problem. Sometimes it doesn't work, also setting rowCacheExtent equal to the size of the rows. https://help.syncfusion.com/flutter/datagrid/scrolling#increase-row-cache-limit

Try changing this example https://flutter.syncfusion.com/#/datagrid/selection/checkbox-selection by adding `rowCacheExtent: 100` and then scrolling the datagrid up and down
Where am I wrong?

Changing the GridCheckboxRenderer by adding a key to the Checkbox Widget would seem to fix the problem.

```dart
class GridCheckboxRenderer
    extends GridVirtualizingCellRendererBase<Widget, Widget> {
  @override
  void onInitializeDisplayWidget(DataCellBase dataCell) {
    final DataGridConfiguration dataGridConfiguration = _dataGridStateDetails();
    if (dataCell.columnIndex < 0 || dataCell.rowIndex < 0) {
      return;
    }

    final bool selectionState = dataCell.dataRow!.isSelectedRow;

    dataCell.columnElement = GridCell(
        key: dataCell.key!,
        dataCell: dataCell,
        backgroundColor:
            dataGridConfiguration.checkboxColumnSettings.backgroundColor ??
                Colors.transparent,
        isDirty: dataGridConfiguration.container.isDirty ||
            dataCell.isDirty ||
            dataCell.dataRow!.isDirty,
        dataGridStateDetails: _dataGridStateDetails,
        child: Checkbox(
          key: ValueKey(dataCell.rowIndex),
            value: selectionState,
            onChanged: (bool? newValue) {
              selection_manager.handleSelectionFromCheckbox(
                  dataGridConfiguration, dataCell, selectionState, newValue);
            }));
  }
}
```

**Comment by Tamilarasan-Paranthaman** [comment] 2022-02-23 14:49
Hi @squaregen,

Currently, we are analysing your reported issue with the "Checkbox column." We will validate and update you with the details in two business days, i.e., February 25, 2022. We appreciate your patience until then.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment] 2022-02-25 12:48
Hi @squaregen,

Sorry for the inconvenience.  

Due to some technical difficulties, we were unable to validate and update further details on this. We will validate and update you with the details in two business days, i.e., March 1, 2022. We appreciate your patience until then.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment] 2022-03-01 11:28
Hi @squaregen,

We could be able to reproduce your reported issue by following the below steps,

- Scrolling rows vertically from start to end

- Tap on the header check box to select all the rows, then tap on the header to deselect.

- Now, Select only the rows in view 

- Scroll the DataGrid vertically, now the issue is reproduced


https://user-images.githubusercontent.com/93904422/156160627-f20750d4-c95e-4e64-8dc9-e19e7c0b8789.mp4



Could you please confirm that this is the same use case that you're having trouble with? If not, please provide more details about your use case. It will also assist us in ensuring that case, after which we will proceed with further steps.

Also, please confirm. We have planned to fix the issue with the **rowCacheExtent** property. I hope this will be suitable for you. Otherwise, do you expect us to include the key property setting in the checkbox?

Regards,
Tamilarasan

**Comment by squaregen** [comment] 2022-03-01 13:48
Hi @Tamilarasan-Paranthaman, thanks for the reply.

 > Could you please confirm that this is the same use case that you're having trouble with? If not, please provide more details about your use case. It will also assist us in ensuring that case, after which we will proceed with further steps.

Yes, the one shown in the video is the problem I encountered. 
 
> Also, please confirm. We have planned to fix the issue with the **rowCacheExtent** property. I hope this will be suitable for you. Otherwise, do you expect us to include the key property setting in the checkbox?

Couldn't both of these be done? 😁 

I proposed adding the key in CheckBox because it allows you to solve the problem of the Checkbox animation without using **rowCacheExtent**.

On the other hand **rowCacheExtent** can be useful for other types of custom columns (such as if you are using CircleAvatar to display an image), so the fix is ​​welcome.

Thanks for the great job you are doing

**Comment by Tamilarasan-Paranthaman** [comment] 2022-03-02 14:52
Hi @squaregen,

Thanks for your update 

We will share the further details by tomorrow (March 3, 2021). We appreciate your patience until then. 

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment] 2022-03-16 05:20
Hi @squaregen,

Sorry for the inconvenience.

Due to some technical difficulties, we could not include the checkbox issue fix in this weekly pub release. We have fixed that issue and it’s in the testing phase. Once the testing is finished, we will include the changes in our weekly pub release which is scheduled to be rolled out on March 29, 2022. We will let you know once it is published. We appreciate your patience until then.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment] 2022-03-29 12:47
Hi @squaregen,

We would like to let you know that because of our 2022 volume 1 main release this week, we will not have a pub release for this week. The fix for the reported issue with the **rowCacheExtent** property will be included in our next weekly pub release. We will let you know once it's rolled out. We appreciate your patience and understanding till then.

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment] 2022-04-13 04:38
Hi @squaregen,

Thank you for your patience.
 
We are glad to inform you that the fix has been included in our weekly pub release. Please update DataGrid package to **20.1.48** version.

Please let us know if you need further assistance on this.

Regards,  
Tamilarasan

**Closed** 2022-05-04 05:54 UTC
