### ISSUE TITLE
zoomMode: ZoomMode.xy in stacked coloumn chart 

### ISSUE THREAD

**Issue by FabioNieVec** [syncfusion/flutter-widgets#1813] opened 2024-04-17 13:54 UTC
### Bug description

If I zoom in with zoomMode: ZoomMode.xy, in a Stacked column chart. The chart will only show me the stack that is the highest and also the color. It also happens if you move above the 0 y point

### Steps to reproduce

1. Zoom the chart in with y > 0, x can be anything
2. if you move the chart 0 y = 0 than you can the all stacks 
3. if you move up they will disappear

### Code sample

<details open><summary>Code sample</summary>

```dart
SfCartesianChart(
                          legend: const Legend(
                              isVisible: true,
                              position: LegendPosition.bottom,
                              overflowMode: LegendItemOverflowMode.wrap),
                          primaryXAxis: CategoryAxis(),
                          zoomPanBehavior:  ZoomPanBehavior(
                              enablePanning: true,
                              zoomMode: ZoomMode.xy,
                              enableSelectionZooming: true),
                          series: <CartesianSeries>[
                            StackedColumnSeries<ChartData1, String>(
                                dataSource: chartData,
                                xValueMapper: (ChartData1 data, _) => data.x,
                                yValueMapper: (ChartData1 data, _) => data.y1
                            ),
                            StackedColumnSeries<ChartData1, String>(
                                dataSource: chartData,
                                xValueMapper: (ChartData1 data, _) => data.x,
                                yValueMapper: (ChartData1 data, _) => data.y2
                            ),
                            StackedColumnSeries<ChartData1,String>(
                                dataSource: chartData,
                                xValueMapper: (ChartData1 data, _) => data.x,
                                yValueMapper: (ChartData1 data, _) => data.y3
                            ),
                            StackedColumnSeries<ChartData1, String>(
                                dataSource: chartData,
                                xValueMapper: (ChartData1 data, _) => data.x,
                                yValueMapper: (ChartData1 data, _) => data.y4
                            )
                          ]
                      )
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

https://github.com/syncfusion/flutter-widgets/assets/32736671/1590e77f-169a-4c46-b043-21dc1db5e411

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

no stack trace
</details>

### On which target platforms have you observed this bug?

Web

### Flutter Doctor output

<details open><summary>Doctor output</summary>

not needed

</details>

**Comment by LokeshPalani** [comment] 2024-04-18 11:26
Hi @FabioNieVec,

We have reproduced the issue you reported regarding **‘StackedColumnSeries not rendered after selection zooming’** on our end and the issue is scheduled to be fixed in our upcoming weekly patch release on **April 30, 2024**. We will notify you here once the release has been rolled out, and we appreciate your patience in the meantime.

Regards,
Lokesh P.

**Comment by Trung15010802** [comment] 2024-04-27 04:13
The same error with ZoomMode.y. Using mouse wheel

**Closed** 2024-05-15 04:48 UTC
Labels: bug, charts, fixed
