### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Scroll fling is jerky and skips multiple pages

### ISSUE THREAD

**Issue by sagarkardani** [syncfusion/flutter-widgets#820] opened 2022-07-15 11:32 UTC
syncfusion_flutter_pdfviewer: 20.2.38-beta

also filed [here](https://github.com/syncfusion/flutter-widgets/issues/809) 20.2.36-beta

### Issue
1. **document is not zoomed** - doing a scroll fling gives jerky scroll / flickers the page without appropriate scrolling animation. Doing a large scroll fling directly skips multiple pages.

2. **document is zoomed** - scroll fling works as expected.

https://user-images.githubusercontent.com/60609139/176886791-3f781a15-5bae-4ab4-b2d0-6bf4994f49bc.mp4

Regards
Sagar

**Comment by sagarkardani** [comment] 2022-07-23 02:42
Why this issue is not being attended ??

**Comment by therealjohnsummer** [comment] 2022-07-24 11:44
I have exactly the same issue - I stopped using SfPdfViewer from 20.1.55-beta because of  the poor performance with respect to fling gestures and the obscene amount of memory that is consumed when using this component. I was hoping that 20.2.39-beta would fix many of the issues with this component.

Unfortunately, it does not. The latest version is only faster when you do a very quick swipe up or down, i.e if you have say 100-page pdf document and then swipe down and take your finger off the device - you roughly jump 33% of the entire document - This is far too much and **we should be able to control or customise how much of a document should be paged when a user a fling gesture**

Additionally - just simply adding a very light downward gesture on the document scrolls to an entirely new page and the animation is horribly jerky and jagged - **if you pinch to zoom and then repeat the downward or upward fling gesture - the animation is perfect and smooth**

For the SfPdfViewer to be usable in a production environment we really need the memory consumption bug to be resolved and also fast efficient smooth scrolling (supporting fling & swipe gestures) on a PDF document to be implemented once and for all rather than incremental fixes that when tested reveal further problems.

**Comment by sagarkardani** [comment] 2022-07-24 13:14
> If you pinch to zoom and then repeat the downward or upward fling gesture - the animation is perfect and smooth

Yes, If zoomlevel is not 1.0 then it is working normally. Ofcourse it is very slow but it is atleast usable.

**Comment by therealjohnsummer** [comment] 2022-07-24 13:51
@sagarkardani If you just require a simple working PDF Viewer that is memory performant and fast with respect to swipe/fling gestures - look at : 

flutter_pdfview: ^1.2.2

I just installed this and got it up and running within 5 mins - works perfectly ... Not jerky , pinch to zoom and fling gestures work perfectly and the memory footprint is much much less than SfPdfViewer. It doesnt have search/bookmarks etc but you can jump to page via a controller ....  This might be a good alternative to SfPdfViewer but obviously depending on your requirements ....

**Comment by deepika134** [comment] 2022-07-27 15:36
Hi @sagarkardani ,

Sorry for the inconvenience.

Kindly confirm us, if you are reported this issue , when scrolling in a non-zoomed document, the scroll end page displays directly without displaying the middle pages in document. We are validating on this and will update the details on August 1,2022.

Regards.
Deepika R

**Comment by sagarkardani** [comment] 2022-07-27 15:52
Hi @deepika134 

Yes, when the scrolling ends, scroll end page is displayed correctly without animating pages in between. If you are asking for very last page of the document, it is also showing correctly.

**Comment by deepika134** [comment] 2022-07-29 06:55
Hi @sagarkardani,

Thank you for the details. As we mentioned earlier, we are checking on this and will update the further details on Augest 1, 2022.

Regards,
Deepika R

**Comment by CuongNV12** [comment] 2022-07-29 07:38
i'm using `initialZoomLevel: 1.001,` to temporary fix

**Comment by deepika134** [comment] 2022-08-04 17:50
Hi @sagarkardani ,

We confirmed that the issue with "Scroll fling skips multiple pages without appropriate scrolling animation" is a defect. The issue fix will be included in our August 3rd weekly package release which is estimated to be available on 16 August 2022.

The status of this issue can be tracked using following link. 
https://www.syncfusion.com/feedback/36835/scroll-fling-skips-multiple-pages-without-appropriate-scrolling-animation

Regards, 
Deepika R

**Comment by vishalpatel1327** [comment] 2022-08-08 17:02
having the same kind of issue
1. Big pdf cant be scroll smooth white page issue delayed loading,i have around 23 MB file, with 24 pages
2. even though I had compressed it to 2 MB still result was same, when I scroll all the pages jerked and display a white blank page
3. even scroll 5-10 pages very quickly.

otherwise library is great.

**Comment by deepika134** [comment] 2022-08-17 03:39
Hi Everyone,

We have included the fix for the issue “Scroll fling skips multiple pages without appropriate scrolling animation” in our latest weekly release, so kindly upgrade to the latest version (20.2.44-beta) to get the issue resolved.

Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/20.2.44-beta

Regards,
Deepika Ravi

**Closed** 2022-08-28 17:28 UTC
