### ISSUE TITLE
[syncfusion_flutter_charts]: DateTimeAxis not displaying expected date at the start of each interval, and missing x-axis labels for some years

### ISSUE THREAD

**Issue by sachin-dahal** [syncfusion/flutter-widgets#2107] opened 2024-10-01 10:05 UTC
I am using the DateTimeAxis with DateTimeIntervalType.years to display date values on the x-axis. However, I am facing two issues:

The x-axis does not display the date at the beginning of the interval as expected.
Even though the dataset contains dates from 2023, 2024, and 2025, only two x-axis labels are being displayed for the years, and some are missing (for example, the year 2025).

Here is my current configuration:
```dart
primaryXAxis: DateTimeAxis(
  intervalType: DateTimeIntervalType.years,
  labelStyle: TextStyle(
    color: Colors.grey[500],
    fontSize: widget.axisFontSize,
    fontWeight: FontWeight.w600,
  ),
  majorGridLines: const MajorGridLines(width: 0),
  majorTickLines: const MajorTickLines(size: 0),
), 
```

data passed:
```dart
[
  '2023-10-01',
  '2023-11-01',
  '2023-12-01',
  '2024-01-01',
  '2024-02-01',
  '2024-03-01',
  '2024-04-01',
  '2024-05-01',
  '2024-06-01',
  '2024-07-01',
  '2024-08-01',
  '2024-09-01',
  '2024-10-01',
  '2025-01-01',
  '2025-02-11',
  '2025-03-05',
]
```

### Issues
- Date Interval Start Issue: I expect the x-axis to display the date value at the beginning of each interval (e.g., 2023-01-01, 2024-01-01, 2025-01-01), but it is not happening.
- Missing Years on X-Axis: Only two years are being displayed even though the dataset contains data for three years (2023, 2024, 2025). The year 2025 is missing on the x-axis even though dates for 2025 are present. (Also if it's about the chart should consist a data for those dates too in order to display then Yes, there are data for these date values too, but still, it's missing in the x-axis)

### Questions:
- Is there any property or value that I can adjust to align the x-axis interval text properly and ensure that all the relevant years (2023, 2024, 2025) are displayed?

Any suggestions or fixes would be greatly appreciated. Thank you!

### Current:
<img width="600" alt="Screenshot 2024-10-01 at 15 14 43" src="https://github.com/user-attachments/assets/135f04c5-dce0-4938-ab19-fdd1b80e3412">

### Expected:
<img width="600" alt="Screenshot 2024-10-01 at 15 10 59" src="https://github.com/user-attachments/assets/0642b34b-60ca-43aa-b46d-b937e0835c74">

**Comment by Mugunthan-Ramalingam** [comment] 2024-10-18 13:45
Hi @sachin-dahal,

We have analyzed your query, and we would like to inform you that this is not an issue; it is the expected behavior of the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html). We also verified this behavior with Microsoft Excel charts, which exhibit the same axis label rendering as the [SfCartesianChart](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart-class.html).

 

When using [DateTimeAixs](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis-class.html)  with an [intervalType](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeAxis/intervalType.html)  of [DateTimeIntervalType.years](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeIntervalType.html), the interval is set to one year based on the data source you provided, and the axis labels are calculated accordingly. The first data point's date is 2023/10/01, so the first label is 2023. The next label, 2024, is calculated to be one year later, on 2024/10/01. Following this pattern, the next label, 2025, would be rendered on 2025/10/01. However, since there is no data available up to 2025/10/01 in the data source, the 2025 label is not displayed on the axis.

 
You can achieve the desired UI by using [DateTimeCategoryAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/DateTimeCategoryAxis-class.html)  for the [primaryXAxis](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/SfCartesianChart/primaryXAxis.html)  and utilizing [axisLabelFormatter](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/ChartAxis/axisLabelFormatter.html) to modify the x-axis labels. We have rendered the 3 labels and sets empty string for other labels as per the below code snippet.
 
 
Code snippet:
```
SfCartesianChart(
   primaryXAxis: DateTimeCategoryAxis(
     majorGridLines: const MajorGridLines(width: 0),
     majorTickLines: const MajorTickLines(size: 0),
     axisLabelFormatter: (AxisLabelRenderDetails args) {
       String text = args.text;
       if (text == '2023 Oct' ||
           text == '2024 Jan' ||
           text == '2025 Jan') {
         text = text.split(' ')[0];
         return ChartAxisLabel(text, args.textStyle);
        }
        return ChartAxisLabel('', args.textStyle);
    },
 ) ...
```
Screenshot: 

 ![Screenshot 2024-10-18 181534](https://github.com/user-attachments/assets/f9e899cb-4bf4-41a1-87b7-88e0e6d1a03c)

For more details refer the following UG: https://help.syncfusion.com/flutter/cartesian-charts/axis-types#date-time-category-axis

And also, we have attached sample for your reference, modify it based on your requirement.

Sample: [gh_2107.zip](https://github.com/user-attachments/files/17436385/gh_2107.zip)



Regards,
Mugunthan.

**Comment by sachin-dahal** [comment] 2024-10-21 13:59
Thanks for the help @Mugunthan-Ramalingam !
Appreciate that! 🙌

**Comment by LavanyaGowtham2021** [comment] 2024-10-23 10:37
Most Welcome. We are always happy to assist you. We are closing this ticket, please open if you need further assistance on this.

**Closed by LavanyaGowtham2021** 2024-10-23 10:37 UTC
Labels: charts, waiting for customer response
