### ISSUE TITLE
[syncfusion_flutter_datagrid] custom key event handler doesn't raise onSelectionChanged event

### ISSUE THREAD

**Issue by dolbin-prime** [syncfusion/flutter-widgets#2100] opened 2024-09-29 14:39 UTC
### Bug description

In my overridden `handleKeyEvent` method in my `RowSelectionManager`, `selectedRows` is set to empty list when `escape` key is pressed. But it doesn't cause `SfDataGrid` to raise any `onSelectionChanged` event, which is weird that `onSelectionChanged` events are raised normally when I press `ctrl` + `A` keys . So I tried to inject `DataGridSource` into my `RowSelectionManager` and called `notifyListerners` of it, but it had no effect.

### Steps to reproduce

I pasted my code to reproduce the issue.

### Code sample

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'package:syncfusion_flutter_datagrid/datagrid.dart';

class Employee {
  Employee(this.id, this.name, this.designation, this.salary);
  final int id;
  final String name;
  final String designation;
  final int salary;
}

final employees = [
  Employee(10001, 'James', 'Project Lead', 20000),
  Employee(10002, 'Kathryn', 'Manager', 30000),
  Employee(10003, 'Lara', 'Developer', 15000),
  Employee(10004, 'Michael', 'Designer', 15000),
  Employee(10005, 'Martin', 'Developer', 15000),
  Employee(10006, 'Newberry', 'Developer', 15000),
  Employee(10007, 'Balnc', 'Developer', 15000),
  Employee(10008, 'Perry', 'Developer', 15000),
  Employee(10009, 'Gable', 'Developer', 15000),
  Employee(10010, 'Grimes', 'Developer', 15000)
];

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(
        body: MyDataGrid(),
      ),
    );
  }
}

class MyDataGrid extends StatefulWidget {
  const MyDataGrid({super.key});

  @override
  State<MyDataGrid> createState() => _MyDataGridState();
}

class _MyDataGridState extends State<MyDataGrid> {
  late EmployeeDataSource _employeeDataSource;
  late DataGridController _dataGridController;
  late MySelectionManager _selectionManager;

  @override
  void initState() {
    _employeeDataSource = EmployeeDataSource(employeeData: employees);
    _dataGridController =
        DataGridController(selectedRows: _employeeDataSource.rows);
    _selectionManager = MySelectionManager(
        gridController: _dataGridController, dataSource: _employeeDataSource);
    super.initState();
  }

  @override
  void dispose() {
    _employeeDataSource.dispose();
    _dataGridController.dispose();
    _selectionManager.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SfDataGrid(
        source: _employeeDataSource,
        controller: _dataGridController,
        selectionManager: _selectionManager,
        showCheckboxColumn: true,
        selectionMode: SelectionMode.multiple,
        onSelectionChanged: (addedRows, removedRows) =>
            debugPrint('Selection changed!'),
        columns: <GridColumn>[
          GridColumn(
              columnName: 'id',
              label: Container(
                  padding: const EdgeInsets.all(16.0),
                  alignment: Alignment.center,
                  child: const Text(
                    'ID',
                  ))),
          GridColumn(
              columnName: 'name',
              label: Container(
                  padding: const EdgeInsets.all(8.0),
                  alignment: Alignment.center,
                  child: const Text('Name'))),
          GridColumn(
              columnName: 'designation',
              label: Container(
                  padding: const EdgeInsets.all(8.0),
                  alignment: Alignment.center,
                  child: const Text(
                    'Designation',
                    overflow: TextOverflow.ellipsis,
                  ))),
          GridColumn(
              columnName: 'salary',
              label: Container(
                  padding: const EdgeInsets.all(8.0),
                  alignment: Alignment.center,
                  child: const Text('Salary'))),
        ]);
  }
}

class EmployeeDataSource extends DataGridSource {
  EmployeeDataSource({required List<Employee> employeeData}) {
    _employeeData = employeeData
        .map<DataGridRow>((e) => DataGridRow(cells: [
              DataGridCell<int>(columnName: 'id', value: e.id),
              DataGridCell<String>(columnName: 'name', value: e.name),
              DataGridCell<String>(
                  columnName: 'designation', value: e.designation),
              DataGridCell<int>(columnName: 'salary', value: e.salary),
            ]))
        .toList();
  }

  List<DataGridRow> _employeeData = [];

  @override
  List<DataGridRow> get rows => _employeeData;

  @override
  DataGridRowAdapter buildRow(DataGridRow row) {
    return DataGridRowAdapter(
        cells: row.getCells().map<Widget>((e) {
      return Container(
        alignment: Alignment.center,
        padding: const EdgeInsets.all(8.0),
        child: Text(e.value.toString()),
      );
    }).toList());
  }
}

class MySelectionManager extends RowSelectionManager {
  MySelectionManager({required this.gridController, required this.dataSource});

  final DataGridController gridController;
  final DataGridSource dataSource;

  @override
  Future<void> handleKeyEvent(KeyEvent keyEvent) {
    if (keyEvent.logicalKey == LogicalKeyboardKey.escape) {
      // This successfully clears currently selected rows,
      // but it raises no `onSelectionChanged` event.
      gridController.selectedRows = [];
      dataSource.notifyListeners();
    }

    return super.handleKeyEvent(keyEvent);
  }
}
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>
Here's the flow:

1. I clicked the last row.
3. I pressed `escape`.
4. I pressed `ctrl` + `A`.

https://github.com/user-attachments/assets/36f4ff97-9f8d-484c-b838-c095287f9942

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
[Add the Stack Traces here]
```

</details>

### On which target platforms have you observed this bug?

Windows

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4169], locale ko-KR)
    • Flutter version 3.24.3 on channel stable at C:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/to/windows-android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.9.34723.18
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/windows-android-setup for detailed instructions).

[√] VS Code, 64-bit edition (version 1.93.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.96.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4169]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 129.0.6668.60
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 129.0.2792.52

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by abineshPalanisamy** [comment] 2024-09-30 10:29
Hi @dolbin-prime ,
 
In SfDataGrid, the selection callbacks ([onSelectionChanging](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FSfDataGrid%2FonSelectionChanging.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C9632386ababb44e767b908dce13a7e3a%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638632888533752827%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=GxEHWIsHXArP%2F%2BjfnXOLEPWI54%2FofL%2FwS3YcdpGoaDU%3D&reserved=0) and [onSelectionChanged](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FSfDataGrid%2FonSelectionChanged.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C9632386ababb44e767b908dce13a7e3a%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638632888533766446%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=HvAm63EYqGMqP2Qoq8Kjw7WG4lUmrJCuBsdiACHl9lc%3D&reserved=0)) are triggered by the default interaction and key behavior. Since you are using custom selection logic through [handleKeyEvent](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fdocumentation%2Fsyncfusion_flutter_datagrid%2Flatest%2Fdatagrid%2FRowSelectionManager%2FhandleKeyEvent.html&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C9632386ababb44e767b908dce13a7e3a%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638632888533779962%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=00lirVF7UVZO3F%2ByliE9LWJKGr3SyiJvqky%2FlA9lzAU%3D&reserved=0), you are implementing your own selection process. As a result, the selection callbacks are not called, which is the expected behavior of the DataGrid. For **Ctrl + A**, this is handled by the default behavior on our side, and the key event triggers the selection callbacks. In your case, with custom selection logic, **you should perform your actions directly within handleKeyEvent instead of relying on the selection callbacks.**
 
Regards,
Abinesh P

**Comment by dolbin-prime** [comment] 2024-09-30 10:35
Hi @abineshPalanisamy ,

Thank you for your reply. Is there any plan to support the ability for custom selection logic to invoke selection callbacks?

**Comment by dolbin-prime** [comment] 2024-10-01 01:49
Hi @abineshPalanisamy ,

Thank you for your reply. Is there any plan to support the ability for custom selection logic to invoke selection callbacks?

**Comment by abineshPalanisamy** [comment] 2024-10-04 13:35
Hi @dolbin-prime ,

In the SfDataGrid, all callbacks are triggered only by UI interactions and default key behaviors handled by our source code. You are implementing selection using custom logic added at the sample level. Therefore, you can perform your actions along with the custom logic. We cannot consider this request as a feature
 
Regards,
Abinesh P

**Comment by dolbin-prime** [comment] 2024-10-04 13:39
Hi @abineshPalanisamy, 

I understand. I'll figure it out in other ways. Thank you 😃

**Comment by ashok-kuvaraja** [comment] 2024-10-15 04:16
Hi @dolbin-prime,

We hope you clearly understand the behavior of selection changing and changed callbacks in programmatic and manual operations. Hence, we are closing this issue now. If you need any further assistance, please reopen this. We are always happy to help.

Regards,
Ashok K

**Closed by ashok-kuvaraja** 2024-10-15 04:16 UTC
Labels: data grid, waiting for customer response
