### ISSUE TITLE
syncfusion_flutter_pdfviewer package causing unnecessary widget rebuilding and affecting app performance

### ISSUE THREAD

**Issue by KinjalDhamatBacancy** [syncfusion/flutter-widgets#1094] opened 2023-02-24 06:39 UTC
I have been using the syncfusion_flutter_pdfviewer package in my Flutter application and it has been providing great features for viewing PDF files. However, I have noticed that the package is causing excessive widget rebuilding, even when no actions are performed on the PDF. This is affecting the overall performance of my application and causing the entire UI to rebuild unnecessarily. 

I have attached a short video of the issue using the Flutter Performance tool, which clearly shows the widget rebuilding and frame rendering occurring frequently. 
https://user-images.githubusercontent.com/90254045/221108250-ae663649-1fe7-49a5-9b70-445083d14194.mov

I have tried various methods to improve the performance of my application, but the issue persists. 

**Steps to reproduce:** 
Run the package example provided by syncfusion_flutter_pdfviewer. 
Observe the Flutter Performance tool and note the excessive widget rebuilding and frame rendering. 

**Expected behavior:** 
The syncfusion_flutter_pdfviewer package should not cause widget rebuilding when no actions are performed on the PDF. 

**Actual behavior:** 
The package is causing excessive widget rebuilding, even when no actions are performed on the PDF, which is affecting the performance of application. 

Please let me know if there is any additional information needed to address this issue. Thank you.

**Comment by deepika134** [comment] 2023-02-27 14:10
Hi @KinjalDhamatBacancy , We are able to reproduce the reported issue with the provided details, we are analysing on this and will update the details on 1 March 2023.

**Comment by raaja-guidely** [comment] 2023-03-14 12:43
@KinjalDhamatBacancy @deepika134  me too have rebuild problem because of i'm using darkmode and light mode

 var themeChange = Provider.of<DarkThemeProvider>(context);
          if(theme.toString()!="2"&& theme.toString()!="3") {
            final darkMode = WidgetsBinding.instance.window.platformBrightness;
            if (darkMode == Brightness.dark) {
              themeChange.darkTheme = true;
            }else{
              themeChange.darkTheme = false;
            }
            
            
            with the above code render multiple times

**Comment by deepika134** [comment] 2023-03-14 13:11
Hi @KinjalDhamatBacancy , We have confirmed that the issue “SfPdfViewer causes excessive widget rebuilding even when no actions are performed” is a defect and logged a defect report for this issue. The fix for the same will be included in our 2023 March 28 weekly NuGet release. The status of the issue can be tracked through the following link,

https://www.syncfusion.com/feedback/41665/sfpdfviewer-causes-excessive-widget-rebuilding-even-when-no-actions-are-performed

**Comment by deepika134** [comment] 2023-04-04 14:53
Hi @KinjalDhamatBacancy , The issue "SfPdfViewer causes excessive widget rebuilding even when no actions are performed" has been resolved and the fix is available in the latest weekly (v21.1.38) release. Please find the link below,
https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/21.1.38

**Closed** 2024-02-07 10:40 UTC
Labels: pdf_viewer
