### ISSUE TITLE
syncfusion_flutter_pdfviewer | No results when searching for a phrase containing a hyphen

### ISSUE THREAD

**Issue by Xavier-Claude** [syncfusion/flutter-widgets#2038] opened 2024-08-23 03:06 UTC
### Bug description

I've observed that when using the search feature in PDF for a phrase containing a hyphen, it yields no results. It will find the word before and after the hyphen separately, but not if you include the hyphen. No issues with underscores or other common symbols like commas, periods, brackets (as far as I have tested).

### Steps to reproduce

1. Use PDF viewer to open a PDF of text. Some of the text should contain phrases with a hyphen, such as "test-phrase".
2. Use the search option to search for "test-phrase"
3. No results.

### Code sample

This doesn't seem to be a code issue..

### Screenshots or Video

None.

### Stack Traces

None.

### On which target platforms have you observed this bug?

iOS

### Flutter Doctor output

None.

**Comment by immankumarsync** [comment] 2024-08-23 10:40
@Xavier-Claude, we are able to replicate the reported issue at our end and currently we are validating the issue. We will update further details once the validation is complete.

**Comment by immankumarsync** [comment] 2024-09-19 12:44
We have resolved the issue "searching text with hyphen character provides no results", and the fix for the same is available in the latest [syncfusion_flutter_pdfviewer 27.1.48](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/27.1.48) package.

Root cause: The words containing hyphens are extracted as separate lines from the Syncfusion PDF Library.
e.g.: as-is is extracted 'as', '-', 'is'. Due to this they are considered as separate lines instead of same word.

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

**Comment by Xavier-Claude** [comment] 2024-09-21 15:32
@immankumarsync, thank you - it works great!

**Comment by Deepak1799** [comment] 2024-10-10 09:43
@Xavier-Claude, Thank you for the confirmation. We are closing this as the issue has been resolved.

**Closed by Deepak1799** 2024-10-10 09:43 UTC
Labels: pdf viewer, solved
