### ISSUE TITLE
[web] Grid lines are not rendered during horizontal swipe on chrome and safari.

### ISSUE THREAD

**Issue by lyf571321556** [syncfusion/flutter-widgets#837] opened 2022-07-29 10:28 UTC
flutter doctor:
 flutter doctor -v
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.3.1 21E258 darwin-arm, locale
    zh-Hans-CN)
    • Flutter version 3.0.5 at /Users/ones/Library/flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision f1875d570e (2 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✗] Android toolchain - develop for Android devices
    • Android SDK at /Users/ones/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.

[!] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 69.0.4
    • Dart plugin version 221.6008.15

[✓] Connected device (3 available)
    • 21091116C (mobile) • rcguam4h759pt4jn • android-arm64  • Android 11 (API
      30)
    • macOS (desktop)    • macos            • darwin-arm64   • macOS 12.3.1
      21E258 darwin-arm
    • Chrome (web)       • chrome           • web-javascript • Google Chrome
      103.0.5060.114
    ! Error: Unable to prepare Ha0 for development.  (code -1)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 3 categories.

syncfusion_flutter_datagrid: ^20.2.40

![image](https://user-images.githubusercontent.com/2295872/181739495-2473abf6-b3c2-47cb-bb3d-61b52ab4b1e3.png)

**Comment by lyf571321556** [comment] 2022-07-29 10:39
![image](https://user-images.githubusercontent.com/2295872/181742432-e154b412-3230-4ca0-8731-7951ef75c144.png)

**Comment by lyf571321556** [comment] 2022-07-29 10:42
![image](https://user-images.githubusercontent.com/2295872/181742775-2acd4690-e165-451e-908c-a21acc696579.png)

**Comment by lyf571321556** [comment] 2022-07-29 10:46
official demo has same issue.
![DCIM](https://user-images.githubusercontent.com/2295872/181743458-b8810b63-2b95-46cb-8102-92a2cbf7d586.jpg)
![DCIM](https://user-images.githubusercontent.com/2295872/181743472-48e7895a-04a1-414d-a485-917d5446c147.jpg)

**Comment by lyf571321556** [comment] 2022-07-29 10:48
![IMG_0608](https://user-images.githubusercontent.com/2295872/181743826-49cbbb62-abf0-4213-8f20-be5fa211eb09.PNG)

**Comment by Tamilarasan-Paranthaman** [comment] 2022-08-01 07:50
Hi @lyf571321556,

In the Framework, we have checked a simple sample that contains a SingleChildScrollView with a Container widget (with borders). While doing horizontal scrolling in that sample, the border not drawn properly issue has been reproduced in the mobile web browser.

Also, this issue only occurs while using the HTML rendering since the mobile web browser takes HTML as the default renderer.

We have already reported this issue to the framework. For further details, you can refer to the following link.

GitHub Link:  https://github.com/flutter/flutter/issues/107705  

As of now, you can use the canvaskit renderer until it has been fixed in the framework. For more information, please check the following code snippet and document.

```
flutter build web --web-renderer canvaskit

flutter run -d chrome --web-renderer canvaskit

```
Web Renderers: https://docs.flutter.dev/development/platform-integration/web/renderers 

We hope this helps. Please let us know if you require any further assistance on this. 

Regards,
Tamilarasan

**Closed** 2022-09-02 06:32 UTC
