### ISSUE TITLE
Getting some issue

### ISSUE THREAD

**Issue by vipul8815** [syncfusion/flutter-widgets#1998] opened 2024-07-30 07:35 UTC
### Bug description

Error (Xcode): ../../../.pub-cache/hosted/pub.dev/syncfusion_flutter_core-26.2.7/lib/src/theme/theme_widget.dart:123:47: Error: The getter 'surfaceContainerHighest' isn't defined for the class 'ColorScheme'.

### Steps to reproduce

  use this version and also try with latest version but getting same error
  syncfusion_flutter_datepicker: ^26.1.35

### Code sample

<details open><summary>Code sample</summary>

```dart
 SfDateRangePicker(
                  onSelectionChanged:
                      (DateRangePickerSelectionChangedArgs args) {
                    ref
                        .read(dateSelectPageProvider.notifier)
                        .setDate(args.value);
                  },
                  selectionMode: DateRangePickerSelectionMode.range,
                  initialSelectedRange: PickerDateRange(
                      DateTime.now().subtract(const Duration(days: 4)),
                      DateTime.now().add(const Duration(days: 3))),
                ),
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>
![Uploading Screenshot 2024-07-30 at 1.05.17 PM.png…]()

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
[Add the Stack Traces here]
```

</details>

### On which target platforms have you observed this bug?

iOS

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[Add your output here]
```

</details>

**Comment by VijayakumarMariappan** [comment] 2024-07-31 11:52
Duplicate of https://github.com/syncfusion/flutter-widgets/issues/1917.

**Comment by VijayakumarMariappan** [comment] 2024-07-31 11:53
Duplicate of https://github.com/syncfusion/flutter-widgets/issues/1917.

@vipul8815 Please check https://github.com/syncfusion/flutter-widgets/issues/1917.

**Closed by VijayakumarMariappan** 2024-07-31 11:52 UTC
Labels: date picker, duplicate
