### ISSUE TITLE
PDF text extraction issue

### ISSUE THREAD

**Issue by ekuleshov** [syncfusion/flutter-widgets#775] opened 2022-06-05 22:40 UTC
I'm trying to use the latest version of `syncfusion_flutter_pdf` to extract lines of text from PDF files using the following code:

```
    List<TextLine> lines = PdfTextExtractor(document).extractTextLines(startPageIndex: 0, endPageIndex: 0);
    for (TextLine line in lines) {
      print(line.text);
    }
```

It pulls all the text fine, however for a table-formatted data it skips any field separators.

So I get this output:

```
33,754355150010114,65
42,615280160000030,59
91,715485190010049,55
101,59313552100021,97
112,4938100200000040,10
122,616075150000028,67
132,513475150000029,84
144,1152408000009,72
153,116580160000025,67
```

and the same look like this in the original PDF:

<img width="873" alt="image" src="https://user-images.githubusercontent.com/440954/172073456-e871015a-64c5-4813-9a1e-af72e01939e1.png">

I wonder if it would be possible to add some separator between individual fields (e.g. `\t` or similar) to preserve structure of the data. E.g. the Apache PdfBox inserts spaces between these fields.

**Comment by ted-marozzi** [comment] 2022-06-06 10:51
If you use the extractText method there is a layout boolean. Maybe it does what you want.
```
String lines = PdfTextExtractor(document).extractText(layout: true);
print(lines);
```
I didn't test this. Just guessing.
Also may want to look at this linux util: https://manpages.debian.org/experimental/poppler-utils/pdftotext.1.en.html

It has the most powerful pdf text extraction engine that I have found so far. I use it in an application by making an os call and reading the txt file. It has a -layout option for this purpose.

**Comment by GowthamrajKumar25** [comment] 2022-06-06 11:23
Hi ekuleshov,

It is not possible to extract lines with spaces using "extractTextLines" when all the text in the same line was rendered at different time. To get all the values in the lines separately, we can use below code snippet on your end and let us know if it is satisfies your requirement or not.

`List<TextLine> textlines = PdfTextExtractor(document).extractTextLines(startPageIndex: 0);
for (TextLine line in textlines) {
  List<TextWord> textWords = line.wordCollection;
  for (TextWord word in textWords) {
    print(word.text);
  }
}`

To get the layout of the page, we can use "extractText",
`extractor.extractText(startPageIndex: 0, layoutText: true);`

Please refer the below documentation link,
https://www.syncfusion.com/kb/11967/how-to-extract-text-from-a-pdf-file-in-syncfusion-flutter-pdf-library

Please let us know if you need any further assistance in this.

Regards,
Gowthamraj K

**Comment by ekuleshov** [comment] 2022-06-06 12:27
> To get all the values in the lines separately, we can use below code snippet on your end and let us know if it is satisfies your requirement or not.

I tried your example and all text from these lines is returned as a single word, which is not what I can use for processing:

```
33,754355150010114,65
42,615280160000030,59
91,715485190010049,55
101,59313552100021,97
112,4938100200000040,10
122,616075150000028,67
132,513475150000029,84
144,1152408000009,72
153,116580160000025,67
```

It seems like the problem is that the `PdfTextExtractor` is gluing together all text on the same line that is rendered with the same font (or something like that). It needs to somehow take into account location of the text and maybe insert some separator between each group.

**Comment by senvB** [comment] 2022-11-15 09:14
I am facing the same issue when reading data from a table. The table row is concatenated into one TextWord. This makes it impossible to differentiate single words from the document and get their position. Using extractText and layout set to true adds at least some space. But when using extractTextLines this option is not available.
Any chance to look into this issue?

**Comment by irfanajaffer** [comment] 2023-01-06 05:56
We suspect that the issue may be due to specific PDF document.

 Kindly provide us with the issue PDF for analyzing further in this.

**Comment by senvB** [comment] 2023-01-06 08:40
Thanks for picking this up. You can find a PDF which is resulting in a single word per textile using this URL: https://www.dsab-vfs.de/VFSProject/WebObjects/VFSProject.woa/wa/rangListen?liga=5703&typ=partienplanPDF&saison=3304

**Comment by ekuleshov** [comment] 2023-02-05 18:12
@irfanajaffer @GowthamrajKumar25 Any update on this?

For this file [20220828.pdf](https://github.com/syncfusion/flutter-widgets/files/10611750/20220828.pdf)
When I use the `PdfTextExtractor(document).extractText(..)` with parameter `layoutText` set to `false`, it returns every column from PDF on a new row:

```
1
142
21,22
6,6918
160,0000
100,00
2
146
22,19
6,5795
157,3159
98,32
...
```

But with the `layoutText` parameter set to `true` the result look like this, i.e. all column data are crumbled together and extracted text doesn't give any way to separate columns:

```
114221,226,6918160,0000100,00	
214622,196,5795157,315998,32	
...
```

Either way it is hard to work with this data.

Looking at the PDF extractor code:

https://github.com/syncfusion/flutter-widgets/blob/4e8f8c73cfeaf2248ed05a88d7fe85d2e04c91eb/packages/syncfusion_flutter_pdf/lib/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart#L1430-L1436

If I change line 1432 to something like this:

```
resultantText += currentText! + wordSeparator; // add word separator such as '\t'
```

Then I get the following desired result. 

```
1	142	21,22	6,6918	160,0000	100,00	
2	146	22,19	6,5795	157,3159	98,32	
...
```

Perhaps you could implement a simple fix and allow to pass an optional `wordSeparator` argument the the `PdfTextExtractor(document).extractText(..)` method.

**Comment by ekuleshov** [comment] 2023-03-11 15:16
@GowthamrajKumar25 @irfanajaffer any chance this issue could be addressed with the above fix or enhancement option?

**Comment by irfanajaffer** [comment] 2023-03-16 09:32
<html>
<body>
<p style="box-sizing: border-box; margin: 0in; color: rgba(0, 0, 0, 0.87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif;">In the provided PDF document “20220828.pdf”, the PDF contains embedded data that is not possible to layout without retrieving the respective font data. So kindly use extractTextLine() method to layout the text instead of extractText(layout).</p><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgba(0, 0, 0, 0.87); font-family: Heebo, &quot;open sans&quot;, sans-serif, -apple-system, BlinkMacSystemFont; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="box-sizing: border-box;"></p><p style="box-sizing: border-box; margin: 0in; color: rgba(0, 0, 0, 0.87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif;">Kindly use the following simple code for layouting using extractTextLine() method,</p>

PdfDocument document = PdfDocument(inputBytes: inputBytes); 
 PdfTextExtractor extractor = PdfTextExtractor(document);
   String extractedText = '';  
 List<TextLine> textLines = extractor.extractTextLines();
   for (int i = 0; i < textLines.length; i++)
 {
     TextLine line = textLines[i]; 
    for (int j = 0; j < line.wordCollection.length; j++) 
 {
       extractedText += ' ${line.wordCollection[j].text}';    
 }
     if (i + 1 < textLines.length &&        (line.bounds.top - textLines[i + 1].bounds.top).abs() > 1) 
 {      extractedText += '\r\n';    }  }  print(extractedText);  document.dispose();
--


<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgba(0, 0, 0, 0.87); font-family: Heebo, &quot;open sans&quot;, sans-serif, -apple-system, BlinkMacSystemFont; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="box-sizing: border-box;"></p><p style="box-sizing: border-box; margin: 0in; color: rgba(0, 0, 0, 0.87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif;">In document “Spielplan.pdf”, We confirmed the issue<span> </span><b style="box-sizing: border-box; font-weight: 700;">”Extract text line words are not split properly for specific document”</b><span> </span>as a defect in our product and fix will be included in our upcoming weekly release, which will be available on March 28, 2023.</p><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgba(0, 0, 0, 0.87); font-family: Heebo, &quot;open sans&quot;, sans-serif, -apple-system, BlinkMacSystemFont; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="box-sizing: border-box;"></p><p style="box-sizing: border-box; margin: 0in; color: rgba(0, 0, 0, 0.87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif;">Use the below feedback link to track the status of the reported bug.</p><p style="box-sizing: border-box; margin: 0in; color: rgba(0, 0, 0, 0.87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif;"><a href="https://www.syncfusion.com/feedback/42104/extract-text-line-words-are-not-split-properly-for-specific-document" target="_blank" style="box-sizing: border-box; color: rgb(46, 46, 241); text-decoration: none; background-color: transparent; user-select: auto;">https://www.syncfusion.com/feedback/42104/extract-text-line-words-are-not-split-properly-for-specific-document</a></p><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgba(0, 0, 0, 0.87); font-family: Heebo, &quot;open sans&quot;, sans-serif, -apple-system, BlinkMacSystemFont; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="box-sizing: border-box;"></p><p style="box-sizing: border-box; margin: 0in; color: rgba(0, 0, 0, 0.87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif;">Disclaimer: “Inclusion of this solution in the weekly release may change due to other factors including but not limited to QA checks and works reprioritization.”</p>
</body>
</html>

**Comment by ekuleshov** [comment] 2023-03-26 15:35
@irfanajaffer I tried your suggestion. It does work on the example I posted above, but it still does not produce separated fields in several other examples I tried.

In comparison, the change I suggested above does produce separated text values in all my test PDFs.

Unfortunately those PDFs have some PII data and I'm not comfortable sharing them in public. But if it would help to address this issue I can email them to you.

On a side note, when trying to extract text from PDFs generated with GhostScript printer, the extracted text has 0x00 values after every character in the result text. I can clean it up in post-processing, but it would be nice if PDF library did that.

**Comment by irfanajaffer** [comment] 2023-03-29 13:53
The reported problem ”Extract text line words are not split properly for the specific document”  is resolved in our latest flutter package release version 21.1.37.

Please refer to the package below:

https://pub.dev/packages/syncfusion_flutter_pdf/versions/21.1.37

@ekuleshov ,
We understand that the security and confidentiality of your files are of utmost importance to you, and we want to assure you that your files are safe with us.

We have robust security measures in place to ensure that your files are protected from unauthorized access, theft, or loss. Additionally, we adhere to strict privacy policies and industry best practices to safeguard your data.

Once the analysis is completed, we will promptly delete your files from our systems. We do not retain any customer data beyond what is necessary to complete the requested service.

We take great pride in our commitment to providing secure and reliable services to our customers. Should you have any further questions or concerns, please do not hesitate to contact us.

**Comment by ekuleshov-idexx** [comment] 2023-03-29 14:41
@irfanajaffer I will check my PDF files with the last release. Thank you.

Regarding sharing them with you, I don't have concerns with you retaining them for testing, but do have concerns with attaching them to this public issue tracker. Like I said, if it would help to diagnose issues, I can email them to you, but can't post/attach them here.

**Comment by ekuleshov** [comment] 2023-03-29 14:42
@irfanajaffer I will check my PDF files with the last release. Thank you.

Regarding sharing them with you, I don't have concerns with you retaining them for testing, but do have concerns with attaching them to this public issue tracker. Like I said, if it would help to diagnose issues, I can email them to you, but can't post/attach them here.

**Closed** 2023-05-09 09:35 UTC
