### ISSUE TITLE
[syncfusion_flutter_pdfviewer] giving wrong search results and text selection not working properly for a particular pdf

### ISSUE THREAD

**Issue by ritz-ch** [syncfusion/flutter-widgets#380] opened 2021-09-22 05:48 UTC
I am using syncfusion_flutter_pdfviewer package. I am using a pdf that comprises of tables and illustrations mainly ,on searching in this pdf ,some words are being highlighted wrongly ,these are the words which lies in the table. Plus, the text selection also does not work properly if I select text from table. 
@syncfusion 

**sample pdf:** 
[SEQ_Sewerage Drawings.pdf](https://github.com/syncfusion/flutter-widgets/files/7207991/SEQ_Sewerage.Drawings.pdf)

Attaching screenshots for the same:

**1. Showing wrongs words highlighted:** 

![1632288825404](https://user-images.githubusercontent.com/60787872/134289174-6f546c92-06b9-44b7-bbb4-c286b608a45f.jpg)

**2. Text selection not working properly**

![1632288825386](https://user-images.githubusercontent.com/60787872/134289405-9a439122-658b-443f-8e59-a6ea12cdccc7.jpg)

**Comment by deepika134** [comment] 2021-09-22 14:20
Hi Rithika,

We can reproduce the reported issue from our side. We are analyzing on this and will update the further details on 24th September 2021.

Regards,
Deepika R

**Comment by deepika134** [comment] 2021-09-28 04:15
Hi Rithika,

We have confirmed that the reported issue “Giving wrong search results and text selection not working properly for a particular pdf” is a defect. The issue fix will be included in our upcoming weekly release, which is estimated to be available on October 5, 2021.Kindly use the below feedback link to track the status of this reported issue, 
https://www.syncfusion.com/feedback/28934/resultant-bounds-are-not-proper-while-performing-text-search-on-particular-pdf.
 
Regards, 
Deepika R

**Comment by deepika134** [comment] 2021-10-05 15:33
Hi Rithika,

We regret for the inconvenience.

Due to stability concerns, we will include the fix for the reported issue in the upcoming weekly release which will be available on 12th October 2021.

Regards,
Deepika R

**Comment by deepika134** [comment] 2021-10-19 15:17
Hi Rithika,

We appreciate your patience.

We have included the fix for “Giving wrong search results for a particular document” in our latest weekly NuGet release, so kindly upgrade to the latest version v19.3.46 to get the issue resolved.
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.3.46-beta 
and we included the fix for the text selection not working properly for a particular document in our latest version.

On further analyzing, we found that the provided document contains a rotated glyph for some words. Currently, SfPdfViewer doesn't provide text selection for rotated glyphs in word, so text selection is not working on few pages. We are analyzing on this feature and will update the further details on 22 October 2021.

Regards,
Deepika Ravi

**Closed** 2022-01-10 06:19 UTC
