### ISSUE TITLE
Flutter 3.7 inside error

### ISSUE THREAD

**Issue by ahmet-ozberk** [syncfusion/flutter-widgets#1060] opened 2023-02-01 13:40 UTC
Error (Xcode): ../../.pub-cache/hosted/pub.dev/syncfusion_flutter_pdf-20.4.48/lib/src/pdf/implementation/forms/pdf_xfdf_document.dart:38:35: Error: The argument type 'String?' can't be assigned to the parameter type 'Object' because 'String?' is nullable and 'Object' isn't.

**Comment by VadimMerzlikin** [comment] 2023-02-01 14:26
I has error too
../../../../.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdf-20.4.48/lib/src/pdf/implementation/forms/pdf_xfdf_document.dart:38:35: Error: The argument type 'String?' can't be assigned to the parameter type 'Object' because 'String?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
        builder.attribute('href', _pdfFilePath);
                                  ^

**Comment by VadimMerzlikin** [comment] 2023-02-01 14:49
> Error (Xcode): ../../.pub-cache/hosted/pub.dev/syncfusion_flutter_pdf-20.4.48/lib/src/pdf/implementation/forms/pdf_xfdf_document.dart:38:35: Error: The argument type 'String?' can't be assigned to the parameter type 'Object' because 'String?' is nullable and 'Object' isn't.

fix your version to syncfusion_flutter_pdf: 20.2.36, it work for me

**Comment by kupresk14** [comment] 2023-02-01 15:54
We are seeing this as well, no version change, just started happening today

**Comment by kaun9144** [comment] 2023-02-01 16:35
Getting same error in my existing project from today.


../../../../.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdf-20.4.48/lib/src/pdf/implementation/forms/pdf_xfdf_document.dart:38:35: Error: The argument type 'String?' can't be assigned to the parameter type 'Object' because 'String?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
        builder.attribute('href', _pdfFilePath);
                                  ^


FAILURE: Build failed with an exception.

* Where:
Script '/Users/aeologic/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/aeologic/flutter/bin/flutter'' finished with non-zero exit value 1


@VadimMerzlikin  I have tried 20.2.36 and latest version also but not resolved.

**Comment by Pexeed** [comment] 2023-02-01 16:45
The weird thing is that we rolled back the version to `20.3.59` , but the github actions are failing with the same error message:
```
/opt/hostedtoolcache/flutter/stable-3.3.10-x64/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.4.48/lib/src/widgets/interactive_scroll_viewer.dart:59:9: Error: Type 'PanAxis' not found.
  final PanAxis panAxis;
        ^^^^^^^
/opt/hostedtoolcache/flutter/stable-3.3.10-x64/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.4.48/lib/src/widgets/interactive_scroll_viewer.dart:15:22: Error: Undefined name 'PanAxis'.
      this.panAxis = PanAxis.free,
                     ^^^^^^^
/opt/hostedtoolcache/flutter/stable-3.3.10-x64/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.4.48/lib/src/widgets/interactive_scroll_viewer.dart:59:9: Error: 'PanAxis' isn't a type.
  final PanAxis panAxis;
        ^^^^^^^
/opt/hostedtoolcache/flutter/stable-3.3.10-x64/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.4.48/lib/src/widgets/interactive_scroll_viewer.dart:[29](https://github.com/floatme-corp/floatme-flutter/actions/runs/4065898040/jobs/7001230837#step:7:30)9:9: Error: No named parameter with the name 'panAxis'.
        panAxis: widget.panAxis,
        ^^^^^^^
/opt/hostedtoolcache/flutter/stable-3.3.10-x64/packages/flutter/lib/src/widgets/interactive_viewer.dart:61:3: Context: Found this candidate, but the arguments don't match.
  InteractiveViewer({
  ^^^^^^^^^^^^^^^^^
/opt/hostedtoolcache/flutter/stable-3.3.10-x64/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdf-20.4.48/lib/src/pdf/implementation/forms/pdf_xfdf_document.dart:38:[35](https://github.com/floatme-corp/floatme-flutter/actions/runs/4065898040/jobs/7001230837#step:7:36): Error: The argument type 'String?' can't be assigned to the parameter type 'Object' because 'String?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
        builder.attribute('href', _pdfFilePath);
```

This error tells me that it is using version `20.4.48`, but I locked it to `20.3.59` , that makes me think github actions is caching something, but it shouldn't be.

**Comment by Pexeed** [comment] 2023-02-01 16:52
Ok so I think I found the issue.

We are using in our company project the `syncfusion_flutter_pdfviewer`  library, looking at the pubspec, it consumes other syncfusion libraries, but it doesn't lock the other library versions.

So the `syncfusion_flutter_core` version that it is using is ALWAYS the latest release, and the latest release is broken at the moment.

You can check that here:
https://github.com/syncfusion/flutter-widgets/blob/master/packages/syncfusion_flutter_pdfviewer/pubspec.yaml

If we lock the pubspec dependencies to older versions of the syncfusion libraries it should fix it, at least for my case it would be:
```
syncfusion_pdfviewer_platform_interface: 20.3.59

  syncfusion_pdfviewer_web: 20.3.59

  syncfusion_pdfviewer_macos: 20.3.59
  
  syncfusion_pdfviewer_windows: 20.3.59
  
  syncfusion_flutter_core: 20.3.59

  syncfusion_flutter_pdf: 20.3.59
```

That's why I recommend locking flutter library versions, I've faced this issue with new library releases breaking at least 3 other times haha

**Comment by Pexeed** [comment] 2023-02-01 17:42
Ok so I think I found the issue.

In my case the syncfusion_flutter_pdfviewer library, looking at the pubspec, it consumes other syncfusion libraries, but it doesn't lock the other library versions.

So the syncfusion_flutter_core version that it is using is ALWAYS the latest release, and the latest release is broken at the moment.

You can check that here:
https://github.com/syncfusion/flutter-widgets/blob/master/packages/syncfusion_flutter_pdfviewer/pubspec.yaml

If we lock the pubspec dependencies to older versions of the syncfusion libraries it should fix it, at least for my case it would be:
```
  syncfusion_pdfviewer_platform_interface: 20.3.59

  syncfusion_pdfviewer_web: 20.3.59

  syncfusion_pdfviewer_macos: 20.3.59
  
  syncfusion_pdfviewer_windows: 20.3.59
  
  syncfusion_flutter_core: 20.3.59

  syncfusion_flutter_pdf: 20.3.59
```
  
That's why I recommend locking flutter library versions, I've faced this issue with new library releases breaking at least 3 other times haha

**Comment by edgarfroes** [comment] 2023-02-01 20:47
@Pexeed yup, I've locked them all to `20.4.44` and it's working now.
The code owners should've upgraded to `20.5.0`, as it introduces breaking changes. It's not the first time they did this to this library.

It remembers me of a case where one dependency of another dependency was using a dependency version from a git branch instead of a tag or a version number. Bad code was pushed to the branch and everything started to fall apart. I've spent quite a few hours with it.

**Comment by kaun9144** [comment] 2023-02-02 09:08
@Pexeed  I have tried solution which you mentioned and it's working now.
Thank you

**Comment by irfanajaffer** [comment] 2023-02-07 06:35
<html>
<body>
<p style="box-sizing: border-box; margin: 0in; color: rgba(0, 0, 0, 0.87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif;">We found that the problem is due to the older version of the<span> </span><a href="https://pub.dev/packages/xml/versions" target="_blank" style="box-sizing: border-box; color: rgb(46, 46, 241); text-decoration: none; background-color: transparent; user-select: auto;">xml</a><span> </span>package being referred to in your project. Recently, the<span> </span><a href="https://pub.dev/documentation/xml/latest/xml/XmlBuilder/attribute.html" target="_blank" style="box-sizing: border-box; color: rgb(46, 46, 241); text-decoration: none; background-color: transparent; user-select: auto;">XmlBuilder</a><span> </span>attribute value API has been updated from non-nullable to nullable type; you can refer to the following API reference for further details.</p><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgba(0, 0, 0, 0.87); font-family: Heebo, &quot;open sans&quot;, sans-serif, -apple-system, BlinkMacSystemFont; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="box-sizing: border-box;"></p>

Xml package version 6.2.0 | Xml package version 6.2.2
-- | --
https://pub.dev/documentation/xml/6.2.0/xml/XmlBuilder/attribute.html | https://pub.dev/documentation/xml/latest/xml/XmlBuilder/attribute.html

<p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgba(0, 0, 0, 0.87); font-family: Heebo, &quot;open sans&quot;, sans-serif, -apple-system, BlinkMacSystemFont; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="box-sizing: border-box;"></p><p style="box-sizing: border-box; margin: 0in; color: rgba(0, 0, 0, 0.87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif;">So, we request you to update your pub cache by using the following command to resolve the issue.</p><p style="box-sizing: border-box; margin: 0in; color: rgba(0, 0, 0, 0.87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; background: rgb(33, 33, 33); font-size: 11pt; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; font-size: 10pt; font-family: &quot;Roboto Mono&quot;; color: rgb(100, 221, 23);">dart pub cache add xml<span> </span></span><span style="box-sizing: border-box; font-size: 10pt; font-family: &quot;Roboto Mono&quot;; color: rgb(153, 187, 0);">--version</span><span style="box-sizing: border-box; font-size: 10pt; font-family: &quot;Roboto Mono&quot;; color: rgb(100, 221, 23);"><span> </span></span><span style="box-sizing: border-box; font-size: 10pt; font-family: &quot;Roboto Mono&quot;; color: rgb(0, 204, 238);">"6.2.2"</span></p><p style="box-sizing: border-box; margin: 0px 0px 10px; color: rgba(0, 0, 0, 0.87); font-family: Heebo, &quot;open sans&quot;, sans-serif, -apple-system, BlinkMacSystemFont; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br style="box-sizing: border-box;"></p><p style="box-sizing: border-box; margin: 0in; color: rgba(0, 0, 0, 0.87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; font-size: 11pt; font-family: Calibri, sans-serif;">You can refer<span> </span><a href="https://dart.dev/tools/pub/cmd/pub-cache" target="_blank" style="box-sizing: border-box; color: rgb(46, 46, 241); text-decoration: none; background-color: transparent; user-select: auto;">https://dart.dev/tools/pub/cmd/pub-cache</a><span> </span>for more details.</p>
</body>
</html>

**Comment by okbye123** [comment] 2023-03-17 12:07
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA

**Closed** 2023-04-11 04:36 UTC
