### ISSUE TITLE
[syncfusion_flutter_pdfviewer]Page crashes in web browser

### ISSUE THREAD

**Issue by OnesWYong** [syncfusion/flutter-widgets#954] opened 2022-11-04 06:56 UTC
Under html rendering, I use the mobile browser to open the demo webpage. After swiping up and down multiple times, the page crashes. Looks like a memory overflow.

This is the version I use

```
  syncfusion_flutter_pdfviewer: 20.2.44-beta
  syncfusion_pdfviewer_platform_interface: 20.2.44-beta
```

<details>
<summary>logs</summary>

```
➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.2.1 21D62 darwin-arm, locale
    zh-Hans-CN)
    • Flutter version 3.0.4 at /Users/ones-wy/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (4 months ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
    • Android SDK at /Users/ones-wy/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • ANDROID_HOME = /Users/ones-wy/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/ones-wy/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • 21091116C (mobile) • rcguam4h759pt4jn • android-arm64  • Android 11 (API
      30)
    • macOS (desktop)    • macos            • darwin-arm64   • macOS 12.2.1
      21D62 darwin-arm
    • Chrome (web)       • chrome           • web-javascript • Google Chrome
      100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

**Comment by deepika134** [comment] 2023-02-01 03:58
Hi @OnesWYong, We tried to replicate the issue with provided details, but the PDF is loaded properly on our side. Kindly share the following details, to reproduce the reported issue on our end.

- Flutter SDK version.
- Issue reproducing steps or video.
- Issue reproducing document

This information will be helpful for us to provide you a prompt solution at the earliest.

**Comment by ramkumarsync** [comment] 2024-02-07 10:57
We are closing this issue since we don't have enough information to reproduce it. You can reopen this anytime and share the requested details to proceed further.

**Closed by ramkumarsync** 2024-02-07 10:57 UTC
Labels: pdf_viewer

**Comment by AhmedAbogameel** [comment] 2025-01-07 19:22
any solutions ? 
i have the same issue on mobile and on web with large pdf
