### ISSUE TITLE
syncfusion flutter pdf viewer not opening pdfs created through adobe scan

### ISSUE THREAD

**Issue by brightseagit** [syncfusion/flutter-widgets#223] opened 2021-05-12 13:06 UTC
Hello,
I was trying to open pdf created through adobe scan using "syncfusion flutter pdf viewer" but it failed to open the pdf correctly. It shows blank white pages with no content. When using the emulator it is working fine but on local devices, it failed with no error in the terminal. 

Here is how it looks in emulator and on local android device respectively:
<img src="https://user-images.githubusercontent.com/72334435/117979101-2ede2c80-b350-11eb-9048-eca05d667b74.png" width="300"/> <img src="https://user-images.githubusercontent.com/72334435/117979157-3ef60c00-b350-11eb-9e87-6567ebe4bd96.jpeg" width="300"/> 

Procedure to recreate the issue:
1. Scan a paper using adobe scan to convert it to pdf or use this [Sample.pdf](https://github.com/syncfusion/flutter-widgets/files/6466273/Sample.pdf).
2. Use a local device to load and view the scanned pdf.

Plugin version : syncfusion_flutter_pdf 19.1.59-beta
Device android version : Android 10, 11

**Comment by dillibabun** [comment] 2021-05-14 08:57
Hi @brightseagit ,

Greetings from Syncfusion.

We can reproduce the reported issue with "Blank page is displayed while loading Adobe scanned PDF document in Android" and suspect it as a defect. We are analyzing this issue and will update the validation details on 18 May 2021.

Regards,
Dilli babu.

**Comment by sarathkumar50** [comment] 2021-05-18 09:51
Hi @brightseagit ,

We have already resolved the reported issue with "Blank page is displayed while loading Adobe scanned PDF document in Android". This fix has been included in our next weekly NuGet release which is expected to available in 19th May, 2021.
 
Regards,
Sarath Kumar.

**Comment by brightseagit** [comment] 2021-05-18 17:35
🙏 Thanks for fixing the issue and letting me know about that. I will try it when the update releases 👍.

**Comment by sarathkumar50** [comment] 2021-05-19 07:10
Hi @brightseagit ,

[Weekly package(19.1.64)](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.1.64-beta) has been released. We have tested this package and the reported issue has been resolved. Kindly use the latest package and let us know if you are facing any other issues.

Note: Since the provided document contains high quality image, SfPdfViewer takes couple of seconds to render in your application.

Regards,
Sarath Kumar.

**Comment by brightseagit** [comment] 2021-05-20 12:25
I have verified that scanned documents are getting displayed correctly . Thanks 👍.

Here is how it looks in emulator and on local android device respectively:
![2](https://user-images.githubusercontent.com/72334435/118978045-7db14500-b994-11eb-8ee7-69b81d81838e.jpg)

**Closed** 2021-05-20 12:26 UTC

**Comment by touseefali** [comment] 2023-08-28 01:39
Hello
I am facing the same issue with the latest version a grey page is displaying on explorer and on samsung device
