### ISSUE TITLE
[syncfusion_flutter_pdfviewer] I am facing an issue in [20.4.48] latest version

### ISSUE THREAD

**Issue by lkrjangid1** [syncfusion/flutter-widgets#1067] opened 2023-02-03 09:58 UTC
Error:
```

../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.4.48/lib/src/widgets/interactive_scroll_viewer.dart:59:9: Error: Type 'PanAxis' not found.
  final PanAxis panAxis;
        ^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.4.48/lib/src/widgets/interactive_scroll_viewer.dart:15:22: Error: Undefined name 'PanAxis'.
      this.panAxis = PanAxis.free,
                     ^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/reorderables-0.6.0/lib/src/widgets/reorderable_flex.dart:320:33: Error: Member not found: 'PrimaryScrollController.maybeOf'.
        PrimaryScrollController.maybeOf(context) ??
                                ^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/reorderables-0.6.0/lib/src/widgets/reorderable_flex.dart:324:44: Error: Member not found: 'Scrollable.maybeOf'.
      _attachedScrollPosition = Scrollable.maybeOf(context)?.position;
                                           ^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/reorderables-0.6.0/lib/src/widgets/reorderable_flex.dart:379:32: Error: A value of type 'RenderAbstractViewport?' can't be assigned to a variable of type 'RenderAbstractViewport' because 'RenderAbstractViewport?' is nullable and 'RenderAbstractViewport' isn't.
 - 'RenderAbstractViewport' is from 'package:flutter/src/rendering/viewport.dart' ('/C:/flutter/packages/flutter/lib/src/rendering/viewport.dart').
        RenderAbstractViewport.of(contextObject);
                               ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/reorderables-0.6.0/lib/src/widgets/reorderable_flex.dart:885:33: Error: Member not found: 'PrimaryScrollController.maybeOf'.
        PrimaryScrollController.maybeOf(context) == null) {
                                ^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/reorderables-0.6.0/lib/src/widgets/reorderable_sliver.dart:387:33: Error: Member not found: 'PrimaryScrollController.maybeOf'.
        PrimaryScrollController.maybeOf(context) ??
                                ^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/reorderables-0.6.0/lib/src/widgets/reorderable_sliver.dart:392:22: Error: Member not found: 'Scrollable.maybeOf'.
        : Scrollable.maybeOf(context)?.position;
                     ^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/reorderables-0.6.0/lib/src/widgets/reorderable_sliver.dart:502:32: Error: A value of type 'RenderAbstractViewport?' can't be assigned to a variable of type 'RenderAbstractViewport' because 'RenderAbstractViewport?' is nullable and 'RenderAbstractViewport' isn't.
 - 'RenderAbstractViewport' is from 'package:flutter/src/rendering/viewport.dart' ('/C:/flutter/packages/flutter/lib/src/rendering/viewport.dart').
        RenderAbstractViewport.of(contextObject);
                               ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/reorderables-0.6.0/lib/src/widgets/reorderable_wrap.dart:500:33: Error: Member not found: 'PrimaryScrollController.maybeOf'.
        PrimaryScrollController.maybeOf(context) ??
                                ^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/reorderables-0.6.0/lib/src/widgets/reorderable_wrap.dart:542:32: Error: A value of type 'RenderAbstractViewport?' can't be assigned to a variable of type 'RenderAbstractViewport' because 'RenderAbstractViewport?' is nullable and 'RenderAbstractViewport' isn't.
 - 'RenderAbstractViewport' is from 'package:flutter/src/rendering/viewport.dart' ('/C:/flutter/packages/flutter/lib/src/rendering/viewport.dart').
        RenderAbstractViewport.of(contextObject);
                               ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/reorderables-0.6.0/lib/src/widgets/reorderable_wrap.dart:1231:33: Error: Member not found: 'PrimaryScrollController.maybeOf'.
        PrimaryScrollController.maybeOf(context) == null) {
                                ^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.4.48/lib/src/pdfviewer.dart:1016:54: Error: Method 'readState' cannot be called on 'PageStorageBucket?' because it is potentially null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
Try calling using ?. instead.
      final dynamic offset = PageStorage.of(context).readState(context);
                                                     ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.4.48/lib/src/pdfviewer.dart:1020:12: Error: Method 'readState' cannot be called on 'PageStorageBucket?' because it is potentially null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
Try calling using ?. instead.
          .readState(context, identifier: 'zoomLevel_${widget.key}');
           ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.4.48/lib/src/pdfviewer.dart:3244:35: Error: Method 'writeState' cannot be called on 'PageStorageBucket?' because it is potentially null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
Try calling using ?. instead.
          PageStorage.of(context).writeState(
                                  ^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.4.48/lib/src/pdfviewer.dart:3272:35: Error: Method 'writeState' cannot be called on 'PageStorageBucket?' because it is potentially null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
Try calling using ?. instead.
          PageStorage.of(context).writeState(
                                  ^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.4.48/lib/src/widgets/interactive_scroll_viewer.dart:59:9: Error: 'PanAxis' isn't a type.
  final PanAxis panAxis;
        ^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.4.48/lib/src/widgets/interactive_scroll_viewer.dart:299:9: Error: No named parameter with the name 'panAxis'.
        panAxis: widget.panAxis,
        ^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/interactive_viewer.dart:61:3: Context: Found this candidate, but the arguments don't match.
  InteractiveViewer({
  ^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_pdf-20.4.48/lib/src/pdf/implementation/forms/pdf_xfdf_document.dart:38:35: Error: The argument type 'String?' can't be assigned to the parameter type 'Object' because 'String?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
        builder.attribute('href', _pdfFilePath);
                                  ^


FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildStestRelease'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 43s
Running Gradle task 'assembleStestRelease'...                      45.2s
Gradle task assembleStestRelease failed with exit code 1
```

**Comment by Garciconx** [comment] 2023-02-03 18:11
Same here, greetings!

**Comment by GSORF** [comment] 2023-02-05 23:45
Duplicate of #1069 and #1064.

I was able to find a solution with the help of the other issues. Maybe it will help you too?

Kind regards,
Adam

**Comment by Garciconx** [comment] 2023-02-06 03:15
> Duplicate of #1069 and #1064.
> 
> I was able to find a solution with the help of the other issues. Maybe it will help you too?
> 
> Kind regards, Adam

Thanks @GSORF, #1064 helped me to solve the issue, greetings!

**Comment by deepika134** [comment] 2023-02-06 05:50
This issue is caused by a recent upgrade to Flutter version. Kindly run the **flutter clean** command and upgrade to the latest version [3.7.0] of Flutter SDK and Syncfusion Flutter PDFViewer to get the issue resolved. Please try this and let us know if the issue is resolved or not.
Flutter SDK setup link for the latest version: https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.7.0-stable.zip 
Syncfusion Flutter PDFViewer link for the latest version: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/20.4.48

**Comment by okbye123** [comment] 2023-03-17 12:07
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA

**Comment by Shahzeb-99** [comment] 2023-12-12 05:39
I change the minSdkVersion to 21 and it worked.

**Closed** 2024-02-07 12:38 UTC
Labels: pdf_viewer
