### ISSUE TITLE
I use the latest version, but the highlight of the search function has deviated

### ISSUE THREAD

**Issue by yixiu30** [syncfusion/flutter-widgets#340] opened 2021-08-12 09:22 UTC
![QQ截图20210812172146](https://user-images.githubusercontent.com/20369016/129172617-9d81f549-1b38-4e25-832a-69a5f3dd6d0b.png)
like this!

**Comment by deepika134** [comment] 2021-08-12 12:23
Hi yixiu30,

Greetings from Syncfusion.

We tried to reproduce the reported issue in other languages (chinese, arabic, latin) PDF document apart from english but it’s working fine on our side. We suspect that it may be document specific, kindly share the PDF document in which you are facing the issue. This will be helpful to investigate further and provide the solution at the earliest.

Regards,
Deepika R

**Comment by deepika134** [comment] 2021-08-13 11:55
Hi yixiu30,

We can reproduce the reported issue from our side. We are analyzing on this and will update the further details on 17 August 2021.

Regards,
Deepika R

**Comment by yixiu30** [comment] 2021-08-16 06:33
I found that there was another problem in the search, such as the path [provided.](https://test.xiamenjwzz.com:9999/portalfile/userFile/2021/08/e348cb5cef8b4ca19cb30177d6910d5d.pdf) When looking for the keyword of chinese name "急", there were fifty-fiveplaces, but I didn't find the keyword at fifty-three to fifty-five

**Comment by yixiu30** [comment] 2021-08-17 03:27
I know this is commercial, but I don't know which module needs to be paid, or which function can't be used without paying

**Comment by deepika134** [comment] 2021-08-17 11:17
Hi yixiu30,

We have confirmed that the reported issue “Resultant bounds are not proper while performing text search in particular PDF document” is a defect. The issue fix will be included in our upcoming weekly release, which will be available on 31 August 2021. The status of this issue can be tracked using the following link https://www.syncfusion.com/feedback/27971/resultant-bounds-are-not-proper-while-performing-text-search-in-particular-pdf. 

There is no change in the features or functionalities of the widgets for paid and free users. But to use our widgets in your production app, you must have a valid Syncfusion license. It can be either Syncfusion commercial license or free community license. Please refer the below links to get more details about the licensing.
Syncfusion license - https://github.com/syncfusion/flutter-examples/blob/master/LICENSE
Community license - https://www.syncfusion.com/products/communitylicense
Pricing - https://www.syncfusion.com/sales/products

Regards,
Deepika R

**Comment by deepika134** [comment] 2021-08-31 11:26
Hi yixiu30,

| Query | Details |
| --- | --- |
| I use the latest version, but the highlight of the search function has deviated | we have included the fix for this issue " Resultant bounds are not proper while performing text search in the particular PDF document" in our latest weekly NuGet release, so kindly upgrade to the latest version v19.2.59 to get the issue resolved.  Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.2.59-beta|
| I found that there was another problem in the search, such as the path provided. When looking for the keyword of Chinese name "急", there were fifty-fiveplaces , but I didn't find the keyword at fifty-three to fifty-five| The reported issue due to the hidden instances of the word in the PDF document. The instances are presented in PDF document level, so it was included in text search occurrences.|

Regards,
Deepika R

**Closed** 2021-10-20 05:16 UTC
