### ISSUE TITLE
"Null check operator used on a null value" in getNearestChartPoints on an SfCartesianChart with trackball

### ISSUE THREAD

**Issue by MrCsabaToth** [syncfusion/flutter-widgets#463] opened 2021-11-29 17:44 UTC
Syncfusion Flutter Charts version 19.3.55
The exception call stack:
```
======== Exception caught by gesture library =======================================================
The following _CastError was thrown while dispatching a pointer event:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      getNearestChartPoints (package:syncfusion_flutter_charts/src/chart/common/common.dart:1644:59)
#1      TrackballRenderingDetails.generateAllPoints (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:897:13)
#2      TrackballBehavior.show (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:436:36)
#3      TrackballBehaviorRenderer.onTouchDown (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:562:52)
#4      ContainerArea._performPointerDown (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2988:14)
#5      ContainerArea.build.<anonymous closure>.<anonymous closure> (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2197:21)
#6      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:2882:29)
#7      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#8      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#9      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#10     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#11     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#12     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#16     _invoke1 (dart:ui/hooks.dart:185:10)
#17     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#18     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 3 frames from dart:async)
Event: PointerDownEvent#96ec0(position: Offset(238.4, 377.8))
  position: Offset(238.4, 377.8)
Target: RenderPointerListener#97763
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=376.0, h=418.7)
  size: Size(376.0, 418.7)
  behavior: deferToChild
  listeners: down, move, up, signal
```

Relevant code sections:
```
import 'package:syncfusion_flutter_charts/charts.dart' as charts;
...
class RecordsScreenState extends State<RecordsScreen> {
  final charts.TooltipBehavior _tooltipBehavior = charts.TooltipBehavior(enable: true);
  final charts.ZoomPanBehavior _zoomPanBehavior = charts.ZoomPanBehavior(
    enableDoubleTapZooming: true,
    enablePinching: true,
    enableSelectionZooming: true,
    zoomMode: charts.ZoomMode.x,
    enablePanning: true,
  );
  final charts.TrackballBehavior _trackballBehavior = charts.TrackballBehavior(
    enable: true,
    activationMode: charts.ActivationMode.singleTap,
    tooltipDisplayMode: charts.TrackballDisplayMode.nearestPoint,
  );
...
  List<charts.LineSeries<DisplayRecord, DateTime>> _getData() {
    return <charts.LineSeries<DisplayRecord, DateTime>>[
      charts.LineSeries<DisplayRecord, DateTime>(
        dataSource: _sampledRecords,
        xValueMapper: (DisplayRecord record, _) => record.dateTime,
        yValueMapper: (DisplayRecord record, _) => record.value,
        color: _chartTextColor,
        animationDuration: 0,
      ),
    ];
  }
...
  @override
  Widget build(BuildContext context) {
...
                      SizedBox(
                        width: widget.size.width,
                        height: widget.size.height / 2,
                        child: charts.SfCartesianChart(
                          primaryXAxis: charts.DateTimeAxis(
                            labelStyle: _chartLabelStyle,
                            axisLine: charts.AxisLine(color: _chartTextColor),
                            majorTickLines: charts.MajorTickLines(color: _chartTextColor),
                            minorTickLines: charts.MinorTickLines(color: _chartTextColor),
                            majorGridLines: charts.MajorGridLines(color: _chartTextColor),
                            minorGridLines: charts.MinorGridLines(color: _chartTextColor),
                          ),
                          primaryYAxis: charts.NumericAxis(
                            plotBands: _plotBands,
                            labelStyle: _chartLabelStyle,
                            axisLine: charts.AxisLine(color: _chartTextColor),
                            majorTickLines: charts.MajorTickLines(color: _chartTextColor),
                            minorTickLines: charts.MinorTickLines(color: _chartTextColor),
                            majorGridLines: charts.MajorGridLines(color: _chartTextColor),
                            minorGridLines: charts.MinorGridLines(color: _chartTextColor),
                          ),
                          margin: const EdgeInsets.all(0),
                          series: _getData(),
                          zoomPanBehavior: _zoomPanBehavior,
                          trackballBehavior: _trackballBehavior,
                        ),
                      ),
```

**Comment by MrCsabaToth** [comment] 2021-11-29 17:56
To help with reproduction: there are multiple charts on the phone's screen listed in a vertically scrollable list. This has an interesting dynamic BTW because the lists's up-down scroll is somewhat interfering with up-down pan (not sure if that's the issue). For the tooltip to appear someone needs to long press on the chart. The crash comes when my finger is not stable during the long press. I have 384 data points on the charts, so it's crowded. Put 5-6 of such charts in a listview, so it scrolls (not sure if that's needed), then intentionally try to pan straight up or straight down while long press for the tooltip.

**Comment by MrCsabaToth** [comment] 2021-11-29 18:08
I tried the `tooltipDisplayMode: charts.TrackballDisplayMode.groupAllPoints` to somehow go around `getNearestChartPoints` because I don't have any level of the call stack when I could catch this crash. The chart crashes with the same call stack while performing the agitated reproduction above.

**Comment by MrCsabaToth** [comment] 2021-11-30 17:47
@Yuvaraj-Gajaraj thank you for your efforts, I'll try to tweak your sample

**Comment by MrCsabaToth** [comment] 2021-11-30 18:17
Ok, I haven't modified the sample yet, but I managed to reproduce another crash multiple times:
```
======== Exception caught by gesture library =======================================================
The following RangeError was thrown while dispatching a pointer event:
RangeError (index): Invalid value: Valid value range is empty: 0

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      getNearestChartPoints (package:syncfusion_flutter_charts/src/chart/common/common.dart:1653:28)
#2      TrackballRenderingDetails.generateAllPoints (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:897:13)
#3      TrackballBehavior.show (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:436:36)
#4      TrackballBehaviorRenderer.onTouchDown (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:562:52)
#5      ContainerArea._performPointerDown (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2988:14)
#6      ContainerArea.build.<anonymous closure>.<anonymous closure> (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2197:21)
#7      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:2882:29)
#8      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#9      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#10     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#11     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#17     _invoke1 (dart:ui/hooks.dart:185:10)
#18     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#19     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 3 frames from dart:async)
Event: PointerDownEvent#c4c00(position: Offset(149.2, 731.4))
  position: Offset(149.2, 731.4)
Target: RenderPointerListener#e05b2
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=384.0, h=418.7)
  size: Size(384.0, 418.7)
  behavior: deferToChild
  listeners: down, move, up, signal
====================================================================================================
```
It requires a few tries and switching between graphs. I cause the tracker to display, then try to swipe up while long pressing. But I don't swipe straight up so it becomes an area selection and the chart zooms in. Then I try to zoom out with pinches. Maybe I'll open another ticket for that because it's a different call stack.

**Comment by MrCsabaToth** [comment] 2021-12-03 08:04
I was side tracked the last few days, I need some more time to reproduce. I managed to reproduce one time, but I need to fine tune to figure out the key to it.

**Comment by MrCsabaToth** [comment] 2021-12-09 07:51
Here is the sample enriched with mock data and other features which are closer to my use-case
[github_463.zip](https://github.com/syncfusion/flutter-widgets/files/7683185/github_463.zip)
However it's still not deterministically reproducable. However with this sample it either comes all the time with every click on the graphs, or it does not come.

**Comment by MrCsabaToth** [comment] 2021-12-13 07:24
There's something very weird going on! I upgraded to the 19.3.57 version. Here is the cached code section which crashes in my pub cache:
![Screenshot_2021-12-12_22-04-51](https://user-images.githubusercontent.com/744949/145760970-23581eb9-2990-43c8-83c3-f8ced0afcdc4.png)

In code:
```
      if (_trackballRenderingDetails.trackballPainter != null &&
          seriesRendererDetails.visibleDataPoints!.isNotEmpty == true) {
        _trackballRenderingDetails.isTrackballTemplate = false;
        _trackballRenderingDetails.generateAllPoints(Offset(x.toDouble(), y));
      } else if (builder != null &&
          (!_trackballRenderingDetails.isMoving) &&
          seriesRendererDetails.visibleDataPoints!.isNotEmpty == true) {
        _trackballRenderingDetails
            .showTemplateTrackball(Offset(x.toDouble(), y));
      }
```
The crash is caused by the `seriesRendererDetails.visibleDataPoints!.isNotEmpty == true` logical predicate, part of the if boolean phrase. I was about to make a PR by hoisting the duplicated predicate out of the two if and changing it to ``seriesRendererDetails.visibleDataPoints?.isNotEmpty ?? false`. But then I realized that the syncfusion repository is different: it just simply missing that problematic predicate:

https://github.com/syncfusion/flutter-widgets/blob/441150d81df4786e2de92dd025a899eedcc221be/packages/syncfusion_flutter_charts/lib/src/chart/user_interaction/trackball.dart#L434
```
      if (_trackballRenderingDetails.trackballPainter != null) {
        _trackballRenderingDetails.isTrackballTemplate = false;
        _trackballRenderingDetails.generateAllPoints(Offset(x.toDouble(), y));
      } else if (builder != null && (!_trackballRenderingDetails.isMoving)) {
        _trackballRenderingDetails
            .showTemplateTrackball(Offset(x.toDouble(), y));
      }
```
This is in the `void show(dynamic x, double y, [String coordinateUnit = 'point'])` function. So probably that's why you cannot reproduce this crash in your lab. But how could the code be different? When I look at the history of the file (https://github.com/syncfusion/flutter-widgets/commits/master/packages/syncfusion_flutter_charts/lib/src/chart/user_interaction/trackball.dart) it have not changed for three+ months now! So I cannot figure out where the `trackball.dart` I have is coming from!

**Comment by MrCsabaToth** [comment] 2021-12-13 07:36
After wiping my pub-cache I still get the faulty code which mismatch what I see in your repo. How is this possible?

**Comment by MrCsabaToth** [comment] 2021-12-13 08:14
I'm starting to suspect that this GitHub repository is really not the actual source of the pub.dev package. Where is the up-to-date source?

**Comment by MrCsabaToth** [comment] 2021-12-13 08:22
Oh yea according to https://github.com/syncfusion/flutter-widgets/blob/master/packages/syncfusion_flutter_charts/CHANGELOG.md this source is only `[19.2.59] - 08/31/2021` version. That didn't have this bug I'm reporting here. But I cannot devise a PR due to the stale source.

**Comment by MrCsabaToth** [comment] 2021-12-14 23:42
https://github.com/syncfusion/flutter-widgets/issues/487

**Comment by MrCsabaToth** [comment] 2021-12-18 01:51
PR#498 crafted!

**Comment by MrCsabaToth** [comment] 2021-12-18 17:11
What's the chance of the PR being accepted?

**Comment by MrCsabaToth** [comment] 2021-12-24 21:56
I have a PR!

**Comment by dharanidharandharmasivam** [comment] 2022-01-03 16:11
Hi @MrCsabaToth ,

We would like to let you know that we are having 4 main releases per year. And for the main release only we will update our packages which are available here. If you wish, now you can share the PR to the flutter-widgets repository. Since the issue is not replicated at our end, kindly get back to us by replicating in the provided sample, this will be much helpful in providing the solution earlier. And kindly share the replication steps as well and we request to ensure with our latest version from below

https://pub.dev/packages/syncfusion_flutter_charts/versions/19.4.40 

Thanks,
Dharani.

**Comment by MrCsabaToth** [comment] 2022-01-09 07:23
@dharanidharandharmasivam I developed the example code further to try to induce easier replication. I observed the `"Null check operator used on a null value"` happen and my PR I think is non intrusive, safe to apply.

**Comment by MrCsabaToth** [comment] 2022-02-04 05:58
I see trackball.dart changed in the 19.4.48 but this null value error is still in there.

**Comment by Yuvaraj-Gajaraj** [comment] 2022-02-22 21:43
Hi @MrCsabaToth,

We have included your fix and merged it into our source. It will be available in our weekly patch release. It would be expected on 1st Mar 2022. We appreciate your patience until then.

Regards,
Yuvaraj.

**Comment by MrCsabaToth** [comment] 2022-02-22 22:10
Excellent! Thank you so much!

**Comment by Yuvaraj-Gajaraj** [comment] 2022-03-09 07:12
Hi @MrCsabaToth,

The fix was included and rolled out in our weekly patch release, so please upgrade the chart package to the below version.

Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/19.4.55

Regards,
Yuvaraj.

**Comment by MrCsabaToth** [comment] 2022-03-10 05:54
I'm looking at the 19.4.55 code and I still see the `seriesRendererDetails.visibleDataPoints!.isNotEmpty == true` clause in the `show` function of the trackball.dart.

**Comment by MrCsabaToth** [comment] 2022-03-16 18:58
> Hi @MrCsabaToth,
> 
> The fix was included and rolled out in our weekly patch release, so please upgrade the chart package to the below version.
> 
> Version: https://pub.dev/packages/syncfusion_flutter_charts/versions/19.4.55
> 
> Regards, Yuvaraj.

I tested with the newest 19.4.56 as well and it still crashes. This is due to the exclamation mark in the `seriesRendererDetails.visibleDataPoints!.isNotEmpty == true`. Since the `visibleDataPoints` indeed can be null the clause crashes. This is why in my PR https://github.com/syncfusion/flutter-widgets/pull/498/ I have the clause with a question mark which avoid the crash: `if (seriesRendererDetails.visibleDataPoints?.isNotEmpty ?? false) {`.

**Comment by MrCsabaToth** [comment] 2022-03-16 19:12
Here is better reproduction step:
1. Clone the source https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/ and build the app
2. Here is a CSV file for testing: https://pastebin.com/nNTkeH9E
3. After the app start click the radial menu button on the bottom right and then Workout List icon (the help button shows an overlay which one is it)
4. On the Workout list screen open up the radial menu again, and click the upload icon
5. At the bottom drawer leave the MPower Echelon type import checkbox selected, click the check mark button
6. Select the CSV file you got from the pastebin
7. Select any date and time for the workout
8. Click import, it takes 1-10 seconds for the file to import
9. Click the back button on the top left, you are back at the Workout list
10. Now that the imported workout is listed click on it's row so the expanded section opens
11. Click on the newly opened expanded section to get to the deeper details of the workout
12. Scroll down and open any of the 4 metrics (Power, Speed, Cadence, HR) to reveal the graph.
13. Now you just have to click in the graph and boom! Crash.

**Comment by MrCsabaToth** [comment] 2022-05-23 07:48
Crash still happens with the newest 20.1.56

**Comment by jyfer** [comment] 2022-05-31 17:08
I have a similar problem with long press action for trackball, just here **chart_base.dart**

` if ((chart.trackballBehavior != null &&
            chart.trackballBehavior.enable == true &&
            chart.trackballBehavior.activationMode ==
                ActivationMode.longPress) &&
        SeriesHelper.getSeriesRendererDetails(_findSeries(position!)!).series
            is! ErrorBarSeries &&
        // ignore: unnecessary_null_comparison
        position != null &&
        zoomingBehaviorDetails.isPinching != true) {`

The **position** is null because **_tapDownDetails** is null too. 

I can see that **_performPointerDown** is probably not being called as this condition is not valid **_stateProperties.chartState.mounted**

**Comment by MrCsabaToth** [comment] 2022-06-26 20:57
This bug is still crashing, I updated my PR. Please merge it. It's been more than half a year I filed this is issue and I have the PR for it.

**Comment by khanh-nguyen-ngoc** [comment] 2022-07-29 03:55
> > I have a similar problem with long press action for trackball, just here **chart_base.dart**
> > ` if ((chart.trackballBehavior != null && chart.trackballBehavior.enable == true && chart.trackballBehavior.activationMode == ActivationMode.longPress) && SeriesHelper.getSeriesRendererDetails(_findSeries(position!)!).series is! ErrorBarSeries && // ignore: unnecessary_null_comparison position != null && zoomingBehaviorDetails.isPinching != true) {`
> > The **position** is null because **_tapDownDetails** is null too.
> > I can see that **_performPointerDown** is probably not being called as this condition is not valid **_stateProperties.chartState.mounted**
> 
> That possibly worth filing another issue

Yeah, that code is definitely causing crashes on my side

**Comment by LokeshPalani** [comment] 2024-02-14 14:14
Hi @MrCsabaToth,

We have done some architectural changes in Charts widget and rolled out in our **Volume 4 Main Release** in 2023. Therefore, we kindly request you to upgrade the **syncfusion_flutter_charts** package to the latest version.

Regards,
Lokesh P.

**Comment by LavanyaGowtham2021** [comment] 2024-02-28 13:21
Please reopen this, if you need any further assistance on this.

**Closed by LavanyaGowtham2021** 2024-02-28 13:21 UTC
Labels: charts, waiting for customer

**Comment by MrCsabaToth** [comment] 2024-02-28 15:30
I haven't experienced this crash for a good while now.
