### ISSUE TITLE
[Flutter Android] Error "There was an error opening this document." when trying to open a document

### ISSUE THREAD

**Issue by sergiogsilva04** [syncfusion/flutter-widgets#1559] opened 2023-12-06 10:11 UTC
Some PDFs aren't opening, and the error "There was an error opening this document" occurs in onDocumentLoadFailed. When I open the document in Edge, it works normally.

Only a few files are opening.

This is happening either with my own phone or with the Android Emulator.

The link is from an API that do the preview, is just a normal pdf
![image](https://github.com/syncfusion/flutter-widgets/assets/64011205/86f63402-e223-4941-ae2e-8e138c2fafcf)

Here is my code:

```
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';

class DocumentViewerScreen extends StatefulWidget {
  final int docId;

  const DocumentViewerScreen({
    super.key,
    required this.docId,
  });

  @override
  State<DocumentViewerScreen> createState() => _DocumentViewerScreenState();
}

class _DocumentViewerScreenState extends State<DocumentViewerScreen> {
  final GlobalKey<SfPdfViewerState> _pdfViewerKey = GlobalKey();
  late String link;

  @override
  void initState() {
    super.initState();

    link = 'EMPTY_LINK';
    print(link);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Syncfusion Flutter PdfViewer'),
        actions: <Widget>[
          IconButton(
            icon: const Icon(
              Icons.bookmark,
              color: Colors.blue,
            ),
            onPressed: () {
              _pdfViewerKey.currentState?.openBookmarkView();
            },
          ),
        ],
      ),
      body: SfPdfViewer.network(
        link,
        onDocumentLoadFailed: (PdfDocumentLoadFailedDetails pdfDocumentLoadFailedDetails) {
          print(pdfDocumentLoadFailedDetails.error);
          print(pdfDocumentLoadFailedDetails.description);
        },
        key: _pdfViewerKey,
      ),
    );
  }
}
```

**Comment by EBBozkurt** [comment] 2024-01-03 17:27
Hello @sergiogsilva04,

In your index.html, do you have these lines:

```
  <script src="//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.min.js"></script>
  <script type="text/javascript">
    pdfjsLib.GlobalWorkerOptions.workerSrc = "//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.worker.min.js";
  </script>
```

If you don't have, you need to add these lines. You can see more details in this [link](https://pub.dev/packages/syncfusion_flutter_pdfviewer#web-integration).

**Comment by daniel-villamizar-yohana** [comment] 2024-01-04 00:11
I'm having the same issue in iOS (Flutter: 3.16.0, syncfusion_flutter_pdfviewer: ^24.1.44)
It only happens with the attached file (a Google spreadsheet downloaded as a PDF).
[spreadsheet.pdf](https://github.com/syncfusion/flutter-widgets/files/13824515/spreadsheet.pdf)

**Comment by sergiogsilva04** [comment] 2024-01-04 21:56
Hi @EBBozkurt, even if I'm not working with web I need to put that? The problem is with Android emulator or my own phone (Android).

**Comment by EBBozkurt** [comment] 2024-01-05 08:47
> Hi @EBBozkurt, even if I'm not working with web I need to put that? The problem is with Android emulator or my own phone (Android).

Hi, there is no mention of **android** in either the issue topic title or issue description. You just mentioned it in your comment. Since I'm not a fortune teller, I guessed there was a problem with web. Because I experienced this kind of problem in web last week. :)


Anyway, I don't want to drag this out any further. I hope your problem will solve fast.

**Comment by sergiogsilva04** [comment] 2024-01-05 09:14
That's my bad, thought I said anything, thank you anyways!

**Comment by ramkumarsync** [comment] 2024-02-14 11:11
> Some PDFs aren't opening, and the error "There was an error opening this document" occurs in onDocumentLoadFailed. When I open the document in Edge, it works normally.
> 
> Only a few files are opening.
> 
> This is happening either with my own phone or with the Android Emulator.
> 
> The link is from an API that do the preview, is just a normal pdf ![image](https://private-user-images.githubusercontent.com/64011205/288369748-86f63402-e223-4941-ae2e-8e138c2fafcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MDkxMjEsIm5iZiI6MTcwNzkwODgyMSwicGF0aCI6Ii82NDAxMTIwNS8yODgzNjk3NDgtODZmNjM0MDItZTIyMy00OTQxLWFlMmUtOGUxMzhjMmZhZmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDExMDcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMmQwYWFkYzAzM2VmYTc2NmY3Y2VkMWUzNGJiNTE3YmFhMTg4MTUxZWM4YTcwY2JjZmIzZGJjZTE5MWRhN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-nZks6wCayC-xPwyODZzttbr8FwPKz4Vnbf9yVdvYPg)
> 
> Here is my code:
> 
> ```
> import 'package:flutter/material.dart';
> import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';
> 
> class DocumentViewerScreen extends StatefulWidget {
>   final int docId;
> 
>   const DocumentViewerScreen({
>     super.key,
>     required this.docId,
>   });
> 
>   @override
>   State<DocumentViewerScreen> createState() => _DocumentViewerScreenState();
> }
> 
> class _DocumentViewerScreenState extends State<DocumentViewerScreen> {
>   final GlobalKey<SfPdfViewerState> _pdfViewerKey = GlobalKey();
>   late String link;
> 
>   @override
>   void initState() {
>     super.initState();
> 
>     link = 'EMPTY_LINK';
>     print(link);
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: const Text('Syncfusion Flutter PdfViewer'),
>         actions: <Widget>[
>           IconButton(
>             icon: const Icon(
>               Icons.bookmark,
>               color: Colors.blue,
>             ),
>             onPressed: () {
>               _pdfViewerKey.currentState?.openBookmarkView();
>             },
>           ),
>         ],
>       ),
>       body: SfPdfViewer.network(
>         link,
>         onDocumentLoadFailed: (PdfDocumentLoadFailedDetails pdfDocumentLoadFailedDetails) {
>           print(pdfDocumentLoadFailedDetails.error);
>           print(pdfDocumentLoadFailedDetails.description);
>         },
>         key: _pdfViewerKey,
>       ),
>     );
>   }
> }
> ```

We tried to replicate the issue on our end with some of the URLs that we have on our end but unfortunately, we couldn't reproduce the issue. We suspect that the PDF document might be encrypted internally, these types of documents could cause this issue. Can you share the document URL, so that we can analyze the document further and provide a better solution at the earliest?

**Comment by ramkumarsync** [comment] 2024-02-14 11:15
> I'm having the same issue in iOS (Flutter: 3.16.0, syncfusion_flutter_pdfviewer: ^24.1.44) It only happens with the attached file (a Google spreadsheet downloaded as a PDF). [spreadsheet.pdf](https://github.com/syncfusion/flutter-widgets/files/13824515/spreadsheet.pdf)

We have checked the same case with the document you shared and the document is loading properly in the syncfusion_flutter_pdfviewer. Please try with our latest version (v24.2.5) and let us know if the issue persists. 

![spreadsheet](https://github.com/syncfusion/flutter-widgets/assets/74192192/9df361f9-1258-498b-975f-363cea70ee9d)

**Comment by ramkumarsync** [comment] 2024-03-14 06:31
We believe that the issue has been resolved after upgrading to the version suggested; hence, we are closing this. However, you can reopen this issue anytime if you need any further assistance on this.

**Closed by ramkumarsync** 2024-03-14 06:31 UTC
Labels: pdf_viewer, waiting for customer
