### ISSUE TITLE
SFDataGrid - Range Error when collapsing group of columns

### ISSUE THREAD

**Issue by litterature** [syncfusion/flutter-widgets#2096] opened 2024-09-25 19:23 UTC
### Bug description

When I add column group programmatically and then I click on the collapsing icon (on group row), an exception occurs.

### Steps to reproduce

1. Add column group
2. Click on collapse button of the group

### Code sample

<details open><summary>Code sample</summary>

```dart
void _initGrouping() {
    final groupedColumns = _gridPreferences.groupedColumns.toList();

    for (final groupedColumn in groupedColumns) {
      final column =
          widget.columns.firstWhereOrNull((x) => x.key == groupedColumn);

      if (column == null) {
        continue;
      }

      _gridSource.addColumnGroup(
        ColumnGroup(
          name: column.title,
          sortGroupRows: true,
        ),
      );
    }
}
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

![image](https://github.com/user-attachments/assets/f4f389c6-7fac-43ce-8196-542acad3ddcb)

![image](https://github.com/user-attachments/assets/9ab9a73c-8241-4ac6-8b41-fd12b6b3db74)

![image](https://github.com/user-attachments/assets/f005d1ed-ec86-4374-bde2-d1270f6a4175)

![image](https://github.com/user-attachments/assets/7037d560-532a-44fc-addc-456dc019c396)

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
======== Exception caught by widgets library =======================================================
The following RangeError was thrown building ScrollViewWidget(state: _ScrollViewWidgetState#9b13a):
RangeError (length): Invalid value: Not in inclusive range 0..706: 707

The relevant error-causing widget was: 
  Grid:file:///C:/Users/[username]/dev/grid.dart:65:12
When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart)
#1      isCaptionSummaryRow (package:syncfusion_flutter_datagrid/src/datagrid_widget/helper/datagrid_helper.dart:279:62)
#2      ColumnSizer._getCellWidth (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/column.dart:678:21)
#3      ColumnSizer._calculateCellWidth (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/column.dart:662:26)
#4      ColumnSizer._calculateAllCellsExceptHeaderWidth (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/column.dart:613:26)
#5      ColumnSizer._calculateAllCellsWidth (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/column.dart:594:9)
#6      ColumnSizer._getWidthBasedOnColumn (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/column.dart:582:17)
#7      ColumnSizer._setWidthBasedOnGrid (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/column.dart:524:40)
#8      ColumnSizer._sizerColumnWidth (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/column.dart:458:5)
#9      ColumnSizer._ensureColumnVisibility (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/column.dart:354:5)
#10     ColumnSizer._refresh (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/column.dart:332:5)
#11     refreshColumnSizer (package:syncfusion_flutter_datagrid/src/datagrid_widget/runtime/column.dart:1261:15)
#12     _ScrollViewWidgetState._updateColumnSizer (package:syncfusion_flutter_datagrid/src/datagrid_widget/widgets/scrollview_widget.dart:157:7)
#13     _ScrollViewWidgetState.build (package:syncfusion_flutter_datagrid/src/datagrid_widget/widgets/scrollview_widget.dart:1092:9)
#14     StatefulElement.build (package:flutter/src/widgets/framework.dart:5729:27)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5617:15)
#16     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#18     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#20     _LayoutBuilderElement._rebuildWithConstraints.updateChildCallback (package:flutter/src/widgets/layout_builder.dart:207:18)
#21     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3038:19)
#22     _LayoutBuilderElement._rebuildWithConstraints (package:flutter/src/widgets/layout_builder.dart:231:12)
#23     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2719:59)
#24     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1098:15)
#25     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2719:14)
#26     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:278:5)
#27     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:369:5)
#28     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#32     RenderLeaderLayer.performLayout (package:flutter/src/rendering/proxy_box.dart:4751:11)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:21)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#36     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:291:14)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:2608:7)
#38     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:61:11)
#39     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:985:73)
#40     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:1051:32)
#41     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2446:7)
#42     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1052:18)
#43     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1065:15)
#44     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:602:23)
#45     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1164:13)
#46     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#47     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#48     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#49     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#50     _invoke (dart:ui/hooks.dart:312:13)
#51     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#52     _drawFrame (dart:ui/hooks.dart:283:31)
====================================================================================================
```

</details>

### On which target platforms have you observed this bug?

Windows

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [version 10.0.22631.4169], locale fr-CA)
    • Flutter version 3.24.0 on channel stable at C:\Users\[username]\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (8 weeks ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\[username]\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = C:\Users\[username]\AppData\Local\Android
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.9.7)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.9.34902.65
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] IntelliJ IDEA Community Edition (version 2024.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.2.1
    • Flutter plugin version 80.0.2
    • Dart plugin version 242.20629

[√] IntelliJ IDEA Community Edition (version 2024.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2024.2
    • Flutter plugin version 81.1.3
    • Dart plugin version 242.22855.32

[√] VS Code (version 1.93.1)
    • VS Code at C:\Users\[username]\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.96.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.22631.4169]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 129.0.6668.70
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 129.0.2792.52

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by abineshPalanisamy** [comment] 2024-09-26 05:34
Hi @litterature ,
 
Based on the information provided, we conducted tests using a simple sample to replicate the reported issues. However, we were unable to reproduce the problems as described. We have tested this scenario using the attached sample, and it worked correctly without any issues. Additionally, we have included a video of the test.
 
If you are still experiencing the same problem, we kindly request that you modify the attached sample to reproduce the issue. Additionally, please provide further details about where you are calling the **_initGrouping()** method, the **properties enabled** in SfDataGrid, and clearly **outline the steps to replicate the issue**. This will greatly assist us in investigating the matter further and providing a prompt and appropriate solution.

- **Sample :**  [SfDataGrid.zip](https://github.com/user-attachments/files/17143208/SfDataGrid.zip)

 
Regards,
Abinesh P

**Comment by litterature** [comment] 2024-09-26 13:39
Hi!

I finally found the source. When I set SfDataGrid.columnWidthCalculationRange to ColumnWidthCalculationRange.allRows, the problem occurs. If I put the default ColumnWidthCalculationRange.visibleRows, all work!

**Comment by litterature** [comment] 2024-09-26 14:07
Two parameters seem in cause: ColumnWidthCalculationRange and  allowMultiColumnSorting. I was able to reproduce the error with the sample you provided.

```dart
class _MyHomePageState extends State<MyHomePage> {
  List<Employee> employees = <Employee>[];
  late EmployeeDataSource employeeDataSource;
  List<String> groupedColumns = ['salary'];
  List<GridColumn> columns = [];

  @override
  void initState() {
    super.initState();
    employees = getEmployeeData();
    columns = getColumns();
    employeeDataSource = EmployeeDataSource(employeeData: employees);
  }

  void _initGrouping() {
    for (final groupedColumn in groupedColumns) {
      final column =
          columns.firstWhereOrNull((x) => x.columnName == groupedColumn);

      if (column == null) {
        continue;
      }

      employeeDataSource.addColumnGroup(
        ColumnGroup(
          name: column.columnName,
          sortGroupRows: true,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Syncfusion Flutter DataGrid'),
      ),
      body: Column(
        children: [
          Align(
            alignment: Alignment.centerLeft,
            child: Padding(
              padding: const EdgeInsets.all(5),
              child: ElevatedButton(
                onPressed: _initGrouping,
                child: const Text('Group Columns'),
              ),
            ),
          ),
          Expanded(
            child: SfDataGrid(
              source: employeeDataSource,
              allowExpandCollapseGroup: true,
              allowFiltering: true,
              allowSorting: true,
              columnWidthMode: ColumnWidthMode.auto,
              allowTriStateSorting: true,
              allowMultiColumnSorting: true,
              columnWidthCalculationRange: ColumnWidthCalculationRange.allRows,
              columns: columns,
            ),
          ),
        ],
      ),
    );
  }
```
The sample modified to cause the error:
[SfDataGrid_mod.zip](https://github.com/user-attachments/files/17149924/SfDataGrid_mod.zip)

**Comment by abineshPalanisamy** [comment] 2024-09-27 14:28
Hi @litterature ,
 
We have checked your query at our end, and we are able to replicate that issue at our end. We have considered this as a  bug and logged a bug report regarding this in our feedback portal. We will fix the reported issue and include the changes in our upcoming weekly patch release, which is expected to be rolled out on October 15, 2024. We will let you know once released, and we appreciate your patience until then. 
 
Disclaimer: Inclusion of this solution in the weekly release may change due to other factors including but not limited to QA checks and works reprioritization.
 
 
Regards,
Abinesh P

**Comment by litterature** [comment] 2024-09-27 20:08
Ok! Thank you!

**Comment by abineshPalanisamy** [comment] 2024-10-15 05:49
Hi @litterature ,
 
We are glad to inform you that the reported problem has been resolved on our end. Therefore, kindly update SfDataGrid to the latest version([27.1.53](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpub.dev%2Fpackages%2Fsyncfusion_flutter_datagrid&data=05%7C02%7Cabinesh.palanisamy%40syncfusion.com%7C07bfb447d6874d91407f08dcecdac18c%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C638645671689444407%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=yTlGXziU3wZKdar%2Fd5%2FYlLyKBgofJBot7JDW7SGk%2BhE%3D&reserved=0)). 
 
Root cause : Apart from the lastColumnFill, the other column width modes behave the same as when we perform drag and drop on a column. When we perform drag and drop, the width for the lastColumnFill needs to be recalculated to match the main columnWidthMode. As a result, recalculation occurs whenever an action is performed on the UI. For row calculation involving grouping, we use **displayElements.length**, which maintains the entire group's length regardless of whether it's collapsed or expanded. This length can cause a range exception when the group is collapsed or expanded.

If you have any further queries, please don't hesitate to reach out. We are more than happy to assist you.

Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment] 2024-10-29 04:14
Hi @litterature,

We suspect that the reported issue has been resolved at your end. Hence, we are closing this issue. If you need any further assistance, please reopen this. We are always happy to help.
 
Regards,
Ashok K

**Closed by ashok-kuvaraja** 2024-10-29 04:14 UTC
Labels: data grid, waiting for customer response
