### ISSUE TITLE
Scatter Chart - shape: DataMarkerType.image - infinite unnecessary rebuilds

### ISSUE THREAD

**Issue by FisherWL** [syncfusion/flutter-widgets#282] opened 2021-06-18 23:02 UTC
when using local image as scatter, and define: `shape: DataMarkerType.image,`
dart devtools performance overlay shows flutter rebuilds the static page --- all the time.

```
ScatterSeries<_SalesData, String>(
                  dataSource: data,
                  xValueMapper: (_SalesData sales, _) => sales.year,
                  yValueMapper: (_SalesData sales, _) => sales.sales,
                  name: 'Sales',
                  markerSettings: MarkerSettings(
                    height: 8,
                    width: 8,
                    image: const AssetImage('icon/football.png'),
                    shape: DataMarkerType.image,
                  ),
                )
              ]
```
the following gif shows the issue:
![2021-06-18 15 39 53](https://user-images.githubusercontent.com/57275868/122622272-06cba280-d04d-11eb-8b1e-2b0c5c96d093.gif)

the following gif shows the normal status(page only rebuilds when there's interaction):
![2021-06-18 15 59 51](https://user-images.githubusercontent.com/57275868/122622728-8017c500-d04e-11eb-8846-f466e0eab254.gif)

**Comment by Dharanipalani** [comment] 2021-06-21 14:15
Hi @FisherWL,

Thanks for the interest in our Flutter charts. We have analyzed your scenario and will update you the details on June 23, 2021, and we appreciate your patience until then.

Thanks,
Dharanitharan. P

**Comment by Dharanipalani** [comment] 2021-06-23 11:22
Hi @FisherWL,

We were able to reproduce the reported issue, and this fix will be included in the main version, which is scheduled to be released on June 25, 2021, and we appreciate your patience until then.

Thanks,
Dharanitharan. P

**Comment by Dharanipalani** [comment] 2021-06-28 05:03
Hi @FisherWL,

We regret for the inconvenience that occurs. Due to some technical glitches, the main release will be postponed to June 30, 2021, and we appreciate your patience until then.

Thanks,
Dharanitharan. P

**Comment by Dharanipalani** [comment] 2021-06-30 13:24
Hi @FisherWL,

Thanks for being patience and we are glad to inform you that the reported issue has been resolved in the latest version of our charts. Now, the scatter series does not rebuild and to resolve this upgrade our charts to the latest version from the below link.

Latest version: [https://pub.dev/packages/syncfusion_flutter_charts/versions/19.2.44+1](https://pub.dev/packages/syncfusion_flutter_charts/versions/19.2.44+1)

Thanks,
Dharanitharan. P

**Closed** 2021-07-02 03:31 UTC

**Comment by FisherWL** [comment] 2021-07-04 00:12
thank you.
