### ISSUE TITLE
Page curl animation 

### ISSUE THREAD

**Issue by deshmukhdhiraj** [syncfusion/flutter-widgets#1854] opened 2024-05-09 03:40 UTC
### Use case

Please add page curl animation when we swipe pages from PDF.

### Proposal

Please add page curl animation when we swipe pages from PDF

**Comment by VijayakumarMariappan** [comment] 2024-05-09 06:09
Duplicate of https://github.com/syncfusion/flutter-widgets/issues/1854

**Closed by VijayakumarMariappan** 2024-05-09 06:09 UTC
