### ISSUE TITLE
[syncfusion_flutter_datagrid] Android back key doesn't work , while user select one cell and open dialog and press system back 

### ISSUE THREAD

**Issue by pateljay10000** [syncfusion/flutter-widgets#1556] opened 2023-12-02 12:20 UTC
SfDataGrid(
                    verticalScrollPhysics: const NeverScrollableScrollPhysics(),
                    columnWidthMode: ColumnWidthMode.auto,
                    gridLinesVisibility: GridLinesVisibility.both,
                    headerGridLinesVisibility: GridLinesVisibility.both,
                    headerRowHeight: 40,
                    shrinkWrapRows: true,
                    source: dataSource!,
                    columns: showColumn,
                    onCellTap: (DataGridCellTapDetails details) async {
                      int value = await getfkECLFormPlanningControlDetailGlCode(
                          details.rowColumnIndex);
                      if (value != -1) {
                        getPopUp(details.rowColumnIndex);
                      }
                    },
                    )
                    
Now, run the the below step.

1) Tap on Cell 
2) Open Dialog 
3) Press Android Back --> Hide keyboard 
4) Again press Android back or Select some rows on the grid (select some items)
Now, press the back button.

=> Nothing happens as the back button doesn't work.                

Please help

Thanks

**Comment by Tamilarasan-Paranthaman** [comment] 2024-02-09 13:59
Hi @pateljay10000,

We have investigated this case on our end and encountered the same issue you have described. Considering this, we have logged a bug report in our feedback portal. We will fix the reported issue and include the changes in our weekly patch release, which is expected to be rolled out on February 27, 2024. We will let you know once it is published. We appreciate your patience and understanding until then. 

Regards,
Tamilarasan

**Comment by Tamilarasan-Paranthaman** [comment] 2024-02-27 09:07
@pateljay10000,

We are glad to inform you that the reported issue regarding the “Android Back key is not working” has been resolved. This fix has been incorporated into our latest weekly patch release. To benefit from this fix, we recommend updating your DataGrid package to version **24.2.8**.
 
https://pub.dev/packages/syncfusion_flutter_datagrid   

**Root Cause of the issue:** The DataGrid has intercepted the `back` key event while it had focus. Consequently, the Android back key operation does not function as intended.

We thank you for your support and appreciate your patience in waiting for this update. 

Regards,
Tamilarasan

**Comment by ashok-kuvaraja** [comment] 2024-03-12 13:14
Hi @pateljay10000,

We suspect that the reported issue has been resolved on your end in the mentioned version. Therefore, I am closing this ticket. If you need any further assistance, please feel free to reopen this issue. We are always happy to help you.

Regards, 
Ashok K

**Closed by ashok-kuvaraja** 2024-03-12 13:14 UTC
Labels: bug, data_grid, solved
