### ISSUE TITLE
Panic  when search text  in big pdf file 

### ISSUE THREAD

**Issue by SobolevWladimir** [syncfusion/flutter-widgets#456] opened 2021-11-22 05:00 UTC
Hello. I'm make pdf viewer in my app. ( I'm using package  syncfusion flutter_pdfview 19.3.54-beta). It works very good, but when im try  search text in big pdf file happends panic.   
Can you help me ?
output console: 
```bash
E/flutter ( 1131): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Unsupported operation: Infinity or NaN toInt
E/flutter ( 1131): #0      double.toInt (dart:core-patch/double.dart:219:36)
E/flutter ( 1131): #1      double.round (dart:core-patch/double.dart:182:34)
E/flutter ( 1131): #2      _XObjectElement._render (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/xobject_element.dart:100:56)
E/flutter ( 1131): #3      _ImageRenderer._getXObject (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/image_renderer.dart:543:60)
E/flutter ( 1131): #4      _ImageRenderer._renderAsImage (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/image_renderer.dart:397:15)
E/flutter ( 1131): #5      PdfTextExtractor._searchInBackground (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:495:18)
E/flutter ( 1131): #6      PdfTextExtractor._findTextFromRange (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:229:11)
E/flutter ( 1131): #7      PdfTextExtractor._findText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:185:16)
E/flutter ( 1131): #8      PdfTextExtractor.findText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:120:12)
E/flutter ( 1131): #9      SfPdfViewerState._handleControllerValueChange (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:2476:44)
E/flutter ( 1131): #10     _ValueChangeNotifier.notifyPropertyChangedListeners (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:3655:15)
E/flutter ( 1131): #11     PdfViewerController.searchText (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:3540:5)
E/flutter ( 1131): #12     _DocumentViewState.search (package:push_app/presentation/document_view.dart:29:26)
```

**Comment by deepika134** [comment] 2021-11-23 02:06
Hi SobolevWladimir,

Thank you for contacting the Syncfusion support.

Based on the provided stack trace, We suspect that the reported issue is maybe document specific. So, kindly share the PDF document in which you are facing the issue and also share the following details, to reproduce the reported issue in our end. 
1. Platforms in which the issue is reproduced (Android, iOS, Web, macOS). 
2. Device Specification. 
3. Flutter Doctor log. 
4. syncfusion_flutter_pdfviewer package version. 
5. Flutter SDK version.

This will be helpful to investigate further and provide the solution at the earliest. 

Regards,
Deepika Ravi.

**Comment by SobolevWladimir** [comment] 2021-11-23 14:15
exsample file: https://pushapp.wkrs.ru/test/test3.pdf

**Comment by deepika134** [comment] 2021-11-26 03:06
Hi SobolevWladimir,

kindly upgrade to the latest version of syncfusion_flutter_pdfviewer package to get the issue resolved.
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.3.55-beta 
Please try this and let us know if you need any further assistance.

Regards,
Deepika Ravi

**Comment by SobolevWladimir** [comment] 2021-11-26 12:31
i'm updated package,  then run program  in emulator and the error is still there.    

```bash 
E/flutter ( 7014): #0      _FontStructure.getFontName (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/font_structure.dart:1033:58)
E/flutter ( 7014): #1      _FontStructure.fontName (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/font_structure.dart:148:41)
E/flutter ( 7014): #2      _PdfPageResources.isSameFont.<anonymous closure>.<anonymous closure> (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/page_resource_loader.dart:210:30)
E/flutter ( 7014): #3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
E/flutter ( 7014): #4      _PdfPageResources.isSameFont.<anonymous closure> (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/page_resource_loader.dart:209:23)
E/flutter ( 7014): #5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
E/flutter ( 7014): #6      _PdfPageResources.isSameFont (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/page_resource_loader.dart:208:21)
E/flutter ( 7014): #7      _ImageRenderer._renderTextElementWithSpacing (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/image_renderer.dart:687:42)
E/flutter ( 7014): #8      _ImageRenderer._renderAsImage (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/image_renderer.dart:317:17)
E/flutter ( 7014): #9      PdfTextExtractor._searchInBackground (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:495:18)
E/flutter ( 7014): #10     PdfTextExtractor._findTextFromRange (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:229:11)
E/flutter ( 7014): #11     PdfTextExtractor._findText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:185:16)
E/flutter ( 7014): #12     PdfTextExtractor.findText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:120:12)
E/flutter ( 7014): #13     SfPdfViewerState._handleControllerValueChange (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:2476:44)
E/flutter ( 7014): #14     _ValueChangeNotifier.notifyPropertyChangedListeners (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:3655:15)
E/flutter ( 7014): #15     PdfViewerController.searchText (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:3540:5)
E/flutter ( 7014): #16     _DocumentViewState.search (package:push_app/presentation/document_view.dart:29:26)

```

**Comment by deepika134** [comment] 2021-11-30 13:15
Hi SobolevWladimir,
  
We tried to reproduce the reported issue with provided details, but the text search is working properly without any exception. We have prepared a sample for your reference and attached the output screen record of sample which can be downloaded in the following link , https://www.syncfusion.com/downloads/support/directtrac/general/ze/sample-362287973.zip 
If you still reproduce the reported issue in your use case, then kindly share the modified issue reproducing in sample which will be helpful for us to provide a prompt solution at the earliest.
 
Regards, 
Deepika Ravi

**Comment by SobolevWladimir** [comment] 2021-12-02 10:51
Thanks. Your example does work without error. I will look for mistakes in myself

**Comment by SobolevWladimir** [comment] 2021-12-06 13:32
Perhaps you can help me. In file syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/xobject_element.dart:100.  The variable  a sometimes becomes larger than 1. then an error occurs  in the asos (s)

**Comment by deepika134** [comment] 2021-12-08 03:11
Hi Wladimir,

We have confirmed the reported issue with “Unsupported exception thrown while extract text with bounds from particular PDF document” is defect. We will include the fix for this issue in our upcoming weekly release which will be available on 14th December 2021.

You can track the status of this issue fix by https://www.syncfusion.com/feedback/30957/unsupported-exception-thrown-while-extract-text-with-bounds-from-particular-pdf 

However, we request you to provide an input PDF document which is used to reproduce this issue in your end. It will help us to provide the prompt solution.

Regards,
Deepika Ravi

**Comment by SobolevWladimir** [comment] 2021-12-08 09:32
I attached the document above. it's weird, but the code in your example works without error, but errors appear in my project. I don’t know why. Perhaps the reason is the size of the project. (number of pages)

**Comment by deepika134** [comment] 2021-12-15 13:02
Hi Wladimir,

Sorry for this inconvenience caused.

We have fixed the reported issue with “**Unsupported exception thrown while extract text with bounds from particular PDF document**” and It will be available on our 2021 Volume 4 main release which will be available on 17th December 2021.

Regards,
Deepika Ravi

**Comment by deepika134** [comment] 2021-12-20 07:11
Hi Wladimir, 

We have included the fix for this issue “Unsupported exception thrown while extract text with bounds from particular PDF document” in our latest volume 4 release, so kindly upgrade to the latest version v19.4.38 to get the issue resolved.    
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.4.38-beta 

We are glad to announce that our Essential Studio 2021 Volume 4 Main Release V19.4.0.38 is rolled out and is available for download under the following link.
https://www.syncfusion.com/forums/171304/essential-studio-2021-volume-4-main-release-v19-4-0-38-is-available-for-download 

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,  
Deepika Ravi

**Closed** 2022-01-10 06:35 UTC
