### ISSUE TITLE
[syncfusion_flutter_pdfviewer] Invalid display character "N" 

### ISSUE THREAD

**Issue by ayuamelia** [syncfusion/flutter-widgets#966] opened 2022-11-09 03:15 UTC
I tried to load PDF from network URL. In the original document everything seems right. But if the PDF document contains character "N" with capital bold letters, it always turns into invalid character (seems like J or I). I have tried to load other PDF documents, but the issue still comes up. 

And here is my code:

```
SfPdfViewer.network(
   pdfUrl!,
   pageLayoutMode: PdfPageLayoutMode.continuous,
   enableDoubleTapZooming: true,
   enableHyperlinkNavigation: true,
   enableTextSelection: true,
   canShowHyperlinkDialog: true,
   onTextSelectionChanged:
   (PdfTextSelectionChangedDetails details) {
       if (details.selectedText == null &&
           overlayEntry != null) {
           overlayEntry!.remove();
           overlayEntry = null;
       } else if (details.selectedText != null &&
            overlayEntry == null) {
            copySelectedText(context, details);
       }
    },
)
```

![ori](https://user-images.githubusercontent.com/59279327/200755883-86dafb6d-7179-4e78-a452-24a1de848828.jpeg)

![app](https://user-images.githubusercontent.com/59279327/200984434-c3e9c97b-afb5-49c8-bd6c-6cc914a0599e.jpeg)

**Comment by deepika134** [comment] 2023-01-11 03:52
We tried to replicate the issue with provided details, but text search is working fine in our side. We have attached the sample for your reference (along with the output screenshot) which can be downloaded from the attachment. If you still reproduce the reported issue in your use case, then kindly share the modified issue reproducing in sample and also, please share the following details, to reproduce the reported issue on our end.

- syncfusion_flutter_pdfviewer package version.
- Flutter SDK version.
- Issue reproducing steps.
- Issue reproducing document

This information will be helpful for us to provide you a prompt solution at the earliest.
[sample.zip](https://github.com/syncfusion/flutter-widgets/files/10388744/sample.zip)

**Comment by hmbadhon** [comment] 2023-01-22 11:33
@deepika134 
Pdf search not working in flutter web

sample code:

SfPdfViewer.network(
                    pdfModel!.fileUrl!,
                    controller: _pdfViewerController,
                    enableDoubleTapZooming: false,
                    canShowScrollStatus: false,
                    canShowPaginationDialog: false,
                    canShowScrollHead: false,
                    enableTextSelection: false,
                    enableDocumentLinkAnnotation: false,
                    canShowHyperlinkDialog: false,
                    enableHyperlinkNavigation: false,
                    canShowPasswordDialog: false,
                    onDocumentLoaded: (details) {
                      setState(() {});
                    },
                    onDocumentLoadFailed: (failed) {
                      setState(() {
                        isPdfLoadFailed = true;
                      });
                    },
                    onPageChanged: (callback) {
                      setState(() {});
                    },
                  ),

see screen recoding browser got stack :

https://user-images.githubusercontent.com/24831033/213913545-7ce3d712-fa98-4a1c-8a5b-bba71ddcd07a.mp4

**Comment by deepika134** [comment] 2023-02-01 03:37
Hi @hmbadhon , As we mentioned earlier, we tried to replicate the issue with provided details, but text search is working fine in our side. please share the following details, to reproduce the reported issue on our end.

- syncfusion_flutter_pdfviewer package version.
- Flutter SDK version.
- Issue reproducing steps.
- Issue reproducing document

This information will be helpful for us to provide you a prompt solution at the earliest.

**Comment by okbye123** [comment] 2023-03-17 12:08
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA

**Comment by ramkumarsync** [comment] 2024-02-07 11:49
We are closing this issue since we don't have enough information to reproduce it. You can reopen this anytime and share the proper issue reproducing sample and the details to proceed further.

**Closed by ramkumarsync** 2024-02-07 11:49 UTC
Labels: pdf_viewer
