### ISSUE TITLE
SFDataGrid horizontal scroll throws exception

### ISSUE THREAD

**Issue by berslen** [syncfusion/flutter-widgets#1743] opened 2024-03-18 18:21 UTC
Aftera adding 3 frozen columns, and set column fit mode to fitbycolumnName (or auto). horizonral scroll throws the following exception.

> ════════ Exception caught by animation library ═════════════════════════════════
> The following assertion was thrown while notifying status listeners for AnimationController:
> 'package:flutter/src/widgets/overlay.dart': Failed assertion: line 1544 pos 14: '_zOrderIndex != null': is not true.
> 
> Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
> In either case, please report this assertion by filing a bug on GitHub:
>   https://github.com/flutter/flutter/issues/new?template=2_bug.yml
> 
> When the exception was thrown, this was the stack:
> #2      OverlayPortalController.hide (package:flutter/src/widgets/overlay.dart:1544:14)
> overlay.dart:1544
> #3      TooltipState._handleStatusChanged (package:flutter/src/material/tooltip.dart:482:28)
> tooltip.dart:482
> #4      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:240:19)
> listener_helpers.dart:240
> #5      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:850:7)
> animation_controller.dart:850
> #6      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:866:5)
> animation_controller.dart:866
> #7      Ticker._tick (package:flutter/src/scheduler/ticker.dart:258:12)
> ticker.dart:258
> #8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
> binding.dart:1386
> #9      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1233:11)
> binding.dart:1233
> #10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
> compact_hash.dart:633
> #11     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1231:17)
> binding.dart:1231
> #12     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1148:5)
> binding.dart:1148
> #16     _invoke1 (dart:ui/hooks.dart:330:10)
> hooks.dart:330
> #17     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:361:5)
> platform_dispatcher.dart:361
> #18     _beginFrame (dart:ui/hooks.dart:272:31)
> hooks.dart:272
> (elided 5 frames from class _AssertionError and dart:async)
> 
> The AnimationController notifying status listeners was: AnimationController#35d3c(⏮ 0.000; paused)
>

**Comment by abineshPalanisamy** [comment] 2024-03-19 11:43
Hi @berslen ,
 
Based on the information you have provided, we have been unable to reproduce the reported issue on our end. In order to further investigate the problem, we kindly request that you provide us with the specific sample that is causing the issue. Additionally, please provide the SfDataGrid and Flutter versions, as well as the platform on which you are facing the issue. This will greatly help us understand your requirements and provide you with an appropriate solution as quickly as possible.
 
 
Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment] 2024-04-05 05:45
Hi @berslen,

We hope that the reported issue is resolved in your end. We are closing this issue now. If you need any further assistance, kindly reopen this ticket. We are always happy to help you.

Regards,
Ashok K

**Closed by ashok-kuvaraja** 2024-04-05 05:45 UTC
Labels: data_grid, waiting for customer response
