### ISSUE TITLE
Regression: RangeController not working with DateTimeAxis

### ISSUE THREAD

**Issue by DrNiels** [syncfusion/flutter-widgets#1782] opened 2024-04-02 15:10 UTC
I try to use a rangeController on a DateTimeAxis, but it seems like it immediately converts the DateTime object into an int and fails.

Consider this minimal example:
````
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_charts/charts.dart';
import 'package:syncfusion_flutter_core/core.dart';

void main() async {
  runApp(
    MaterialApp(
      home: TestChart(),
    ),
  );
}

class TestChart extends StatefulWidget {
  static List<Offset> allData = [
    Offset(0, 0),
    Offset(1, 10),
    Offset(2, 2),
    Offset(3, 13),
    Offset(4, 4),
    Offset(5, 15),
    Offset(6, 6),
    Offset(7, 17),
    Offset(8, 8),
    Offset(9, 19),
    Offset(10, 10),
  ];

  _TestChartState createState() => _TestChartState();
}

class _TestChartState extends State<TestChart> {
  RangeController rangeController = RangeController(start: DateTime(2003), end: DateTime(2005),);

  @override
  Widget build(BuildContext context) {
    return SfCartesianChart(
      series: [
        SplineSeries<Offset, DateTime>(
          xValueMapper: (data, _) => DateTime((2000 + data.dx).round()),
          yValueMapper: (data, _) => data.dy,
          dataSource: TestChart.allData,
          markerSettings: MarkerSettings(
            isVisible: true,
          ),
        ),
      ],
      primaryXAxis: DateTimeAxis(
        name: 'xAxis',
        minimum: DateTime(2000),
        maximum: DateTime(2010),
        initialVisibleMinimum: rangeController.start,
        initialVisibleMaximum: rangeController.end,
        rangeController: rangeController,
      ),
    );
  }
}
````

After an initial working render, an error is thrown:
````
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following _TypeError was thrown while dispatching notifications for RangeController:
TypeError: 1041375600000: type 'int' is not a subtype of type 'DateTime?'

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3  throw_
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1385:3                         _failedAsCheck
dart-sdk/lib/_internal/js_shared/lib/rti.dart 1375:3                         _generalNullableAsCheckImplementation
packages/syncfusion_flutter_charts/src/charts/axis/datetime_axis.dart 430:5  [_handleRangeControllerChange]
packages/flutter/src/foundation/change_notifier.dart 433:24                  notifyListeners
packages/syncfusion_flutter_core/src/slider_controller.dart 213:7            set start
packages/syncfusion_flutter_charts/src/charts/axis/axis.dart 1978:9          [_calculateRangeAndInterval]
packages/syncfusion_flutter_charts/src/charts/axis/axis.dart 1772:7          performLayout
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/syncfusion_flutter_charts/src/charts/base.dart 1961:13              measureHorizontalAxes
packages/syncfusion_flutter_charts/src/charts/base.dart 1999:5               performLayout
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/syncfusion_flutter_charts/src/charts/base.dart 771:23               performLayout
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/syncfusion_flutter_charts/src/charts/common/core_legend.dart 989:5  performLayout
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/shifted_box.dart 239:5                        performLayout
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/shifted_box.dart 239:5                        performLayout
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/proxy_box.dart 3728:13                        performLayout
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/widgets/overlay.dart 968:12                             layoutChild
packages/flutter/src/widgets/overlay.dart 1282:9                             performLayout
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/custom_paint.dart 569:11                      performLayout
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/proxy_box.dart 105:21                         <fn>
packages/flutter/src/rendering/object.dart 2575:7                            layout
packages/flutter/src/rendering/box.dart 2389:11                              layout
packages/flutter/src/rendering/view.dart 195:7                               performLayout
packages/flutter/src/rendering/object.dart 2414:7                            [_layoutWithoutResize]
packages/flutter/src/rendering/object.dart 1051:17                           flushLayout
packages/flutter/src/rendering/object.dart 1064:14                           flushLayout
packages/flutter/src/rendering/binding.dart 582:5                            drawFrame
packages/flutter/src/widgets/binding.dart 991:13                             drawFrame
packages/flutter/src/rendering/binding.dart 448:5                            [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1386:7                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1311:9                           handleDrawFrame
packages/flutter/src/scheduler/binding.dart 1034:7                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:11      internalCallback

The RangeController sending notification was:
  RangeController#9ea13
════════════════════════════════════════════════════════════════════════════════════════════════════
````

This seems to be a regression as the example above works fine with 25.1.37, but not with 25.1.38

I use Flutter in Web.
My output of flutter doctor is:
````

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.19045.4170], locale de-DE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc4)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.6)
[√] Android Studio (version 2021.2)
[√] VS Code, 64-bit edition (version 1.87.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
````

**Comment by LokeshPalani** [comment] 2024-04-09 05:21
Hi @DrNiels,

 

We can reproduce the reported issue regarding the **‘Exception thrown when set rangeController in the DateTimeAxis'** at our end. We will fix and include this issue in our upcoming **weekly patch release**, which is expected to be rolled out on **April 23, 2024.** We will notify you once it has been rolled out. We appreciate your patience until then. 

 

Regards,
Lokesh P.

**Comment by LokeshPalani** [comment] 2024-04-24 08:27
Hi @DrNiels,

 

We would like to let you know that the reported issue is fixed and rolled out in our patch release. We kindly request you to upgrade the syncfusion_flutter_charts package to the latest version below. 

 

 **Version:** https://pub.dev/packages/syncfusion_flutter_charts/versions/25.1.41+1

 

**Root cause:** Milliseconds values are assigned to rangeController start and end properties instead of DateTime value for DateTimeAxis.  

 

If you have any further queries, please feel free to reach out to us.

 

Regards,
Lokesh P.

**Closed** 2024-04-25 17:09 UTC
Labels: bug, charts, waiting for customer response, fixed
