### ISSUE TITLE
[SFCartersianChart] onPlotAreaSwipe not working

### ISSUE THREAD

**Issue by ench0** [syncfusion/flutter-widgets#1888] opened 2024-05-29 15:52 UTC
### Bug description

I have used an example from [here](https://help.syncfusion.com/flutter/cartesian-charts/callbacks#onplotareaswipe) and [here](https://github.com/syncfusion/flutter-widgets/issues/1508), but they dont seem to work.

This produces no output:

```
SfCartesianChart(
    ...             
    onPlotAreaSwipe: (ChartSwipeDirection direction) =>             
        print('direction is $direction'),
)
```

Any pointers appreciated.

### Steps to reproduce

1. Use the code above within any cartesian chart, it doesn't work on latest flutter - swiping does not seem to trigger the callback.

### Code sample

<details open><summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

void main() {
  return runApp(_ChartApp());
}

class _ChartApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(brightness: Brightness.light, primarySwatch: Colors.blue),
      home: const MyChart(),
    );
  }
}

class MyChart extends StatefulWidget {
  const MyChart({Key? key}) : super(key: key);

  @override
  _MyChartState createState() => _MyChartState();
}

class _MyChartState extends State<MyChart> {
  late List<ChartSampleData> chartData;
  double axisVisibleMin = 1;
  double axisVisibleMax = 3;
  bool isLoad = false;
  late CategoryAxisController _axisController;

  @override
  void initState() {
    chartData = [
      ChartSampleData(0, 5),
      ChartSampleData(1, 25),
      ChartSampleData(2, 100),
      ChartSampleData(3, 75),
      ChartSampleData(4, 33),
      ChartSampleData(5, 80),
      ChartSampleData(6, 21),
      ChartSampleData(7, 77),
      ChartSampleData(8, 8),
      ChartSampleData(9, 12),
      ChartSampleData(10, 42),
      ChartSampleData(11, 70),
      ChartSampleData(12, 77),
      ChartSampleData(13, 55),
      ChartSampleData(14, 19),
      ChartSampleData(15, 66),
    ];
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: SizedBox(
          height: 500,
          width: 500,
          child: SfCartesianChart(
            primaryXAxis: CategoryAxis(
              initialVisibleMinimum: 0,
              initialVisibleMaximum: 5,
              labelPlacement: LabelPlacement.onTicks,
              interval: 1,
              name: 'primaryXAxis',
              axisLine: const AxisLine(width: 0, color: Colors.transparent),
              edgeLabelPlacement: EdgeLabelPlacement.shift,
              majorGridLines: const MajorGridLines(width: 0),
              onRendererCreated: (CategoryAxisController controller) {
                _axisController = controller;
              },
            ),
            primaryYAxis: const NumericAxis(
              interval: 2,
              minimum: 0,
              maximum: 26,
              isVisible: false,
              axisLine: AxisLine(width: 0),
              majorTickLines: MajorTickLines(color: Colors.transparent),
            ),
            plotAreaBorderWidth: 0,
            series: [
              ColumnSeries<ChartSampleData, num>(
                dataSource: chartData,
                xValueMapper: (ChartSampleData sales, _) => sales.x,
                yValueMapper: (ChartSampleData sales, _) => sales.y,
              ),
            ],
            onPlotAreaSwipe: (ChartSwipeDirection direction) => performSwipe(direction),
          ),
        ),
      ),
    );
  }

  void performSwipe(ChartSwipeDirection direction) {
    print('swiped');
    if (direction == ChartSwipeDirection.end &&
        (axisVisibleMax + 3.toDouble()) < chartData.length) {
      isLoad = true;
      setState(
        () {
          axisVisibleMin = axisVisibleMin + 3.toDouble();
          axisVisibleMax = axisVisibleMax + 3.toDouble();
        },
      );
    } else if (direction == ChartSwipeDirection.start && (axisVisibleMin - 3.toDouble()) >= 0) {
      setState(
        () {
          axisVisibleMin = axisVisibleMin - 3.toDouble();
          axisVisibleMax = axisVisibleMax - 3.toDouble();
        },
      );
    }
  }
}

class ChartSampleData {
  final double x;
  final int y;

  ChartSampleData(this.x, this.y);
}

```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
[Add the Stack Traces here]
```

</details>

### On which target platforms have you observed this bug?

iOS, macOS

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.19.4, on macOS 14.4 23E214 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by LokeshPalani** [comment] 2024-05-30 13:31
Hi @ench0,

We can reproduce the reported issue on our end and the issue is scheduled to be fixed in our **Volume 2 Main Release** on **second week of June**. We will notify you here once the release has been rolled out, and we appreciate your patience in the meantime.

Regards,
Lokesh P.

**Comment by ench0** [comment] 2024-05-30 15:32
Great, thanks very much!

**Comment by LokeshPalani** [comment] 2024-06-11 14:25
Hi @ench0,

Thank you for your patience. The reported issue is fixed and rolled out in our volume 2 main release. To avoid this issue, we kindly request you to upgrade the **syncfusion_flutter_charts** package to the latest version below.

Version Link:  https://pub.dev/packages/syncfusion_flutter_charts/versions/26.1.35  

**Root cause:** Handled the horizontal drag and vertical drag for single pointer interaction for panning, but missed to check the plotAreaSwipe interaction methods, we have used scale methods for single interaction for plot area swipe.

If you have any further queries, please feel free to reach out to us.

Regards,
Lokesh P.

**Closed** 2024-06-24 11:50 UTC
Labels: bug, charts, fixed
