### ISSUE TITLE
the pdfviewer zooms when scrolling up on web

### ISSUE THREAD

**Issue by PascalGehring** [syncfusion/flutter-widgets#993] opened 2022-11-28 09:18 UTC
The pdfviewer zooms instead of going up when scrolling up on web

https://user-images.githubusercontent.com/41545796/204239070-e1189e7f-0af5-4dac-8991-7efd4ff276a1.mov

**Comment by deepika134** [comment] 2023-01-11 03:42
We tried to replicate the issue with provided details, but the scrolling is working fine in our side. We have attached the sample for your reference which can be downloaded from the attachment. If you still reproduce the reported issue in your use case, then kindly share the modified issue reproducing in sample and also, please share the following details, to reproduce the reported issue on our end.

- syncfusion_flutter_pdfviewer package version.
- Flutter SDK version.
- Issue reproducing steps.

This information will be helpful for us to provide you a prompt solution at the earliest.
[pdfviewer_save.zip](https://github.com/syncfusion/flutter-widgets/files/10388706/pdfviewer_save.zip)

**Comment by ramkumarsync** [comment] 2024-02-07 11:50
We are closing this issue since we don't have enough information to reproduce it. You can reopen this anytime and share the proper issue reproducing sample and the details to proceed further.

**Closed by ramkumarsync** 2024-02-07 11:50 UTC
Labels: pdf_viewer
