### ISSUE TITLE
[syncfusion_flutter_signaturepad] Poor performance when use Impeller

### ISSUE THREAD

**Issue by Mairramer** [syncfusion/flutter-widgets#1429] opened 2023-09-25 19:05 UTC
I opened this bug to alert you about the problem with Impeller. Below I will leave two videos, the first without the impeller and the second with the impeller.

https://github.com/syncfusion/flutter-widgets/assets/50643541/ddb693bd-7f9b-4393-b71f-4b258680a463

https://github.com/syncfusion/flutter-widgets/assets/50643541/2621ba41-03d7-4e58-a176-8505ec1693dd

**Comment by pedroafonsouza** [comment] 2023-09-25 19:16
The same is happening to me. Using flutter 3.13.0
@Mairramer can you provision flutter doctor result?

**Comment by Mairramer** [comment] 2023-09-25 19:21
> The same is happening to me. Using flutter 3.13.0 @Mairramer can you provision flutter doctor result?
```
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.0 22A380 darwin-arm64, locale pt-BR)
    • Flutter version 3.13.0 on channel stable at /Users/mairramersilva/fvm/versions/3.13.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (6 weeks ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/mairramersilva/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = /Users/mairramersilva/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/mairramersilva/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2022.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.82.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 13.0 22A380 darwin-arm64
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 116.0.5845.187

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by sfHariHaraSudhan** [comment] 2023-09-26 11:15
Hi @Mairramer,

We have checked the reported issue with [SfSignaturePad](https://pub.dev/documentation/syncfusion_flutter_signaturepad/latest/signaturepad/SfSignaturePad-class.html) and have reproduced it at our end. This issue is replicated with 3.10.0 and later Flutter SDK versions because Flutter Framework uses an impeller rendering engine for iOS by default. Disabling the impeller by following the steps mentioned in the below link can resolve your issue.

Link: https://docs.flutter.dev/perf/impeller#ios

Regards,
Hari Hara Sudhan. K.

**Comment by Mairramer** [comment] 2023-09-26 11:53
Hi @sfHariHaraSudhan,
For now I have disabled it.
I opened an issue on Flutter too, [[Impeller] Poor performance when use Impeller](https://github.com/flutter/flutter/issues/135458).

**Comment by jonahwilliams** [comment] 2023-09-26 18:00
I have a fix for this in https://github.com/flutter/engine/pull/46282 . However, updating the package to use PaintingStyle.stroke will improve performance for both Skia and Impeller.

**Comment by sfHariHaraSudhan** [comment] 2023-09-28 12:53
Hi @Mairramer ,

Okay, Thanks.

Regards,
Hari Hara Sudhan. K.

**Comment by sfHariHaraSudhan** [comment] 2023-09-28 12:54
Hi @jonahwilliams,

Thanks for your suggestion. We will check and consider it from our side based on our use case.

Regards,
Hari Hara Sudhan. K.

**Closed** 2024-02-07 09:51 UTC
