### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by REU8ER** [syncfusion/flutter-widgets#1052] opened 2023-01-27 14:41 UTC
I would like to request the change of dependency image from image: ">=3.0.1 <4.0.0" to image: ">=3.0.1 <5.0.0" in pubspec.yaml, to allow compatibility with other plugins. thanks!

**Comment by jbryanh** [comment] 2023-01-27 19:27
Ditto!

**Comment by KonduruKeerthi** [comment] 2023-02-01 10:20
We have confirmed the issue as **Pub get failed while using the image package version above ^4.0.0** and logged a defect report. We will include the fix for this issue in our weekly NuGet release scheduled for the **second week of February 2023**. You will be informed regarding this once the fix is included.

You can track the status of this defect report through the feedback link below.

https://www.syncfusion.com/feedback/40609/pub-get-failed-while-using-the-image-package-version-above-4-0-0

**Disclaimer:** Inclusion of this solution in the weekly release may change due to other factors including but not limited to QA checks and works reprioritization.

**Comment by RahulBalasundaramSF3494** [comment] 2023-02-10 13:48
We have included the fix for **Pub get failed while using the image package version above ^4.0.0** in our weekly NuGet release **version 20.4.49**. Please upgrade your package to this latest version to resolve the issue.


Latest NuGet Package: https://pub.dev/packages/syncfusion_flutter_xlsio/versions/20.4.49-beta

**Closed** 2024-02-07 09:01 UTC
