### ISSUE TITLE
pdf is not working ,please check it

### ISSUE THREAD

**Issue by engineer-ece** [syncfusion/flutter-widgets#1069] opened 2023-02-05 08:51 UTC
/D:/src/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdf-20.4.48/lib/src/pdf/implementation/forms/pdf_xfdf_document.dart:38:35: Error: The argument type 'String?' can't be assigned to the parameter type 'Object' because 'String?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
        builder.attribute('href', _pdfFilePath);
                                  ^

**Comment by rahulserver** [comment] 2023-02-05 10:02
I am facing the same exact issue with version `20.4.48` (latest currently). Is this plugin version working for anyone?

**Comment by GSORF** [comment] 2023-02-05 14:22
I can confirm this issue with the latest version.

I tried switching between iOS and Android and clearing my pub cache via:
`dart pub cache clean`

Nothing helped. The error log is quite long, maybe it helps when I post the full error:

```
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.4.48/lib/src/widgets/interactive_scroll_viewer.dart:59:9: Error: Type 'PanAxis' not found.
  final PanAxis panAxis;
        ^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.4.48/lib/src/widgets/interactive_scroll_viewer.dart:15:22: Error: Undefined name 'PanAxis'.
      this.panAxis = PanAxis.free,
                     ^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.4.48/lib/src/pdfviewer.dart:1016:54: Error: Method 'readState' cannot be called on 'PageStorageBucket?' because it is potentially null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('../../../Development/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
Try calling using ?. instead.
      final dynamic offset = PageStorage.of(context).readState(context);
                                                     ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.4.48/lib/src/pdfviewer.dart:1020:12: Error: Method 'readState' cannot be called on 'PageStorageBucket?' because it is potentially null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('../../../Development/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
Try calling using ?. instead.
          .readState(context, identifier: 'zoomLevel_${widget.key}');
           ^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.4.48/lib/src/pdfviewer.dart:3244:35: Error: Method 'writeState' cannot be called on 'PageStorageBucket?' because it is potentially null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('../../../Development/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
Try calling using ?. instead.
          PageStorage.of(context).writeState(
                                  ^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdfviewer-20.4.48/lib/src/pdfviewer.dart:3272:35: Error: Method 'writeState' cannot be called on 'PageStorageBucket?' because it is potentially null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart' ('../../../Development/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
Try calling using ?. instead.
          PageStorage.of(context).writeState(
                                  ^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.4.48/lib/src/widgets/interactive_scroll_viewer.dart:59:9: Error: 'PanAxis' isn't a type.
  final PanAxis panAxis;
        ^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_core-20.4.48/lib/src/widgets/interactive_scroll_viewer.dart:299:9: Error: No named parameter with the name 'panAxis'.
        panAxis: widget.panAxis,
        ^^^^^^^
../../../Development/flutter/packages/flutter/lib/src/widgets/interactive_viewer.dart:61:3: Context: Found this candidate, but the arguments don't match.
  InteractiveViewer({
  ^^^^^^^^^^^^^^^^^
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_pdf-20.4.48/lib/src/pdf/implementation/forms/pdf_xfdf_document.dart:38:35: Error: The argument type 'String?' can't be assigned to the parameter type 'Object' because 'String?' is nullable and 'Object' isn't.
 - 'Object' is from 'dart:core'.
        builder.attribute('href', _pdfFilePath);
                                  ^


FAILURE: Build failed with an exception.

* Where:
Script '/Users/USER/Development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/USER/Development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

I am on a M1 MacBook Pro 2020 with MacOS Ventura 13.0.1.

A fix would be highly appreciated!

Kind regards,
Adam

**Comment by GSORF** [comment] 2023-02-05 23:40
FYI:
Duplicate of #1067 and #1064 .

Solution proposed in #1064 is to upgrade the flutter SDK by running 
`flutter upgrade` 

**This worked for me and I am able to now compile my iOS app with the syncfusion SfPDFViewer widget! But before this, I broke my flutter installation and it took me an hour to google for the fixes, so beware of that!**

I do not remember all of the commands, but among these are the following:
- Make sure you are on the "stable" channel by running `flutter channel stable`
- Check your paths on MacOS for double slashes at the beginning of your `dart` and `flutter` executables by running `echo $PATH` . Otherwise you will get an error message about "_Cannot extract a non-Windows file path from a file URI with an authority_".
- Update your flutter pub dependencies using `flutter pub outdated` and `flutter pub upgrade` and then upgrading flutter again using `flutter channel stable` and `flutter upgrade`. Otherwise you get an error message like "_The method 'File.create' doesn't have the named parameter 'exclusive' of overridden method_".
- Update your cocoa pods installation to the latest version using a combination of `flutter clean`, `rm -Rf ios/Pods`, `rm -Rf ios/.symlinks`, `rm -Rf ios/Flutter/Flutter.framework`, `rm -Rf ios/Flutter/Flutter.podspec`, `flutter pub get`, `cd ios`, `arch -x86_64 pod install` (specifically M1 MacOS!), `flutter build ios` and `flutter run`. Otherwise you get the error message "_error running pod install_".

It was quite chaotic and in retrospective I think it would have been easier to just re-install flutter. However, I did not test that.

I hope that this will help you resolving your issues regarding the most recent release of the SF flutter widget.

Kind regards,
Adam

**Comment by abehbatre** [comment] 2023-02-06 04:04
up. same problem here..

**Comment by rahulserver** [comment] 2023-02-06 04:07
Upgrading flutter is way too much hassle. I don't want to break existing dependencies and open another can of worms. 
Would either go for a different library of use a version of this one which is compatiable with my flutter version ( `[✓] Flutter (Channel beta, 3.7.0-1.3.pre, on macOS 12.5 21G72 darwin-x64, locale en-GB)` )

Currently trying to find which version will work for my flutter.

**Comment by abehbatre** [comment] 2023-02-06 04:52
temporary fix: downgrade to:
```
  # syncfusion
  syncfusion_flutter_core: 20.3.59
  syncfusion_flutter_pdf: 20.3.59
  syncfusion_flutter_pdfviewer: 20.3.59
```

**Comment by engineer-ece** [comment] 2023-02-06 06:45
> syncfusion_flutter_core: 20.3.59
>   syncfusion_flutter_pdf: 20.3.59
>   syncfusion_flutter_pdfviewer: 20.3.59

This is working, thank you sir, i checked.  In new version only throwing bug in above

**Comment by irfanajaffer** [comment] 2023-02-06 12:30
<html>
<body>
<p style="box-sizing: border-box; margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif;">We found that the problem is due to the older version of the<span> </span><a href="https://pub.dev/packages/xml/versions" target="_blank" style="box-sizing: border-box; color: rgb(46, 46, 241); text-decoration: none; background-color: transparent; user-select: auto;">xml</a><span> </span>package being referred to in your project. Recently, the<span> </span><a href="https://pub.dev/documentation/xml/latest/xml/XmlBuilder/attribute.html" target="_blank" style="box-sizing: border-box; color: rgb(46, 46, 241); text-decoration: none; background-color: transparent; user-select: auto;">XmlBuilder</a><span> </span>attribute value API has been updated from non-nullable to nullable type; you can refer to the following API reference for further details.</p><p style="box-sizing: border-box; margin: 0px 0px 10px;"><br style="box-sizing: border-box;"></p>

Xml package version 6.2.0 | Xml package version 6.2.2
-- | --
https://pub.dev/documentation/xml/6.2.0/xml/XmlBuilder/attribute.html | https://pub.dev/documentation/xml/latest/xml/XmlBuilder/attribute.html

<p style="box-sizing: border-box; margin: 0px 0px 10px;"><br style="box-sizing: border-box;"></p><p style="box-sizing: border-box; margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif;">So, we request you to update your pub cache by using the following command to resolve the issue.</p><p style="box-sizing: border-box; margin: 0in; background: rgb(33, 33, 33); font-size: 11pt; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box; font-size: 10pt; font-family: &quot;Roboto Mono&quot;; color: rgb(100, 221, 23);">dart pub cache add xml<span> </span></span><span style="box-sizing: border-box; font-size: 10pt; font-family: &quot;Roboto Mono&quot;; color: rgb(153, 187, 0);">--version</span><span style="box-sizing: border-box; font-size: 10pt; font-family: &quot;Roboto Mono&quot;; color: rgb(100, 221, 23);"><span> </span></span><span style="box-sizing: border-box; font-size: 10pt; font-family: &quot;Roboto Mono&quot;; color: rgb(0, 204, 238);">"6.2.2"</span></p><p style="box-sizing: border-box; margin: 0px 0px 10px;"><br style="box-sizing: border-box;"></p><p style="box-sizing: border-box; margin: 0in; font-size: 11pt; font-family: Calibri, sans-serif;">You can refer<span> </span><a href="https://dart.dev/tools/pub/cmd/pub-cache" target="_blank" style="box-sizing: border-box; color: rgb(46, 46, 241); text-decoration: none; background-color: transparent; user-select: auto;">https://dart.dev/tools/pub/cmd/pub-cache</a><span> </span>for more details.</p><p style="box-sizing: border-box; margin: 0px 0px 10px;"><br style="box-sizing: border-box; color: rgba(0, 0, 0, 0.87); font-family: Heebo, &quot;open sans&quot;, sans-serif, -apple-system, BlinkMacSystemFont; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
</body>
</html>

**Comment by scuti-dai** [comment] 2023-03-09 06:43
+1

**Comment by ChieuDev** [comment] 2023-03-09 11:42
it don't working for me. 

> temporary fix: downgrade to:
> 
> ```
>   # syncfusion
>   syncfusion_flutter_core: 20.3.59
>   syncfusion_flutter_pdf: 20.3.59
>   syncfusion_flutter_pdfviewer: 20.3.59
> ```

**Comment by okbye123** [comment] 2023-03-17 12:07
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA

**Comment by chinnumuniyappan** [comment] 2023-04-11 04:39
The reported problem has been resolved in our latest versions.

**Closed by chinnumuniyappan** 2023-04-11 04:39 UTC
