### ISSUE TITLE
Error: Type 'PointerHoverEventListener' not found.

### ISSUE THREAD

**Issue by bawa-ra** [syncfusion/flutter-widgets#184] opened 2021-04-10 09:23 UTC
I had working example withe version 18 however I upgraded my packages to 19 and this error come

my packages are 
```
  syncfusion_flutter_sliders: ^19.1.55-beta
  syncfusion_flutter_datagrid: ^19.1.55-beta
  syncfusion_flutter_core: ^19.1.55
  syncfusion_flutter_charts: ^19.1.55+1
```

```
../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.55-beta/lib/src/range_selector.dart:1862:16: Error: Type 'MouseTrackerAnnotation' not found.
    implements MouseTrackerAnnotation {
               ^^^^^^^^^^^^^^^^^^^^^^
../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.55-beta/lib/src/range_selector.dart:2945:3: Error: Type 'PointerEnterEventListener' not found.
  PointerEnterEventListener? get onEnter => null;
  ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.55-beta/lib/src/range_selector.dart:2949:3: Error: Type 'PointerHoverEventListener' not found.
  PointerHoverEventListener get onHover => _handleHover;
  ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.55-beta/lib/src/range_selector.dart:2952:3: Error: Type 'PointerExitEventListener' not found.
  PointerExitEventListener get onExit => _handleExit;
  ^^^^^^^^^^^^^^^^^^^^^^^^
../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.55-beta/lib/src/range_slider.dart:1655:16: Error: Type 'MouseTrackerAnnotation' not found.
    implements MouseTrackerAnnotation {
               ^^^^^^^^^^^^^^^^^^^^^^
../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.55-beta/lib/src/range_slider.dart:2547:3: Error: Type 'PointerEnterEventListener' not found.
  PointerEnterEventListener? get onEnter => null;
  ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.55-beta/lib/src/range_slider.dart:2551:3: Error: Type 'PointerHoverEventListener' not found.
  PointerHoverEventListener get onHover => _handleHover;
  ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.55-beta/lib/src/range_slider.dart:2554:3: Error: Type 'PointerExitEventListener' not found.
  PointerExitEventListener get onExit => _handleExit;
  ^^^^^^^^^^^^^^^^^^^^^^^^
../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.55-beta/lib/src/slider.dart:1498:57: Error: Type 'MouseTrackerAnnotation' not found.
class _RenderSlider extends RenderBaseSlider implements MouseTrackerAnnotation {
                                                        ^^^^^^^^^^^^^^^^^^^^^^
../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.55-beta/lib/src/slider.dart:1914:3: Error: Type 'PointerEnterEventListener' not found.
  PointerEnterEventListener get onEnter => _handleEnter;
  ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.55-beta/lib/src/slider.dart:1917:3: Error: Type 'PointerExitEventListener' not found.
  PointerExitEventListener get onExit => _handleExit;
  ^^^^^^^^^^^^^^^^^^^^^^^^
Failed to compile application.
```

**Comment by ervindobri** [comment] 2021-04-11 07:27
I have the same error on my windows laptop. 
MacOS was working fine.

**Comment by LakshmiRadhaKrishnan** [comment] 2021-04-12 12:34
Hi,

We are not able to reproduce the issue. Can you confirm whether you are facing this in older version of Flutter? Please check our system requirements here.

https://help.syncfusion.com/flutter/system-requirement-installation/system-requirements  

We kindly request you to share the output of flutter doctor -v if you still face the issue.

Regards,
Lakshmi R.

**Comment by mukai154** [comment] 2021-04-14 00:46
This seems to be the reason why
https://flutter.dev/docs/release/breaking-changes/mouse-tracker-no-longer-attaches-annotations

**Comment by LakshmiRadhaKrishnan** [comment] 2021-04-14 09:08
Hi,

Thanks for your inputs.

The reported issues are compile time issues. The above mentioned breaking issue is run time behavior changes in framework and it is a different one.

Please let us know if the compilation issues are still happening.

Regards,
Lakshmi R.

**Comment by narumishi** [comment] 2021-04-17 06:16
I have to add import sentance

**Comment by LakshmiRadhaKrishnan** [comment] 2021-04-20 13:03
Hi,  
  
In the Flutter latest beta version (2.2.0-10.1.pre), the MouseTrackerAnnotation class has been moved from “package:flutter/rendering.dart” to “package:flutter/services.dart” library. We have fixed this in our source and this fix will be included in our next weekly NuGet on April 27th, 2021.  
  
Regards,  
Lakshmi R.

**Comment by robertoltrocha** [comment] 2021-04-21 21:09
Hi,
I have the similar error **MouseTrackerAnnotation** and  **PointerEnterEventListener**.

```
[√] Flutter (Channel beta, 2.2.0-10.1.pre, on Microsoft Windows [versÃ£o 10.0.19042.928], locale pt-BR)
    • Flutter version 2.2.0-10.1.pre at C:\src\flutter
    • Framework revision 0941968447 (6 days ago), 2021-04-15 12:01:02 -0700
    • Engine revision d2a2e93510
    • Dart version 2.13.0 (build 2.13.0-211.6.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\rocha\AppData\Local\Android\sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.53.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.20.0
```


```
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.57-beta/lib/src/range_selector.dart:1863:16: Error: Type 'MouseTrackerAnnotation' not found.
    implements MouseTrackerAnnotation {
               ^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.57-beta/lib/src/range_selector.dart:2950:3: Error: Type 'PointerEnterEventListener' not found.
  PointerEnterEventListener? get onEnter => null;
  ^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.57-beta/lib/src/range_selector.dart:2954:3: Error: Type 'PointerHoverEventListener' not found.
  PointerHoverEventListener get onHover => _handleHover;
  ^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.57-beta/lib/src/range_selector.dart:2957:3: Error: Type 'PointerExitEventListener' not found.
  PointerExitEventListener get onExit => _handleExit;
  ^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.57-beta/lib/src/range_slider.dart:1655:16: Error: Type 'MouseTrackerAnnotation' not found.
    implements MouseTrackerAnnotation {
               ^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.57-beta/lib/src/range_slider.dart:2552:3: Error: Type 'PointerEnterEventListener' not found.
  PointerEnterEventListener? get onEnter => null;
  ^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.57-beta/lib/src/range_slider.dart:2556:3: Error: Type 'PointerHoverEventListener' not found.
  PointerHoverEventListener get onHover => _handleHover;
  ^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.57-beta/lib/src/range_slider.dart:2559:3: Error: Type 'PointerExitEventListener' not found.
  PointerExitEventListener get onExit => _handleExit;
  ^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.57-beta/lib/src/slider.dart:1497:57: Error: Type 'MouseTrackerAnnotation' not found.
class _RenderSlider extends RenderBaseSlider implements MouseTrackerAnnotation {
                                                        ^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.57-beta/lib/src/slider.dart:1918:3: Error: Type 'PointerEnterEventListener' not found.
  PointerEnterEventListener get onEnter => _handleEnter;
  ^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/syncfusion_flutter_sliders-19.1.57-beta/lib/src/slider.dart:1921:3: Error: Type 'PointerExitEventListener' not found.
  PointerExitEventListener get onExit => _handleExit;
  ^^^^^^^^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by LakshmiRadhaKrishnan** [comment] 2021-04-22 06:21
Hi,

As we mentioned in our last update, we will include the fix for this issue in our next weekly NuGet on April 27th, 2021.

Regards,
Lakshmi R.

**Comment by LakshmiRadhaKrishnan** [comment] 2021-04-27 12:28
Hi,

As we mentioned earlier, we have included fix for the reported issue in our latest weekly release (19.1.58-beta). Kindly check and confirm us whether the issue resolved in your side.

Regards,
Lakshmi R.

**Comment by robertoltrocha** [comment] 2021-04-27 19:05
Hi @LakshmiRadhaKrishnan,

It is working.

thanks

**Closed** 2021-05-03 05:37 UTC

**Comment by NidhiPatel77** [comment] 2021-05-19 10:13
Hi @robertoltrocha 

I'm having the same error MouseTrackerAnnotation and PointerEnterEventListener.

Can you guide me how did you resolve this?
