### ISSUE TITLE
[SfPdfViewer] Poor rendering quality on iOS when zoom >= 3

### ISSUE THREAD

**Issue by orestesgaolin** [syncfusion/flutter-widgets#1363] opened 2023-08-30 07:14 UTC
First of all thanks for sharing such a good package with wider community.

**The issue**

Rendering quality is much lower on iOS than on Android when zooming in. Even when using vector images the preview is a little bit blurred. The issue is much less prellevant on Android.

**Examples**

Both at `maxZoomLevel = 5`

| Android | iOS |
| ---- | ---- |
| ![Screenshot_20230830_091035](https://github.com/syncfusion/flutter-widgets/assets/16854239/b9dae25a-18da-4153-b7fd-4c17b15cff0c) | ![IMG_0CF93543035A-1](https://github.com/syncfusion/flutter-widgets/assets/16854239/d9b68b16-8d2b-47fc-bf81-67df57025513) |

I suspect this is due to the fact that the image requested from the platform is the same no matter what the zoom level. 

**Tech details**

- syncfusion_flutter_pdfviewer: ^22.2.11
- Flutter 3.13
- Android 13
- iOS 16.6

**Comment by deepika134** [comment] 2023-09-07 13:05
We confirmed the issue “The PDF page rendering quality is lower on iOS than on Android when zooming in SfPdfViewer” is a defect and logged a defect report for this issue. The fix for the same will be included in our September 19th weekly release.

Use the below feedback link to track the status of the reported bug.
https://www.syncfusion.com/feedback/46708/the-pdf-page-rendering-quality-is-lower-on-ios-than-on-android-when-zooming-in 

**Disclaimer:** “Inclusion of this solution in the weekly release may change due to other factors including but not limited to QA checks and works reprioritization.”

**Comment by deepika134** [comment] 2023-09-27 03:46
The issue “The PDF page rendering quality is lower on iOS when zooming in SfPdfViewer” has been resolved, and the fix is included in our September 26th weekly release. Please find the Pub.dev link below:

[syncfusion_flutter_pdfviewer | Flutter Package (pub.dev)](https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/23.1.38)

**Closed** 2024-02-08 07:51 UTC
Labels: pdf_viewer
