### ISSUE TITLE
Pdf Page is overlap when it show in two different screen 

### ISSUE THREAD

**Issue by nimisharanipabacancy** [syncfusion/flutter-widgets#388] opened 2021-09-28 07:35 UTC
I  am using syncfusion_flutter_pdfviewer library. I have tabbar in bottom and show different pdf in different page. When I switch tab multiple time and then scroll second pdf it show first tab pdf page. Here is issue video

### https://drive.google.com/file/d/12Q-H-tv3RRAwI2dLERqCAkP_4l_aArXJ/view

```
import 'package:custom_app_bar/utils/images.dart';
import 'package:flutter/material.dart';
import 'package:syncfusion_flutter_pdfviewer/pdfviewer.dart';

import 'app_bottom_bar.dart';

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int selectedItemIndex = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(

      body: Center(
        child: IndexedStack(
          index: selectedItemIndex,
          children: [
            SfPdfViewer.network(
              "https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf",
            ),
            SfPdfViewer.network(
                "https://www.ets.org/Media/Tests/GRE/pdf/gre_research_validity_data.pdf"
            ),
            Container(
              child: Text("Demo"),
            )

          ],
        ),
      ),
      bottomNavigationBar: BottomNavigationBar(
          items: const <BottomNavigationBarItem>[
            BottomNavigationBarItem(
                icon: Icon(Icons.home),
                title: Text('Home'),
                backgroundColor: Colors.green
            ),
            BottomNavigationBarItem(
                icon: Icon(Icons.search),
                title: Text('Search'),
                backgroundColor: Colors.yellow
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.person),
              title: Text('Profile'),
              backgroundColor: Colors.blue,
            ),
          ],
          type: BottomNavigationBarType.shifting,
          currentIndex: selectedItemIndex,
          selectedItemColor: Colors.black,
          iconSize: 40,
          onTap: (index) {
            setState(() {
              selectedItemIndex = index;
            });
          },
          elevation: 5
      ),
    );
  }
}
```

**Comment by deepika134** [comment] 2021-10-01 13:59
Hi nimisharanipabacancy,

We confirmed that the issue with " Pdf Page is overlap when it show in two different screen " is a defect. The issue fix will be included in our October 3rd weekly NuGet release which is estimated to be available on 19th October 2021 tentatively.

The status of this issue can be tracked using following link. 
https://www.syncfusion.com/feedback/29138/pdf-pages-gets-overlapped-when-placing-more-one-sfpdfviewer-widget-in-indexedstack

Regards,
Deepika R

**Comment by nimisharanipabacancy** [comment] 2021-10-05 07:26
Thank you for give attention and solve issue quickly. It will be great if you provide beta release or push code in particular branch so we can use it until new release on 19th October 2021.

**Comment by deepika134** [comment] 2021-10-06 10:57
Hi nimisharanipabacancy,

We regret for the inconvenience.

We are working on the reported issues and currently, Syncfusion doesn't provide custom patches for issue fixes. As we mentioned earlier, we will include the fix in our October 3rd weekly release as promised.

Regards,
Deepika R

**Comment by nimisharanipabacancy** [comment] 2021-10-19 15:04
Any update for release new version with this bug fix?

**Comment by deepika134** [comment] 2021-11-11 02:44
Hi nimisharanipabacancy, 

Due to stability concerns, we are unable to include the issue fix in our 2021 Volume 3 SP1 release. As the reported issue fix requires changes in syncfusion_flutter_pdfviewer_platform_interface which need to be ensured in all platforms so we have planned to include this major implementation in our 2021 Volume 4 release which is estimated to be available by the second week of December 2021 tentatively. 

Regards, 
Deepika Ravi.

**Comment by deepika134** [comment] 2021-12-20 07:13
Hi nimisharanipabacancy, 

We have included the fix for this issue “Pdf Page is overlap when it show in two different screen” in our latest volume 4 release, so kindly upgrade to the latest version v19.4.38 to get the issue resolved.    
Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/19.4.38-beta 

We are glad to announce that our Essential Studio 2021 Volume 4 Main Release V19.4.0.38 is rolled out and is available for download under the following link.
https://www.syncfusion.com/forums/171304/essential-studio-2021-volume-4-main-release-v19-4-0-38-is-available-for-download 

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Deepika Ravi

**Closed** 2022-01-10 06:19 UTC
