### ISSUE TITLE
[syncfusion_flutter_charts] When tapping on an external label with a large description on Android, the tooltip is not displayed

### ISSUE THREAD

**Issue by mdmota** [syncfusion/flutter-widgets#1848] opened 2024-05-04 20:21 UTC
### Bug description

syncfusion_flutter_charts: ^25.1.41+2

I created a circular chart and some outside labels are large and do not appear completely on the screen. When you tap on the label, the tooltip is displayed on iOS and on the Anroid emulator version 13. On a physical cell phone with Android 14, when you tap on the label, it is not displayed on the tooltip.

### Steps to reproduce

Create a chart with a large label and tap on it on Android 14.
The label has 'text...' but when tapped it does not display the full text

### Code sample

```
SfCircularChart _buildSmartLabelPieChart() {
    return SfCircularChart(
      title: ChartTitle(text:tittle, textStyle: TextStyle(fontSize: 14, fontWeight: FontWeight.w600)),
      series: _gettSmartLabelPieSeries(),
      tooltipBehavior: TooltipBehavior(enable: true, header: '', format: 'point.x', decimalPlaces: 2),
    );
  }

  /// Returns the pie series with smart data labels.
  List<PieSeries<ChartData, String>> _gettSmartLabelPieSeries() {
    return <PieSeries<ChartData, String>>[
      PieSeries<ChartData, String>(
          name: title,
          dataSource: listData,
          xValueMapper: (ChartDatadata, _) => data.x as String,
          yValueMapper: (ChartDatadata, _) => data.y,
          dataLabelMapper: (ChartDatadata, _) =>  data.x + ' ${data.xValue}',
          radius: '60%',
          dataLabelSettings: DataLabelSettings(
              margin: EdgeInsets.zero,
              isVisible: true,
              labelPosition: ChartDataLabelPosition.outside,
              connectorLineSettings: const ConnectorLineSettings(
                  type: ConnectorType.curve, length: '20%'),
              labelIntersectAction: LabelIntersectAction.shift))
    ];
  }
```

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

[Upload media here]

</details>

### Stack Traces

dont stack

### On which target platforms have you observed this bug?

Android

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [versÆo 10.0.22631.3447], locale pt-BR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web

**Comment by Kaviyarasansf4298** [comment] 2024-05-07 11:37
Hi,

We have replicated the issue you reported on our end. The tooltip does not display when tapping on a data label with a large description. In order to thoroughly investigate the root cause at the source level, we need some time, so this issue is scheduled to be fixed in our upcoming weekly release which is scheduled on **May 14, 2024**. We will provide you with more information. We appreciate your understanding and patience until then.

Regards,
Kaviyarasan A.

**Closed** 2024-06-05 03:58 UTC
Labels: bug, charts, fixed
