### ISSUE TITLE
[syncfusion_pdfviewer] After zoom in, on Android, the alignment become not centered.

### ISSUE THREAD

**Issue by sejun2** [syncfusion/flutter-widgets#883] opened 2022-09-13 09:18 UTC
Below is widget code

 _buildPdfSection() {
    return Container(
      child: SfPdfViewer.file(
        File(controller.filePath.toString()),
        controller: controller.pdfViewerController,
        password: controller.pdfPassword,
        onDocumentLoaded: (details){
          controller.syncPage(0);
        },
        onPageChanged: (details){
          controller.currentPage = details.newPageNumber;
          // controller.totalPage = details.page?? 0;
        },
        pageLayoutMode: PdfPageLayoutMode.single,
        scrollDirection: PdfScrollDirection.horizontal,
        canShowPaginationDialog: false,
        canShowPasswordDialog: false,
        canShowHyperlinkDialog: false,
        canShowScrollHead: false,
        canShowScrollStatus: false,
      ),
    );

After zoom in, alignment move to right from center. 
The code above works fine on iOS and IpadOS, but android.

**Comment by ManigandanShanmugam** [comment] 2022-09-14 14:02
Hi @sejun2 

We tried to reproduce the reported issue with provided details, but the alignment is proper after  performing zoom in our side. For your reference, we have prepared a sample (along with the output screen record of the same) and it can be downloaded from the following link,

https://www.syncfusion.com/downloads/support/directtrac/general/ze/SA1C33~1-1169796735.zip

Kindly let us know if you are facing the reported issue with this sample. Also, please share the following details, to reproduce the reported issue on our end.
1. Device Specification.
2. Flutter Doctor log.
3. syncfusion_flutter_pdfviewer package version.
4. Flutter SDK version.
5. Issue reproducing video.
These information will be helpful for us to provide you a prompt solution at the earliest.

**Comment by sejun2** [comment] 2022-09-16 08:32
@ManigandanShanmugam 

Here I provide details.

1. Device spec
Samsung galaxy tab a8 (SM-X200)
2. Flutter doctor log
```
➜  1Hour_Flutter git:(refactoring/source_player) ✗ fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.1, on macOS 12.4 21F79 darwin-arm, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
[✓] Connected device (5 available)
[✓] HTTP Host Availability

```
3. syncfusion_flutter_pdfviewer package version
20.2.48+beta, 20.2.49+beta

4. Flutter SDK version
3.3.1, 3.3.0

5. Reproducing video

https://user-images.githubusercontent.com/33044667/190594074-8953a943-7f0a-4b3b-a68c-e5842efc2450.mp4

**Comment by deepika134** [comment] 2022-09-19 10:24
Hi @sejun2,

We are checking on this reported issue and will update the details on September 21,2022.

Regards,
Deepika

**Comment by sejun2** [comment] 2022-09-20 02:19
@deepika134 @ManigandanShanmugam 
It has still same issue. 
Your sample code is perfectly working but, when I set horizontal empty space to sfPdfviewer, same thing happens.

If I wrap sfPdfViwer with Container(width: Mediaquery.of(context).size.width, height: MediaQuery.of(context).siez.height/2), then it makes padding horiztonaly because the pdfViewer fits it's height to Container widget. 
Afther that, zoomming in makes same thing happen.

Best wishes,

**Comment by sejun2** [comment] 2022-09-20 02:23
In sample code you provided, I wrapped the sfPdfviwer widget like this.

```dart
body: Container(
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.height/2,
        child: SfPdfViewer.network(
          'https://cdn.syncfusion.com/content/PDFViewer/flutter-succinctly.pdf',
          key: _pdfViewerKey,
          controller: pdfViewerController,
          onDocumentLoaded: (details) {},
          onPageChanged: (details) {

          },
          pageLayoutMode: PdfPageLayoutMode.single,
          scrollDirection: PdfScrollDirection.horizontal,
          canShowPaginationDialog: false,
          canShowPasswordDialog: false,
          canShowHyperlinkDialog: false,
          canShowScrollHead: false,
          canShowScrollStatus: false,
        ),
      ),
```

**Comment by ManigandanShanmugam** [comment] 2022-09-20 17:29
Hi @sejun2,

We have confirmed that the issue “PDF pages are not aligned properly when zooming is performed in the single page layout mode” is a defect and logged a defect report for this issue.The fix for the same will be included in our upcoming weekly NuGet release which is scheduled to be published on October 4, 2022.

The status of this issue can be tracked using following link.
https://www.syncfusion.com/feedback/37862/pdf-pages-are-not-aligned-properly-when-zooming-is-performed-in-the-single-page

Regards,
Manigandan S

**Comment by deepika134** [comment] 2022-10-05 04:19
Hi Sejun,

We regret for the inconvenience.

We have fixed the reported issue. In testing phase, we found few breaks due to this issue fix, so we are unable to include the issue fix in our latest weekly release. We will fix the breaks and include this issue fix in our next weekly package release which is on 11 October 2022.

Regards,
Deepika R

**Comment by deepika134** [comment] 2022-10-11 14:10
Hi @sejun2 ,

Thank you for your patience.

We have included the fix for this issue “PDF pages are not aligned properly when zooming is performed in the single page layout mode” in our latest weekly NuGet release, so kindly upgrade to the latest version v20.3.49 to get the issue resolved.

Package link: https://pub.dev/packages/syncfusion_flutter_pdfviewer/versions/20.3.49

Regards,
Deepika R

**Closed** 2022-12-29 07:44 UTC
