### ISSUE TITLE
Barchart greyed in release build

### ISSUE THREAD

**Issue by iOSTest321** [syncfusion/flutter-widgets#1096] opened 2023-02-25 06:45 UTC
Hi team, i'm using syncfusion_flutter_charts: ^20.4.50 in my app i'm added the bar chart it works previously.  Now the release build show greyedout but it works in debug build. please help in this issue

Flutter 3.7.5 • channel stable •Dart 2.19.2 • DevTools 2.20.1

**Comment by Yuvaraj-Gajaraj** [comment] 2023-02-27 12:07
We have checked the [BarSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/BarSeries-class.html) with the latest flutter SDK version 3.7.5, Dart version 2.19.2, and syncfusion_flutter_charts version 20.4.51, and ensured that in both release and debug mode, it is working fine and the bar chart is not greyed out. We have shared the screenshot and sample below for your reference.

​
Unfortunately, we are not able to reproduce the reported issue as we are not exactly sure in which scenario the issue is replicating. So, we kindly request you to share more information on your requirement in detail, along with screenshots or screen recordings or try to replicate the reported issue in the below-attached test sample and revert us so that it will help us assist you in a better way.



Screenshot:
Release | Debug
-- | --
<img src='https://user-images.githubusercontent.com/61863686/221559153-fc8f598b-6df1-487b-b9d7-be50b8b9384b.png' width=200px/> |  <img src='https://user-images.githubusercontent.com/61863686/221559211-ec0d03a2-1cf4-46e7-8b96-946400763522.png' width=200px/>

Sample: 
[i442087.zip](https://github.com/syncfusion/flutter-widgets/files/10839444/i442087.zip)

**Comment by rogervdf** [comment] 2023-11-18 14:50
We have a similar (or perhaps identical) problem where compiling in debug works fine, while in profile and release mode the x-axis and chart content are consistently and/or occasionally bugged. Not sure where to start looking in this case.

Release (left) and debug (right) side-by-side

![image](https://github.com/syncfusion/flutter-widgets/assets/43315295/7ac949c7-0890-4c8d-a252-ace11a0066b6)

![image](https://github.com/syncfusion/flutter-widgets/assets/43315295/dd752293-fda8-4e1b-a266-0dc73403aa2d)

**Comment by LokeshPalani** [comment] 2024-02-14 13:28
Hi @rogervdf,

We have checked the [BarSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/BarSeries-class.html) in both release mode and debug mode, it was working fine at our end. We have checked with the below mentioned versions.

Flutter SDK version: 3.16.9
syncfusion_flutter_charts version: 24.2.5
Dart version: 3.2.6

We kindly request you to try to replicate the reported issue in the below-attached test sample and revert us so that it will help us assist you in a better way.

**Screenshot:**

Release Mode:
 
![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/54ff4b75-5d34-4bb1-894f-9355c09de639)


Debug Mode:
 
![image](https://github.com/syncfusion/flutter-widgets/assets/105289202/6878e4d1-0a03-4873-b472-d4bd124577ff)


Regards,
Lokesh P.

[github_1097.zip](https://github.com/syncfusion/flutter-widgets/files/14279951/github_1097.zip)

**Comment by rogervdf** [comment] 2024-02-14 20:27
Hi @LokeshPalani

It's not currently possible to do this test for us. Moving to flutter 3.16 breaks too many things in too many of our flutter apps, so we are sticking with 3.13.9. Also some widgets we use have problems with 3.16's breaking changes. This also means we can't use the latest versions of your libraries, which already moved to 3.16.

When we do move to 3.16 we'll look into this again

**Comment by LokeshPalani** [comment] 2024-02-15 09:34
Hi @iOSTest321,

Thank you for the update. We will close this GitHub issue, and you can create a new one if you are facing any issues with the latest version of the **syncfusion_flutter_charts** package. We are always here to assist you.

Regards,
Lokesh P.

**Closed** 2024-02-15 09:36 UTC
Labels: charts, waiting for customer
