### ISSUE TITLE
Annoying behaviour on each action user do !

### ISSUE THREAD

**Issue by farisshomali** [syncfusion/flutter-widgets#1592] opened 2023-12-21 08:26 UTC
Can someone please describe to me what is this ?

[VERBOSE-2:dart_isolate.cc(1097)] Unhandled exception:
Invalid argument (Header of the stream can not be read.): -1
#0      CompressedStreamReader._readZlibHeader (package:syncfusion_flutter_pdf/src/pdf/implementation/compression/compressed_stream_reader.dart:220:7)
#1      CompressedStreamReader._initialize (package:syncfusion_flutter_pdf/src/pdf/implementation/compression/compressed_stream_reader.dart:212:7)
#2      new CompressedStreamReader (package:syncfusion_flutter_pdf/src/pdf/implementation/compression/compressed_stream_reader.dart:12:5)
#3      PdfZlibCompressor.decompress (package:syncfusion_flutter_pdf/src/pdf/implementation/compression/pdf_zlib_compressor.dart:22:43)
#4      PdfStream._decompressData (package:syncfusion_flutter_pdf/src/pdf/implementation/primitives/pdf_stream.dart:164:27)
#5      PdfStream.decompress (package:syncfusion_flutter_pdf/src/pdf/implementation/primitives/pdf_stream.dart:125:24)
#6      PdfPageLayerCollectionHelper._combineProcess (package:syncfusion_flutter_pdf/src/pdf/implementation/pages/pdf_page_layer_collection.dart:191:23)
#7      PdfPageLayerCollectionHelper._combineContent (package:syncfusion_flutter_pdf/src/pdf/implementation/pages/pdf_page_layer_collection.dart:167:22)
#8      PdfPageLayerCollectionHelper.combineContent (package:syncfusion_flutter_pdf/src/pdf/implementation/pages/pdf_page_layer_collection.dart:104:12)
#9      PdfTextExtractor._getRecordCollection (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:914:14)
#10     PdfTextExtractor._getText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:284:51)
#11     PdfTextExtractor._searchInBackground (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:593:29)
#12     PdfTextExtractor._findText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:232:14)
#13     PdfTextExtractor.findText (package:syncfusion_flutter_pdf/src/pdf/implementation/exporting/pdf_text_extractor/pdf_text_extractor.dart:161:12)
#14     SfPdfViewerState._findTextAsync (package:syncfusion_flutter_pdfviewer/src/pdfviewer.dart:4766:57)
<asynchronous suspension>

What do you mean by Header of the stream can not be read ? i'm only doing a search on a text!

**Comment by ramkumarsync** [comment] 2024-02-14 10:56
We tried to replicate the issue on our end with the stack trace shared but unfortunately, we couldn't reproduce the issue. We suspect that this issue is specific to the document. Could you please check whether the same issue occurs with our latest version (v24.2.5)? 

If the issue persists, kindly share the document that would help us analyze the issue further and provide you solution at the earliest.

**Comment by ramkumarsync** [comment] 2024-03-14 06:34
Since we don't have enough information to proceed further, we are closing this. However, you can reopen this issue anytime and share the requested details to make progress. Also, please feel free to contact us if you need any further assistance.

**Closed by ramkumarsync** 2024-03-14 06:34 UTC
Labels: pdf_viewer, waiting for customer
