### ISSUE TITLE
[syncfusion_flutter_pdfviewer] App crashing after getting Out of Memory exception while rendering multiple Pdfs

### ISSUE THREAD

**Issue by ritz-ch** [syncfusion/flutter-widgets#362] opened 2021-09-03 14:20 UTC
The app I am working on solely depends on the syncfusion_flutter_pdfviewer package since it's a small app which involves opening a pdf from a list , searching text, saving its content to favourites. After rendering pdfs  multiple times I am getting Out of Memory Exception and my app is getting crashed on iOS device(not on simulator) but it is running fine on Android devices.
I am attaching below the screenshots for Out Of Memory exception and video for the app crashing. @syncfusion

**Device configurations  for iOS device **
iphone 8 Plus
Model number: MQ8D2HN/A
Software Version: 13.1.2 
RAM -3GB

**1.  Out of Memory Exception  screenshot_**

![image (4)](https://user-images.githubusercontent.com/60787872/132019301-35f5d330-8630-488b-9270-9886a2a29472.png)

**2.  _Video for app crashing on iOS device_**
https://user-images.githubusercontent.com/60787872/132019544-80a3d69e-045c-48e0-8eb9-cafbe8d2c6b4.mp4

**3.  Dart Dev Tools Memory usage screenshot_**

![image (5)](https://user-images.githubusercontent.com/60787872/132019693-95696872-b732-4e24-a418-454097796d42.png)

**Comment by sarathkumar50** [comment] 2021-09-06 12:41
Hi @ritz-ch ,

We tried to reproduce the reported issue in different iOS devices and the documents were loaded properly. We are trying to reproduce the reported issue in other iOS simulators. We will update the further analysis details on 8 September 2021.
 
Kindly share us the issue reproducing document which will be helpful for us to provide you a prompt solution at the earliest.
 
You can also contact us through our [support forums](https://www.syncfusion.com/forums), [Direct-Trac](https://www.syncfusion.com/support/directtrac/), or [feedback portal](https://www.syncfusion.com/feedback/xamarin-forms). We are always happy to assist you!

Regards,
Sarath Kumar

**Comment by ritz-ch** [comment] 2021-09-07 05:17
Hi @sarathkumar50 ,
I am getting the issue while working with the following documents:

[Instagram Guide.pdf](https://github.com/syncfusion/flutter-widgets/files/7119024/Instagram.Guide.pdf)
[Plumbing Part 2.pdf](https://github.com/syncfusion/flutter-widgets/files/7119025/Plumbing.Part.2.pdf)

**Comment by achinverma** [comment] 2021-09-08 07:32
@sarathkumar50 , I am also facing the issue. 

OutOfMemory
The OS most likely terminated your app because it overused RAM.

iOS
Version:13.2.2

iPhone 8
Arch:x86

**Comment by sarathkumar50** [comment] 2021-09-09 05:07
Hi ritz-ch, 

We tried to reproduce the reported issue from our side with provided PDF documents but we did not face any app crashes after rendering PDF document multiple times and it is loaded properly.
To check further on this, we like to have meeting and looking the issue in your machine. So, kindly a create a incident in our support site and mention your convenience time for the meeting.
https://www.syncfusion.com/support/directtrac/incidents

Regards,
Sarath Kumar.

**Comment by ritz-ch** [comment] 2021-09-10 04:40
Hi @sarathkumar50 ,
I have created an incident with ID: 341994 on your support site. 
For the meeting call we are available between 9:30 AM IST  to 7:00 PM IST (Monday-Friday). It would be nice if we could schedule it today, you can pick the meeting time as per your convenience.

**Comment by dharanidharandharmasivam** [comment] 2021-10-20 04:58
Hi @ritz-ch ,

Since you have created an [incident](https://www.syncfusion.com/support/directtrac/incidents/341994), kindly follow up with the same for further queries and we are closing this now.

Thanks,
Dharani.

**Closed** 2021-10-20 05:20 UTC
