### ISSUE TITLE
Multiple Datatable inside loop

### ISSUE THREAD

**Issue by wfybiz4** [syncfusion/flutter-widgets#1776] opened 2024-03-29 18:29 UTC
I am trying to show 2 different datatable with different data inside a product loop and table will have multiple data based on product id. Your help will be very helpful to me.

**Comment by abineshPalanisamy** [comment] 2024-04-01 10:24
Hi @wfybiz4 ,
 
Based on the information provided, it appears that you are expecting multiple DataTable inside a loop. Using ListView.builder, you can construct multiple DataGrid's with the necessary counts. We have included a sample file for your reference.
 
If the provided sample does not meet your requirements, we kindly ask you to modify it to reflect the expected behavior and provide further details. This will greatly assist us in investigating and promptly delivering an appropriate solution.

- **Sample :** 

    [SfDataGrid.zip](https://github.com/syncfusion/flutter-widgets/files/14822491/SfDataGrid.zip)

 
Regards,
Abinesh P

**Comment by wfybiz4** [comment] 2024-04-01 14:22
Thank you for your help. But I have already solve the issue. Your solution is good but I have already solve it by converting the data object for table into model then populating data from model to datatable into the widget in relation to the product ID.

**Comment by ashok-kuvaraja** [comment] 2024-04-02 04:50
Hi @wfybiz4,

We are closing this issue since it is resolved on your end. If you need any further assistance, kindly reopen this issue. We are always happy to help you.

Regards,
Ashok K

**Comment by wfybiz4** [comment] 2024-04-02 05:26
It would be nice if we could select row or rows if the value or index is equal to the give data in the initial load. Like onTap, onSelected, onChanded, same with intial(value).

**Comment by abineshPalanisamy** [comment] 2024-04-02 09:51
Hi @wfybiz4 ,
 
Based on the information provided, it seems you want to select the rows upon loading. Please refer to the following Knowledge Base link to gain a deeper understanding of how to achieve this. You can customize the provided code to align it with your specific requirements.
 
To select the rows if the value is equal to the given data on the initial load, you need to list the rows containing the desired value and add them to controller.selectedRows. Please refer to the following code snippet for a better understanding.
 
If this does not meet your requirements, please provide additional clear details. This will greatly assist us in investigating and providing an appropriate solution as quickly as possible.
 
KB Link - [Select the rows](https://support.syncfusion.com/kb/article/11359/how-to-select-the-rows-in-flutter-datatable-sfdatagrid-on-loading)

- **Code snippets :** 
``` dart
  @override
  void initState() {
    super.initState();
    employees = getEmployeeData();
    employeeDataSource = EmployeeDataSource(employeeData: employees);
    List<DataGridRow> selectedRows = employeeDataSource._employeeData
        .where((row) => getCellValue(row) == 10001)
        .toList();
    controller.selectedRows = selectedRows;
  }
 
  dynamic getCellValue(DataGridRow row) {
    // chose 'id' column since it contains the unique values in my collection.
    // If you use a column that contains the duplicate values, it will not work effectively for this case.
    return row
        .getCells()
        .firstWhere((element) => element.columnName == 'id')
        .value;
  }
```

Regards,
Abinesh P

**Comment by ashok-kuvaraja** [comment] 2024-04-16 07:17
Hi @wfybiz4,

We suspect that the reported issue has been resolved at your end. We're closing this issue now. If you need any further assistance, kindly reopen this ticket. We are always happy to help you.

Regards,
Ashok K

**Closed by ashok-kuvaraja** 2024-04-16 07:17 UTC
Labels: data_grid, waiting for customer response
