### ISSUE TITLE
[syncfusion_flutter_xlsio]  Conflict error with packages Image 4.0.10

### ISSUE THREAD

**Issue by danilocatalanoapsystem** [syncfusion/flutter-widgets#1045] opened 2023-01-20 16:54 UTC
Because syncfusion_flutter_xlsio 20.4.44-beta depends on image ^3.0.1 and no versions of syncfusion_flutter_xlsio match >20.4.44-beta <21.0.0, syncfusion_flutter_xlsio ^20.4.44-beta requires image ^3.0.1.
So, because "app" depends on both syncfusion_flutter_xlsio ^20.4.44-beta and image ^4.0.10, version solving failed.
pub get failed (1; So, because "app" depends on both syncfusion_flutter_xlsio ^20.4.44-beta and image ^4.0.10, version solving failed.)

**Comment by KonduruKeerthi** [comment] 2023-01-27 06:31
We have confirmed the issue as **Pub get failed while using the image package version above ^4.0.0** and logged a defect report. We will include the fix for this issue in our weekly NuGet release scheduled for the **second week of February 2023**. You will be informed regarding this once the fix is included.

 

You can track the status of this defect report through the feedback link below.

https://www.syncfusion.com/feedback/40609/pub-get-failed-while-using-the-image-package-version-above-4-0-0

 

**Disclaimer:** Inclusion of this solution in the weekly release may change due to other factors including but not limited to QA checks and works reprioritization.

**Comment by RahulBalasundaramSF3494** [comment] 2023-02-15 12:48
We have included the fix for **Pub get failed while using the image package version above ^4.0.0** in our weekly NuGet release version **20.4.49**. Please upgrade your package to this version and let us know if the issue is resolved.



Latest NuGet Package: https://pub.dev/packages/syncfusion_flutter_xlsio/versions/20.4.49-beta

**Closed** 2024-03-19 11:00 UTC
Labels: xlsIO
